### ISSUE TITLE
Search complete "no results found" message

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#100]
Hi

When carrying out a search using the connectors, we are still getting the search complete and no results found messages. The waiting time isn't the problem, it's just that those messages are misleading as the search hasn't really finished yet. I've done a video of the delay. After 25 seconds or so it returns results:

http://www.screencast.com/t/TRLtC6jJds2 

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for that, and thanks for the video, very helpful. I'll take a look at why that message is being displayed, it shouldn't be displayed until the search is complete, however the progress bar suggests that it thinks the search is complete before it actually is.

The search seems inordinately slow also, it shouldn't be taking that long. I'll investigate this also.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
@AndrewIsh I'm wondering if there's any update on this one?

**Comment by AndrewIsh** [comment]
@mrenvoize The slow search problem should now be resolved. The changes made to fix it should also have fixed the problem with the no results message being displayed prematurely. I am now unable to replicate it. If @richughes is still experiencing problems, please let us know.

Closing.
