### ISSUE TITLE
Pop-up hover text appears in the wrong place

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#101]
Good morning,

The pop-up hover text appears in the wrong place (too low) - on the attached picture my mouse was hovering over the "JB Test - Week 2" text. The same happens when hovering over any other list.

![image](https://cloud.githubusercontent.com/assets/16195154/13738816/5687689c-e9bf-11e5-8fb4-3333933d7881.png)

All the best,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for that, I'll create an issue at our end.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1689

**Comment by AndrewIsh** [comment]
Hi Joanna

This problem has now been fixed. I'll close this issue. Feel free to re-open it if you're still seeing it.

Many thanks
Andrew
