### ISSUE TITLE
Search for adding new items doesn't work (15:00)

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#103]
Hello,

I have created a new list to start fresh, but when I try to find some items in the catalogue, the search doesn't work. When I input the search query and press enter I am getting only a blank screen:

https://youtu.be/_JBo4bwqxCM

Thanks,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for that. There appears to be a problem with searching on preview2 at the moment, apologies for the inconvenience. I'll let you know once it's sorted out.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Joanna

This is now fixed, thanks for alerting us to the problem.

I'll close this issue now.

Many thanks
Andrew
