### ISSUE TITLE
Odd behaviour of the reading list (08:30)

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#104]
Hello,

I have tried to add a few items through search (which is working fine now, thanks!) to my newly created reading list, but got into some weird kind of loop, which stops me from doing any work on the list. Video:

https://youtu.be/YrzgNP8u2ds

Thanks a lot,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks very much for this. I'm a bit puzzled by the behaviour you're seeing. I'll ask @mrenvoize to take a look too as this might affect his side of things.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Joanna

I recently pushed out a fix that should have addressed this. Can you check if you're still seeing the problem and let me know please?

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hello,

I haven't experience this issue for quite a while. Thanks!

**Comment by AndrewIsh** [comment]
Great. I'll close this issue for now, feel free to re-open if you see it again.
