### ISSUE TITLE
Rebus listit - no results

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#107]
Hi

We aren't getting any results on Rebuslist it from our library catalogue or on Amazon. Trying the same record on each site produces no result. 

It works via the Summon connector within a list, so it definitely looks like a listit issue. I tried deleting the bookmarklet from the favourites bar and retrying but it made no difference. 

![rebus listit amazon](https://cloud.githubusercontent.com/assets/17139950/13874837/30dc7afc-ecf2-11e5-8c20-7234b1b698d4.png)
![rebus listit libcat](https://cloud.githubusercontent.com/assets/17139950/13874838/32ccdde8-ecf2-11e5-98e5-ba9b004c28fa.png)

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for that, I'll take a look now.

Regards
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1694

**Comment by AndrewIsh** [comment]
Hi Richard

This is now fixed, apologies for the delay. You should not need to re-add the bookmarklet, you will however, need to refresh your browser tab.

I'll close this issue, if you continue to see problems, feel free to re-open.

Many thanks
Andrew
