### ISSUE TITLE
[Manage Hierarchy suggestion] Add child list & delete options

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#108]
Hi,

Just a suggestion in case possible - within the Manage Hierarchy, the 'add a child list' and 'delete' options are next to each other.  I learnt the hard way today that if you're not concentrating, it's very easy to click on delete list option rather than add a child list!   It could be quite useful if these options could be moved apart to avoid mistakes. 

Thanks,
Heather

![image](https://cloud.githubusercontent.com/assets/12249067/13921683/0aafdde8-ef71-11e5-9e6b-b797c7f84ed4.png)

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for that, good point. I'll create an issue at this end to get that sorted.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1698

**Comment by SharonCocker** [comment]
Hi Andrew,

I just had another thought - for the delete option, would it also be 
possible to add a typical warning prompt, eg "are you sure want to 
delete...."  ?

Thanks,
Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for the suggestion, I'll log it in the issue.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Heather

A fix has now been created for this. The delete button is now more separated from the other buttons in the toolbar, this will hopefully reduce the likelihood of accidental clicks. I've also added a confirmation request which needs to be clicked before the delete will actually occur.

This update will shortly be pushed out to your server. I'll update this issue once it is live.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Heather

This is now live on preview. I'll close this issue, if you have any further problems, feel free to reopen.

Many thanks
Andrew
