### ISSUE TITLE
Word repeated in instructions

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#11]
![mistake in instruction](https://cloud.githubusercontent.com/assets/12249067/8233500/7b8fb6be-15ce-11e5-98ef-a63d15047c38.png)

**Comment by mrenvoize** [comment]
Assigning this to Andrew, ack Typo's!

**Comment by AndrewIsh** [comment]
Will update when it's fixed.

**Comment by AndrewIsh** [comment]
Hi

This is now fixed upstream and will appear in the next preview server refresh.

Thanks
Andrew
