### ISSUE TITLE
Recommended appearing above Core

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#110]
Hi

A number of staff have noticed that Recommended reading has started appearing above the Core reading in certain lists. Re-publishing the list seems to help, but we cannot do this for all of them. 

Can you have a look please? We haven't made any changes to Global Cateogry headings.

![recommended and core mixup](https://cloud.githubusercontent.com/assets/17139950/13988157/9a193faa-f102-11e5-83f2-edfeb6bcf7ae.png)

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for reporting this. I've looked in the database and the categories are ordered correctly, so I'm unclear what's happening. Once again, I'm going to tag @mrenvoize as the categories are being returned in the wrong order by the API. Hopefully Martin will be able to shed some light.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Richard

Martin has now fixed this. I'll close this issue, if you continue to see problems, feel free to re-open.

Many thanks
Andrew
