### ISSUE TITLE
Error: Properties not allowed

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#111]
Hi

On trying to edit this list in Chrome, the following error message appeared, it's one that we hadn't seen before. The time was 10:06 March 23rd.

![error messages](https://cloud.githubusercontent.com/assets/17139950/13988327/6078f988-f103-11e5-9a1c-87f0a26a589e.png)

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for that. I'm going to tag @mrenvoize as those errors looks like they're coming from the API and he might be able to shed some light on what's happening.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
This should be sorted now, my apologies.. in my haste to improve some areas of performance I missed an instance of parent_id vs parent alterations in the database.

You should find buffers accessible again now.

**Comment by AndrewIsh** [comment]
I'll close this issue. If you still experience problems, feel free to re-open.

Many thanks
Andrew
