### ISSUE TITLE
[Edit Mode] Manual entry web link oddity

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#113]
Hi,

Within edit, I tried to create a manual entry with an item type of web page and found it behaves oddly.   My intention was to create a link to Twitter, adding relevant text information together with a URL.   After clicking finish I noticed that the item type displayed as a book entry rather than as a web page entry.   So that I could distinguish this error, I added a note "This was supposed to be a website entry".   I then tried to create a second manual entry (web page) to Twitter to see what would happen.  This new entry appeared again as a book rather than a web page, though strangely my first entry changed/corrected itself to a web page.  I then published the list and only one of the web page entries appeared - please see screenshots, the first is of the unpublished list showing the two 'web pages' entries to Twitter, the second shows the published list displaying only one entry to Twitter. 

Thanks,
Heather 

![image](https://cloud.githubusercontent.com/assets/12249067/14532207/283caaae-0258-11e6-9229-b804474cb428.png)

![image](https://cloud.githubusercontent.com/assets/12249067/14532285/79db76ec-0258-11e6-9caa-49f112f87844.png)

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for this, apologies for the delay in getting back to you. This is a strange one indeed, I've not seen anything like this before. I'll create an issue at our end and invesigate.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Heather

I've just been looking into this, and am unable to replicate it. I just created a list and added some weblinks to it: https://preview2.rebuslist.com/#/list/214 and they have been added as the correct type.

I've been doing some work on improving manual item addition recently, so this may well have fixed the problem. Could you please try again and let me know if it's still an issue.

Many thanks
Andrew

**Comment by SharonCocker** [comment]
Hi Andrew,

I have just tried creating a link to Twitter and the process seemed far easier than before, plus it works okay.  The only oddity I had was a warning popping up right at the start of the process (please see screenshot), before I had add any data.  

Thanks,
Heather 

![image](https://cloud.githubusercontent.com/assets/12249067/16332101/14fefd4a-39ec-11e6-8985-7190e3414983.png)

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for the update. Glad to hear it worked OK.

The idea behind the warning is that it's to inform you that required data has not yet being filled in, but it is somewhat heavy handed. I'll create an issue at our end to address this.

I'll close this issue, since the original problem seems to have been resolved. Feel free to re-open it if you see the problem again.

Many thanks
Andrew
