### ISSUE TITLE
List not available - judgemental kitten

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#114]
Hi

Can you have a look at the following list, we are getting the judgemental kitten error when trying to access it:

https://uhi.rebuslist.com/#/list/2268

The module details are:  Molecular biology for algal biotechnology [UF711987] 

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

It seems the API is returning an error when retrieving this list, I'll investigate.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Looks like a data error has crept in. I've got to host a company meeting this morning, but hope to be able to take a look at this in circa an hour from now.

**Comment by richughes** [comment]
Hi 
We are getting the same error on this list as well:

https://uhi.rebuslist.com/#/list/2422 

Recent Advances in Physical Sciences [UC910774]

Many thanks

Richard

**Comment by richughes** [comment]
Hi 

The following lists are also getting the same error:

Environmental and Social Issues in Mountain Areas
Environmental Conservation
Blue Biotechnology for the 21st Century
The Economics of Mountain Regions

Many thanks

Richard

**Comment by richughes** [comment]
Hi

We are still having difficulties with unavailable lists, the latest one is:

Scottish Covenant Theology 
https://uhi.rebuslist.com/#/list/1423 

Thanks

**Comment by mrenvoize** [comment]
"UnknownType: [electronic resource]." was getting in as a type.. Another one ofr me to get mapped correctly in connect.

I've fixed the list though now.

**Comment by richughes** [comment]
Hi 

We have found another judgemental kitten. The list loads, but when we click edit we get the following error: 

![edit error judgemental kitten](https://cloud.githubusercontent.com/assets/17139950/14916889/091aa244-0e14-11e6-8e23-b52659307826.png)

The list is:
https://uhi.rebuslist.com/#/list/1579

Many thanks
Richard

**Comment by richughes** [comment]
Hi 

I've found another list with the judgemental kitten error. Can you have a look?

https://uhi.rebuslist.com/#/list/1318
UX107100
Blended learning, Introduction to

Thanks

Richard
