### ISSUE TITLE
Delete buttons not working properly

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#115]
Hello,

I have tried to delete some items from my list. I am able to delete around 3, and after that the delete buttons stop working and I am not able to delete any more. I have to then publish the list (getting a few error messages of unavailability of the server on the way), go back to it and delete a few more items.

Solution would be much appreciated.
Joanna

**Comment by AndrewIsh** [comment]
Hi Heather

Another weird one. I've not been able to replicate this. Are you still seeing it? If so, can you let me know which lists you've seen it on?

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hi Andrew,

Although I am not Heather, the issue is still there. Tried with JB Test week 2 list just now.

Best,
Joanna

**Comment by JoannaBek** [comment]
https://youtu.be/4aHlcKdaE7U

**Comment by AndrewIsh** [comment]
Thanks for the video, very helpful indeed. I'll create an issue and investigate.

Sorry for the confusion over names. It doesn't take much to confuse me, seemingly two people sharing one Github account is enough!

**Comment by AndrewIsh** [comment]
Hi Joanna

A fix was pushed out last week that should have addressed this. Can you try again and let me know if it's still a problem please?

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hello Andrew,

Unfortunately the problem still persist: https://youtu.be/JxAfSW0sgLk

**Comment by AndrewIsh** [comment]
OK, thanks for the update. I'll investigate.

**Comment by AndrewIsh** [comment]
Hi Joanna

Can you let me know which list you're seeing this on, I'm still unable to replicate it and, am hoping, if I try on the same list you're experiencing the problem on I might have more luck.

Thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Joanna

I'm going to close this issue for now as I've been unable to replicate the problem. Feel free to repoen it if you are continuing to see the issue.

Many thanks
Andrew
