### ISSUE TITLE
"Add list alternatives" problem

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#116]
Hi

I attempted to add an alternative item to the following reading list to see how it displayed. In Edit mode, it appeared to work, as I could see there was now one further item in the dropdown list. However, when I published the list and refreshed the page, the judgemental kitten error appeared and I can no longer access the list at all:

https://uhi.rebuslist.com/#/list/1300 
UV208486

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Apologies for that, this is now fixed.

Regards
Andrew
