### ISSUE TITLE
UHI Rebus - 503 Service unavailable

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#117]
Hi 

Rebus is currently down, we are getting the message:

"The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later".

Please can you have a look.

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Apologies for that, it should be available again now.

Regards
Andrew

**Comment by richughes** [comment]
Hi 

It seems to be down again. The error in Chrome is:

"This site can’t be reached

uhi.rebuslist.com took too long to respond" 

I was working on this list just beforehand: UV208492

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Apologies for that, the server is now back up.

Many thanks
Andrew
