### ISSUE TITLE
List not available - judgemental kitten

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#118]
Hi

The following list can be viewed, but on clicking "edit" the judgemental kitten appears. Can you have a look?

https://uhi.rebuslist.com/#/list/1579 

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

I've tried accessing this list as both an authenticated and unauthenticated user and haven't have any problems (see attached screenshot). Can you try logging out of rebus:list and back in again, then try again.

Many thanks
Andrew

![image](https://cloud.githubusercontent.com/assets/9194223/15078600/db262f46-13ab-11e6-8992-000dfda28eef.png)

**Comment by richughes** [comment]
HI Andrew

We can view the list fine, but it's when we click "edit" that the error appears. I tried it again this morning and it's still the same. 

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Apologies, I misread your initial comment! This list should now be fixed, there was a bad bit of data in one of the items. We're not clear at this point how it got there, so if you see the problem again, please don't hesitate to let us know. I'll close this issue for now.

Many thanks
Andrew

**Comment by richughes** [comment]
Hi Andrew

We’re getting another list with judgemental kitten error. It’s happening in public view before we click edit:

https://uhi.rebuslist.com/#/list/2249

Can you have a look?

Thanks

Richard
