### ISSUE TITLE
Search for material crashing

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#119]
Hi 

In the Search for material menu, after carrying out a search, when I try to edit an item manually it crashes the broswer and the screen turns white. 

![search for material crashing](https://cloud.githubusercontent.com/assets/17139950/15076823/74c080d8-13a3-11e6-965d-245e30b1bdc9.png)

When I use task manager to close it, I get the message: "Plugin container for firefox has stopped working". The same screen freezes when I use Chrome as well. 

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for this. It's an issue we're aware of and I'm currently working on a fix. As soon as we have a fix pushed to your server, I'll update this issue to let you know.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1713

**Comment by AndrewIsh** [comment]
Hi Richard

This problem was fixed a few weeks ago, so I'll close this issue. Feel free to re-open if you still see it.

Many thanks
Andrew
