### ISSUE TITLE
Problem with publishing additions to list

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#12]
![problems with adding items](https://cloud.githubusercontent.com/assets/12249067/8233588/ff30f5dc-15ce-11e5-93d6-901f2b765032.png)

**Comment by mrenvoize** [comment]
I believe 'save draft' is performing as expected. If you re-enter the edit screen, you should find your 'draft' in tact with the additional items visible and editable.

However, the 'publish' does appear to have a bug at the moment, I will investigate this further.

Cheers

**Comment by AndrewIsh** [comment]
This was fixed some time ago, closing.
