### ISSUE TITLE
Server unavailable when publishing lists

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#121]
Hi 

Yesterday afternoon, it appeared that the connection to the server was disappearing for a short period oif time. When addding items and clicking publish I was getting the following message:

![server not available2](https://cloud.githubusercontent.com/assets/17139950/15243261/6509b0fc-18f2-11e6-9b54-ca878cdedd2e.png)

The most recent items added to the list disappeared. Also, when publishing the lists, I was having to refresh the browser a few times before the new items became visible on the public display. It seemed a longer delay than in the last few weeks. I was using Firefox. 

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Many thanks for that. We had a brief problem with the server yesterday afternoon, it should only have been unavailable for a couple of minutes. Items added while the server was unavailable _should_ have been preserved and added once it became available again, but it sounds like that may not have been the case here? I'll investigate.

As far as having to refresh before items become visible on the list, that's very interesting, they should be instantly visible. I'll create an issue and investigate.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1780

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1781

**Comment by richughes** [comment]
Thanks Andrew.

I only had to re-add a couple of items so it wasn’t a huge issue, but thought it was worth mentioning. The list is fine today.

If you can resolve the refresh issue that would be good. I now know to press F5 a couple of times, but for those that don’t they might think the items haven’t been added. It seems to happen more often in Firefox than Chrome.

Many thanks

Richard

**Comment by mrenvoize** [comment]
@richughes I believe I have now fixed this issue, but would appreciate a verification from yourselves as I was struggling to replicate it consistently in the first place.

Many thanks,

Martin

**Comment by richughes** [comment]
Hi 

I hadn't noticed this issue for a few weeks, but it started again the other day. Items are added to lists but then disappear after being published as the server could not be found. Items have to then be re-added, which is frustrating, especially when a few list alternatives disappear. I was training someone so wasn't able to get screenshots and report it at the time. 

Thanks

**Comment by AndrewIsh** [comment]
Hi Richard

This issue should now be fixed following an update I pushed out earlier in the week. I'll close this issue, but feel free to re-open if you find the problem remains.

Many thanks
ANdrew
