### ISSUE TITLE
Issues with list visibility

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#122]
Hello

We've been having some issues with creating lists/editing list details/publishing lists - yesterday I created a parent with 4 child lists, D59I Inter-Cultural Psychoanalytic Psychotherapy (2016-2018), but had problems publishing them, some would take and others steadfastly remained unpublished - today when I looked two of the child lists had disappeared completely! 

As I couldn't give you step-by-step details of exactly what I'd done yesterday I started again from scratch today, and had similar problems - sorry I couldn't do this as a video as I've got a new work pc with virtually nothing on it! 

At the moment I'm using IE 11.0.9600.1832, and haven't been able to try any of this out on any other browsers yet
1. New top-level list created – M33 Psychodynamic Approaches to Working with Adolescents - all I did here was enter a list name, then go back in to edit it from 2015-17 to 2015-2017, no other fields were changed
   ![new_parent_list](https://cloud.githubusercontent.com/assets/12201255/15567948/3a95ef28-2321-11e6-85bc-6ff711a84741.png)
2. I published this list then created 3 child lists for it, in these the only entries were for the list name and list summary, no other fields were changed.
   ![child_lists_unpublished](https://cloud.githubusercontent.com/assets/12201255/15568145/2a333c52-2322-11e6-96e2-bcf8e23d0608.png)
3. child lists published:
   ![child_lists_published](https://cloud.githubusercontent.com/assets/12201255/15568157/31c0ac7a-2322-11e6-9ecf-fcb5ddd15de5.png)
4. I moved across to the public site in a new browser window (though I was still logged in to the admin site in the same browser)  – none of the lists were visible under Browse
   ![compare_manage_hierarchy_and_browse](https://cloud.githubusercontent.com/assets/12201255/15568160/3b4b2d24-2322-11e6-8ff4-2d72be9cf326.png)
5. Searching for the list found it:
   ![search_for_list](https://cloud.githubusercontent.com/assets/12201255/15568166/4afd3e9c-2322-11e6-8a05-4fd85ca30fd3.png)
6. But only the parent level list, none of the child lists showed up in the breadcrumb
   ![no_child-lists](https://cloud.githubusercontent.com/assets/12201255/15568174/522a8daa-2322-11e6-90d7-dcee4585de00.png)

Hopefully this will all make sense, we've had similar problems in the past but there's been a lot of too-ing and fro-ing so it's been hard to ascertain when lists appear and when they don't, or if we're just missing a vital step!  If you think it would be helpful to have more details about yesterday's lists, especially the disappearing ones, let me know.

best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Changes made in one browser window will not be reflected in a second browser window unless the second window is refreshed. Can you try the same process again, but refresh the second browser window before step 4?

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew - I'd opened a new browser window after publishing the lists, would the window still need to be refreshed to show any changes if it’s a new window?

I've tried this anyway though, but am now seeing a different problem - every time I hit refresh on the Browse page the login box appears even though I am logged in.

I tried logging in again, and closing the login box, but the new course didnn’t appearing there or under Manage Hierarchy anymore!

I have a couple of screenshots but can't upload them on github so have attached them here.

I wondered if clearing my browser cache might sort things out so I did that – which worked to some extent, now I can see the M33 and child lists under browse, but am stuck in a login loop and can’t get into the admin side at all!

Helen

Helen Oliver

Systems Librarian
Tavistock Library
Tavistock & Portman NHS Foundation Trust Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.ukmailto:holiver@tavi-port.ac.uk

https://library.tavistockandportman.ac.uk

[cid:image003.png@01D1B744.131CF8E0]

**Comment by AndrewIsh** [comment]
Hi Helen

The screenshots don't appear to have come through, can you try again please :)

Many thanks
Andrew

**Comment by hloliver** [comment]
OK, looks like I can upload them in github again now so have updated the post below

Hi Andrew - I'd opened a new browser window after publishing the lists, would the window still need to be refreshed to show any changes if it’s a new window?

I've tried this anyway though, but am now seeing a different problem - every time I hit refresh on the Browse page the login box appears even though I am logged in.

![refresh_page](https://cloud.githubusercontent.com/assets/12201255/15573152/d4b3c9b6-233c-11e6-8a4c-b71430a2696a.png)

I tried logging in again, and closing the login box, but the new course didn’t appear in the Browse window or under Manage Hierarchy anymore!

![m33_lists_missing](https://cloud.githubusercontent.com/assets/12201255/15573157/dd26195a-233c-11e6-9fd9-90c7719affed.png)

I wondered if clearing my browser cache might sort things out so I did that – which worked to some extent, now I can see the M33 and child lists under browse, but am stuck in a login loop and can’t get into the admin side at all! It's hard to see from the screenshot below but when I try to get in to admin all I see is the login link, so I login (apparently) successfully but only see the login link not the admin toolbar

![login_loop](https://cloud.githubusercontent.com/assets/12201255/15573162/e5801858-233c-11e6-9957-67acb96c9bff.png)

best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Apologies for the delay in getting back to on this. We've pushed out some fixes in the last week or so which should help fix these problems. Could you please try the workflow described above again and let me know how you get on?

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew - we did notice that the lists seemed to be behaving themselves last week, hoping to spend more time on the systems this week so will let you know if there are any problems
Thanks
Helen

**Comment by hloliver** [comment]
Hi Andrew - just to confirm that we haven't had any further problems with this
best wishes
Helen

**Comment by AndrewIsh** [comment]
Good to hear. I'll close this issue. Feel free to re-open if you have further problems with this.
