### ISSUE TITLE
From YSJ: migrated lists not in same order

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/rebus-list-2#123]
From Vic: "The first thing I’ve noticed is that nothing seems to be in alphabetical order – at top level, or the next level down.  Is it possible to re-order?"

It looks like they ordered them all alphabetically on RL1. Will they just have to repeat the exercise on RL2 post-migration?

**Comment by mrenvoize** [comment]
Is this against the migrated data.. If so,  the migration script is meant to import the items in the same order as they were on rl1. 

I've not checked ysj yet, but this has worked everywhere else so far.

**Comment by janetc** [comment]
It does seem to be on migrated data - on RL1 the order for the top level is:
Arts - Business School - Education and Theology - Health and Life Sciences - Information Learning Services
On RL2 I'm seeing:
Education and Theology - Arts - Information Learning Services - Business School - Health and Life Sciences.

Having said that - YSJ will be reordering their hierarchy on RL1 before the final migration so probably makes better sense to park this for now.

**Comment by mrenvoize** [comment]
They wanted alpha ordering.. done
