### ISSUE TITLE
Problems adding weblinks

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#124]
Hi 

A member of staff is having constant difficulty adding weblinks manually to the following list:

Quality, regulation and intellectual property in an industrial context [UC911004].

The error she receives is: 

![add website error](https://cloud.githubusercontent.com/assets/17139950/15775498/144e495a-297a-11e6-811e-9cac7a86b4fb.png)

It happened at 10:04 today, although she was getting similar errors yetserday. 

Can you have a look?

Thanks

**Comment by fionaborthwick1** [comment]
Thanks for reporting this Richard. I have just attempted to add a web page
material type to this list and have been given the same error as you.  We
will need to investigate.

Fiona

On 3 June 2016 at 11:00, richughes notifications@github.com wrote:

> Hi
> 
> A member of staff is having constant difficulty adding weblinks manually
> to the following list:
> 
> Quality, regulation and intellectual property in an industrial context
> [UC911004].
> 
> The error she receives is:
> 
> [image: add website error]
> https://cloud.githubusercontent.com/assets/17139950/15775498/144e495a-297a-11e6-811e-9cac7a86b4fb.png
> 
> It happened at 10:04 today, although she was getting similar errors
> yetserday.
> 
> Can you have a look?
> 
> Thanks
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/PTFS-Europe/rebus-list-2/issues/124, or mute the
> thread
> https://github.com/notifications/unsubscribe/ABHRoY40TMP1Hr2Lf1lVYnRniGyxe3zCks5qH_tJgaJpZM4ItYar
> .

## 

_Fiona Borthwick_

Customer Services Consultant

_T:_ +44 (0) 1483 378728

_Mobile:_ +44 (0) 7540 768230

_Skype:_ 0131 2088578

_F:_ +44 (0) 800 756 6384

_E:_ fiona.borthwick@ptfs-europe.com

www.ptfs-europe.com

 https://www.ptfs-europe.com/

Registered in the United Kingdom No. 06416372   VAT Reg No. 925 7211 30

The information contained in this email message may be privileged,
confidential and protected from disclosure. If you are not the
intended recipient, any dissemination, distribution or copying is
strictly prohibited. If you think that you have received this email
message in error, please email the sender at info@ptfs-europe.com

**Comment by richughes** [comment]
Hi 

The problem doesn't seem to be confined to weblinks. I tried addding a manual book entry twice this morning and both times it disappeared. It was an add list alternative entry. 

![manual link entry error](https://cloud.githubusercontent.com/assets/17139950/15887827/3e5f6b80-2d5c-11e6-872f-2952f3596a9a.png)

The list was:
Air traffic management project [UH410846]
Firefox 46.0.1

We have umpteen lists still to add to the system and if errors like this keep occuring it means we'll have to revisit every single one once the manual entry problem is resolved. Are there any timescales on a fix for this?

Thanks

Richard

**Comment by richughes** [comment]
Hi 

Is there any update on when the ability to add items manually will be available?

Thanks

**Comment by AndrewIsh** [comment]
Hi Richard

Apologies for the delay in getting to this. I am hoping to take a look at it later this week. I'll update this issue as soon as it has been resolved. Thanks for your patience.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Richard

I have just pushed out a fix for this. I'll close this issue now, feel free to re-open if you are still seeing the problem.

Many thanks
Andrew

**Comment by richughes** [comment]
Hi Andrew

Thank you, I’ve added a link and it is now working again. However, the website title doesn’t automatically become a hyperlink as before. It’s adding the URL underneath the webpage title instead, eg:

[cid:image003.png@01D1C7E5.024835A0]

Can you alter this, or is it to do with the webpage template? I’ve not made any changes to it.

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Yes, this can be performed via the editable templates. See this page for more details: http://ptfs-europe.github.io/rebus-list/templates/

Many thanks
Andrew
