### ISSUE TITLE
Publishing lists - refreshing the browser

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#125]
Hi 

We've been getting various reports of staff publishing lists and new entries not being visible on the public view. Although hitting F5 one or two times usually refreshes the list with the new entries, is this going to be necessary in the long-run? Some library staff are re-adding items and then getting a message saying that the list already contains the item, which is frustrating and slows the rate at which they can add material. 

Thanks

Richard

**Comment by fionaborthwick1** [comment]
Hi Richard,

Just to let you know that this is an issue we are aware of and Martin and
Andrew are working on a fix.

Kind Regards,
Fiona

On 3 June 2016 at 11:09, richughes notifications@github.com wrote:

> Hi
> 
> We've been getting various reports of staff publishing lists and new
> entries not being visible on the public view. Although hitting F5 one or
> two times usually refreshes the list with the new entries, is this going to
> be necessary in the long-run? Some library staff are re-adding items and
> then getting a message saying that the list already contains the item,
> which is frustrating and slows the rate at which they can add material.
> 
> Thanks
> 
> Richard
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/PTFS-Europe/rebus-list-2/issues/125, or mute the
> thread
> https://github.com/notifications/unsubscribe/ABHRoaNWys7VPwPL7IrRm1Zmy3c-flXPks5qH_1lgaJpZM4ItY3D
> .

## 

_Fiona Borthwick_

Customer Services Consultant

_T:_ +44 (0) 1483 378728

_Mobile:_ +44 (0) 7540 768230

_Skype:_ 0131 2088578

_F:_ +44 (0) 800 756 6384

_E:_ fiona.borthwick@ptfs-europe.com

www.ptfs-europe.com

 https://www.ptfs-europe.com/

Registered in the United Kingdom No. 06416372   VAT Reg No. 925 7211 30

The information contained in this email message may be privileged,
confidential and protected from disclosure. If you are not the
intended recipient, any dissemination, distribution or copying is
strictly prohibited. If you think that you have received this email
message in error, please email the sender at info@ptfs-europe.com

**Comment by AndrewIsh** [comment]
Hi Richard

We have just pushed out an update which should address this issue. Could you please see if you're still seeing the problem.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
I'm closing this issue as I'm assuming it's now working. Feel free to re-open if it is still a problem.
