### ISSUE TITLE
Multiple judgemental kitten errors

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#126]
Hi 

Library staff are in the process of checking each list on our system and have found many returning the judgemental kitten error. I suspect there are others that haven't been reported yet. Can you have a look to see what the problem is? Do we have to report all individually or can you check all lists for the error?

UJ908005    Live audio production
UJ909003            Live event audio
UW410762     (Inter) National theatre
UW311014    Enterprise and community: Making music matter
UI610002            Emerging technologies in human computer interaction
UI610003           Entrepreneurship and portfolio development
UI610005             Research and product development
UW308467     Music theory and analysis
UW408003     Performance studies, Introduction to
UW311003     Popular music: Gender and sexuality (1920 to present)
UW307233    Creativity is more important than knowledge
UW308475    Creative skills
UH410843        Avionics and aircraft computer systems 2
UH408393       Aircraft systems: electrical / avionic
UH409785       Avionics and aircraft computer systems 1
UX107100       Blended learning, Introduction to

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Many thanks for those. I'll tag @mrenvoize in this issue as I believe he has been working with you on previous occurrences of this problem.

Many thanks
Andrew

**Comment by richughes** [comment]
Another one when I press edit on the following list:

Safety and security of air traffic operations [UH409791]

![judgemental kitten when editing](https://cloud.githubusercontent.com/assets/17139950/15889246/488a81f2-2d62-11e6-9f6a-f5f0581c3b28.png)

**Comment by richughes** [comment]
Another one:

Conceptual and historical issues in psychology [UC810801]

**Comment by richughes** [comment]
Hi Martin

I've re-checked a number of these since our chat earlier and they are still showing as the judgemental kitten error. Can you have a look?

Thanks

Richard

**Comment by richughes** [comment]
Hi 

Another list that needs attention:

Civil engineering technology 2 [UH208425] 

 In public view there is a red exclamatation mark next to the module title which says: "list has an active draft!" When I try to enter edit mode I get the judgemental kitten error. 

Also, the list at the top of this ticket have been unavailable for 5 weeks. Can you have a look as soon as possible, as they all require work.

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Many thanks for the additional information. I'll pass this to @mrenvoize to sort these lists out.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Hi @richughes ,

It's appears somehow some unknown material types were making their way into the system still.. I've cleaned them up so your lists should be working now.

Please let me know if you come across any more so I can followup with further validation checking
