### ISSUE TITLE
Multiple notifications after one action

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#13]
![rebus](https://cloud.githubusercontent.com/assets/12249067/8233616/2916368c-15cf-11e5-8d67-3f951400f2c9.png)

**Comment by mrenvoize** [comment]
I have a feeling this may have been fixed upstream, but is awaiting an authentication fix to be added before we push it forward onto the preview system.

I will post back here once pushed so we can varify.

Cheers

Martin Renvoize

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/362
It has been a fairly longstanding bug and I've got some debug code running to try and determine the cause. It's fairly high on my list of bugs to fix, I'll update here once it's fixed.

**Comment by mrenvoize** [comment]
This one has now been squashed, well done @AndrewIsh
