### ISSUE TITLE
Unable to add/edit list items

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#131]
Hello
I tried to add items to the following list, but when I went in to edit mode there were no items listed at all, and the only section that I could edit was the list details area

https://tavi.rebuslist.co.uk/#/list/1105

http://screencast.com/t/iHyHVKmHn 

I've noticed this a couple of times but haven't spotted any pattern, will update with some more examples as I come across them if it helps
bw
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

There appears to be a problem with the data for this list, specifically it appears to contain duplicate items. I'll pass this one over to @mrenvoize, as he should be able to remove the duplicate items.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hello Andrew -  a lot (probably the majority) of our lists include duplicate items!  

All of the examples below occur frequently in our reading lists:
- Different chapters may be recommended for the same seminar 
- Different chapters for different seminars
- The same chapter for different seminars
- Core text listed for a seminar series, with a different chapter highlighted as the main reading for each week
- The whole book may be listed as background reading, with individual chapters set for different seminars

I'd already raised this as a general issue with Janet/Martin when I was looking at our migrated lists but hadn't realised that it was by design

Hoping that there will be a way around this

best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

As noted in #132, we will be shortly be pushing out an update that will allow the same item (in different forms) to be added to the same list multiple times. This will satisfy all the criteria you specify above. I'll update this issue once the fix is on your server.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

The ability to add the same material (in different forms) to the same list multiple times is now live on your site. This can be achieved by choosing the "Add item as..." option next to the search results. I'll close this issue, but feel free to open a new issue if you have any problems with this new functionality.

Many thanks
Andrew

**Comment by hloliver** [comment]
That’s great – thanks Andrew
