### ISSUE TITLE
Adding a book chapter

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#132]
Hello

I wanted to check up on the workflow for adding a book chapter to a list

In RL1 you select the material type, ie chapter, then search for the book – after selecting the correct title you can manually enter the chapter details ie chapter title, chapter author and pagination.

In RL2 after selecting the material type you are directed to the template and all the details have to be entered manually.  
Or, you search for the book, but once the record has been pulled in to the list there is no way to edit it in order to add the chapter details.

At the moment our RL1 and RL2 are both only searching Koha, but even when the connectors are set up for our Discovery service the majority of chapters that we add to lists won’t be found on there 

Is there a workaround for this, or are you planning to include a search option similar to RL1? The prospect of adding every chapter manually is daunting to say the least!

Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for the information. We are currently working on a method to allow the addition of book chapters from search results. This should be available very shortly. I'll update this issue when it is live.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

The ability to add book chapters from search results is now live on your site. This can be achieved by doing a search as usual, then choosing the "Add item as..." option next to the search results. I'll close this issue, but feel free to open a new issue if you have any problems with this new functionality.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew
We seem to have lost this function - all we see are select/deselect options

![screenshot 2016-10-14 13 59 45](https://cloud.githubusercontent.com/assets/12201255/19388277/a7b2c4e6-9216-11e6-8543-bce2fbb2f6b3.png)

can this be reinstated, or has it been moved somewhere else?

Thanks
Helen
