### ISSUE TITLE
Not able to work on preview

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#133]
Hello,

I wanted to check the issue with deleting the items from the reading list, but I am not able to work on the preview at all:
- No text that I am trying to input is visible (I have written "teaching" where the highlight is)
  ![image](https://cloud.githubusercontent.com/assets/16195154/16452226/4bbb6442-3dff-11e6-853d-63a5a2abd384.png)
- I can't publish the list, as the system comes back with an error:
  ![image](https://cloud.githubusercontent.com/assets/16195154/16452288/8ff2f238-3dff-11e6-8e75-ed7881421d2c.png)
- I can't get to either JB Test list 2 and JB Test list 1, as the system returns judgmental kitten.

Thanks,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Apologies for the delay in getting back to you. Are you still experiencing this problem. 

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hello,

The text came back, but I still can't publish the list (same error as above).

Joanna

**Comment by JoannaBek** [comment]
Video:
https://youtu.be/GO2qFHWVWbk

**Comment by AndrewIsh** [comment]
Hi Joanna

Many thanks for this, apologies for the delay in getting back to you. I've just logged into preview2 and edited the list "JB Test list 3", I deleted a few items and added one to the "Essential" category, this all appeared to work fine.

It may be that the server was unavailable at the time you were working, that would account for the errors you received. When you get a moment, could you please try again and let me know if you still see the problem?

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Closing, 1 month no contact, presuming fixed.
