### ISSUE TITLE
Misleading Login Fields

### ISSUE THREAD

**Issue by paulwilliamsBCU** [PTFS-Europe/rebus-list-2#134]
Is it possible to remove the example email address from the username box on the login screen? Not sure if this is true elsewhere, but our academics aren't using an email address to authenticate (they use a staff ID) but the sample email address is already confusing test users. Despite telling them otherwise, they automatically try to use their email address because of this misleading pointer. Screenshot attached.
[Login email.docx](https://github.com/PTFS-Europe/rebus-list-2/files/341610/Login.email.docx)

**Comment by mrenvoize** [comment]
One for Andrew,  I can certainly see how this could become misleading. 

We actually match on username and not email at all so this likely an hangover from early development, thanks for the feedback.

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#1879

**Comment by AndrewIsh** [comment]
This has now been removed, the update will be pushed out to all customers shortly.
