### ISSUE TITLE
Manually entering a book - publication date not retained

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#136]
I've entered a couple of books manually - both times included the publication year when I created the record, but this wasn't retained.  

When I went in to edit the record and add in the date again I wasn't able to save the record.  

When adding/editing the record this alert appeared  'string doesn't match pattern...' as soon as I started typing in the date, but disappeared as soon as I entered the 4th digit.

This shows what happened when I tried editing the record to include the date:
http://screencast.com/t/cNZD5TO8CK3q

Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for the report. I'll create an issue at our end and investigate.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1885

**Comment by hloliver** [comment]
Hi Andrew
I noticed earlier this morning that I can't make any changes at all.

First of all I was experiencing the same problem when I tried to edit books that had been entered manuallly ie I could make the change but the record wouldn't save

Now the item can't be edited at all, the following error displays and I can't click in to any of the fields

"There is a problem with your form data, please check it and try again
This message will disappear when your form data is valid"

![edit_material_error](https://cloud.githubusercontent.com/assets/12201255/16576358/920c3800-4286-11e6-9111-e1097f32d714.png)

Incidentally the problem with the data seems to be that the Edition field is empty, but I can't enter anything in there to clear it.  

Hope this helps with your investigation!
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for the report, very useful indeed. I've created a new issue for this as it appears to be unrelated to the publication year issue: https://github.com/PTFS-Europe/rebus-list-2/issues/140 I'll make comments on that issue.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Incidentally, the problem with year not being retained should now be fixed. I'll close this issue. Feel free to re-open if it is still a problem.
