### ISSUE TITLE
'Retain vols' note in citation

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#137]
Hi
I manually entered a book (only fields populated were title, author, place, publisher, date, isbn and url (this is set as a mandatory field - can it be switched off?), when I looked at the citation it displayed ''Retain vols' after the title field. 

When I went to edit the record 'retain' had appeared in the Vols field, I tried deleting this but wasn't able to save the record.

![retain vols note in citation](https://cloud.githubusercontent.com/assets/12201255/16540278/994a3c3e-4056-11e6-8e36-8ee4f2134950.png)

https://tavi.rebuslist.co.uk/#/list/1613 
Could you take a look?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this. That's a very interesting problem, I'll create an issue at our end and investigate.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

I have completed a fix for this problem. I'll update this issue once it is available on your server.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

The fix for this has now been pushed out to your server. I'll close this issue. Feel free to reopen if you still have problems.

Many thanks
Andrew
