### ISSUE TITLE
Edition as Required field

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#139]
Hello
Edition seems to be set as a required field for books/book chapters - it doesn't show up when you are adding a new book manually, but if you go in to edit the record the following error message appears:

There is a problem with your form data, please check it and try again
This message will disappear when your form data is valid

![edition_required_field](https://cloud.githubusercontent.com/assets/12201255/16576586/053a1a94-4288-11e6-8e42-ba5fb6f1e52b.png)

Not sure what other sites do but we only include an edition statement if it's a revised/later edition so would prefer this not to be a required field 

best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for the feedback. As you suggest, required fields are going to vary from site to site and, currently, it is not possible to specify them on a per-site basis. We'll certainly look at making them user definable. In the meantime, I'll change 'edition' to not being required. I'll update here once this has been done.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1894

**Comment by AndrewIsh** [comment]
Hi Helen

Edition is now no longer required. I'll close this issue. Feel free to reopen if you still have problems.

Many thanks
Andrew

**Comment by hloliver** [comment]
Great, thanks Andrew
