### ISSUE TITLE
My List: no lists result display

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#14]
If the search result is 'no lists' the display doesn't provide a way to reset the search or filter.  

![my lists filter no lists - search](https://cloud.githubusercontent.com/assets/10532724/8252681/ecbee998-167f-11e5-9846-23095991ca13.JPG)

Refreshing the page does recover the full My Lists page.

**Comment by AndrewIsh** [comment]
Confirmed, logged as issue https://github.com/PTFS-Europe/rebus-list/issues/781

**Comment by AndrewIsh** [comment]
This has been fixed upstream and will be available on the preview server when we next push master to it
