### ISSUE TITLE
Unable to edit manually created material

### ISSUE THREAD

**Issue by AndrewIsh** [PTFS-Europe/rebus-list-2#140]
Reported by @hloliver: https://github.com/PTFS-Europe/rebus-list-2/issues/136#issuecomment-230401760

Hi Andrew
I noticed earlier this morning that I can't make any changes at all.

First of all I was experiencing the same problem when I tried to edit books that had been entered manuallly ie I could make the change but the record wouldn't save

Now the item can't be edited at all, the following error displays and I can't click in to any of the fields

"There is a problem with your form data, please check it and try again
This message will disappear when your form data is valid"

![image](https://cloud.githubusercontent.com/assets/9194223/16578205/2c30c946-4291-11e6-8339-9fff3ac33f35.png)

Incidentally the problem with the data seems to be that the Edition field is empty, but I can't enter anything in there to clear it.

Hope this helps with your investigation!
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for the details, very useful. Can you let me know what user you are logged in as when attempting to edit this material?

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew – I was logged in as holiver

**Comment by AndrewIsh** [comment]
Hi Helen

I'm still unable to replicate this. So, you're logged in a holiver, which is an admin user, and you're trying to edit "Blue Heaven", which was created by that user. You should be able to edit that material. Would you mind very much if I changed your password, so I can log in as you, and see what's happening. I'll let you know the password after, so you can change it back.

Many thanks
Andrew

**Comment by hloliver** [comment]
Please do!

**Comment by AndrewIsh** [comment]
Hi Helen

The plot thickens. I just logged in as you and I am able to edit the material! I'll email you your new password. Can you try completely refreshing your browser, then try again?

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew
Really odd - I've just completely cleared two browsers but still can't edit the record, I tried deleting the url field, adding a publication year and entering text in the description field and although I was able to do all of these nothing happened when I clicked on Finish so I had to cancel the changes.

I've tried this in Firefox v 47.0 and Chrome Version 51.0.2704.103 (64-bit)

I've left the password as is in case you want to try anything else - I'm at a conference for the next two days, but may get a chance to try again in the evenings.

Thanks for all of the other issues that you've cleared up today!

best wishes
Helen

**Comment by AndrewIsh** [comment]
Aha! I've been misunderstanding you all along! I thought you were not able to change values in the fields. Not being able to save is something we are aware of and are working on a fix for. Apologies for messing you around today! I'll let you know as soon as the fix is ready.

Many thanks
Andrew

**Comment by hloliver** [comment]
Not at all - I should have been clearer when reporting it, but by end of this process I will be much better at explaining issues!

best wishes
Helen

Helen Oliver

Systems Librarian
Tavistock & Portman NHS Foundation Trust
Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.uk

**Comment by AndrewIsh** [comment]
Hi Helen

This is now fixed. I'll close this issue, feel free to reopen if it is still a problem for you.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hello Andrew

Can we reopen this one?

I've just been testing this out again and seeing some odd behaviour! 

When I edit a record I can now save the changes, but going back in it looks as if the changes haven't taken. After clearing the search results and searching for the same item again the changes I made were there. 

The item I was testing was Blue Heaven, here's a screencast:

http://screencast.com/t/JcMiB0o8VG5

However now if I try to edit the same record I can't make any changes, I can't even click into any of the fields

Clearing my browser worked temporarily, but the problem reoccured straight away, ie I was able to edit the record, the changes didn't display, this time I clicked on Edit, then Finish on the title below Blue Heaven, and when I went back to Blue Heaven I couldn't edit it again

Could you take a look? I've left my password as the one that you set yesterday in case you wanted to try my account.

best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for this.

Re: the first part of your reply:

> When I edit a record I can now save the changes, but going back in it looks as if the changes haven't taken. After clearing the search results and searching for the same item again the changes I made were there.

This was a bug. I've just fixed it, it should be pushed out to your server shortly.

I'll take a look at your being unable to edit the material now.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

I've been looking at your problem with editing the material. I've not been able to replicate it, these are the steps I followed. Please let me know if I did something wrong:
- Logged in as holiver
- Searched for material "Blue heaven"
- Edited material, added a few words to the Abstract field
- Saved
- Edited material "Blue heaven" again
- At this point I was able to edit the material with no problem.

If you are still seeing the problem and have a moment, could you please record a quick screencast demonstrating what you're seeing, just so I can see if I'm doing something subtly different?

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Closed with Nov 14th 2016 Release
