### ISSUE TITLE
UniofSunderland - Organisation of Browse Hierarchy

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#141]
Module codes are not showing next to module titles in the new version, also the list does not appear in any obvious order - for students wanting to browse the list should be either in A-Z order of module codes or title - some departments have up to 250 modules in a seemingly random order.
![new mmr browse list - no codes](https://cloud.githubusercontent.com/assets/20297411/16580303/a2bad8d6-429b-11e6-84a5-a132e99d2b11.JPG)
![old mmr browse list - codes included](https://cloud.githubusercontent.com/assets/20297411/16580309/ab5a9454-429b-11e6-8209-9395a91f3572.JPG)

**Comment by AndrewIsh** [comment]
Hi

The display of module codes was switched off in your Global Preferences, I've now switched that on.

The order of lists in the hierarchy view is completely customisable, you can re-order lists to whatever order you choose, this order will be reflected in both the hierarchy view and browse view.

I will close this issue, feel free to reopen if it does not answer your question.

Many thanks
Andrew

**Comment by UniofSunderland** [comment]
After further testing today and examination of our global preferences we still cannot get the list to re-order automatically at list level - it's fine at Faculty level as these are relatively stable but with lists being added all the time it's not possible to manually re-order constantly.

Can the lists be ordered by A-Z module code or A-Z title automatically? With new items dropped into the list at the right place/list automatically re-ordered?

**Comment by AndrewIsh** [comment]
Hi

Automatic sorting of lists within the hierarchy has been raised by other customers. We have an open issue for it, so I'll reference this one there and leave this issue closed.

Many thanks
Andrew
