### ISSUE TITLE
UniofSunderland - Browse Breadcrumb trail not displaying results

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#142]
When using the breadcrumb trail to move around the browse hierarchy moving back up the list produces no results ie go to Faculty of Education and Society, Department of Culture, 'Talking pages' list. View list then click on Dept of Culture to return to hierarchy - title of dept is there but now no module resources are shown.  You have to go right back to the beginning to get any results - seems to work down the hierarchy but not back up again.
![viewing lac278 in browse hierarchy](https://cloud.githubusercontent.com/assets/20297411/16580507/c195a546-429c-11e6-89a0-ee20543cc96e.JPG)
![after viewing lac278 returning to dept of culture list using breadcrumb trail - no results](https://cloud.githubusercontent.com/assets/20297411/16580508/c4ea951c-429c-11e6-9f9d-26660226c098.JPG)

**Comment by AndrewIsh** [comment]
Hi

Many thanks for the feedback.

When moving back up the hierarchy via the breadcrumb trail, all sub-lists should be displayed in a drop down box next to the current list. Indeed, in your second screenshot, the "Select a sub-list" box is next to the "Department of Culture" in the breadcrumb trail. A list of all sub-lists can be seen here. 

The area of lists vs hierarchy elements is something we're currently reviewing, any feedback you have would be welcome.

I'll close this issue as I believe it answers your question. Feel free to reopen it if you have further questions in this area.

Many thanks
Andrew
