### ISSUE TITLE
UniofSunderland - Search results unstable

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#143]
On three occasions of testing search results have varied in the way they are shown and what is displayed - on 28/06/16 all three instances of the same list were shown without any features to identify the year which means current year cannot be selected.

On 05/07/16 searching by module code did not work - test list used was Talking Pages LAC278

![searching using module code](https://cloud.githubusercontent.com/assets/20297411/16580710/c605a1e8-429d-11e6-8748-61c282bf31f2.JPG)

Title search works and today is showing only one variation of the list - however again we don't know which instance this is - should we assume the latest?  Ideally the display needs to read Module Code, Module Title, Year.
![searching using title](https://cloud.githubusercontent.com/assets/20297411/16580754/f70e5870-429d-11e6-8962-1c258d5661f1.JPG)

**Comment by AndrewIsh** [comment]
Hi

As far as the course code is concerned, this was switched off in your Global Preferences, I have now switched it on.

I performed the same search as you, as an authenticated user, just now and these were the results I got:

![image](https://cloud.githubusercontent.com/assets/9194223/16581844/856018ac-42a3-11e6-9cdf-ab461b2b10a7.png)

I see the same results as your 3rd screenshot when I am unauthenticated.

Could you please elaborate on the problem? Currently I am seeing what appears to be correct behaviour.

Many thanks
Andrew

**Comment by UniofSunderland** [comment]
Thanks Andrew.  I've tried the module code search both authenticated and non-authenticated and taken screen shots from each.  Thanks for switiching on the module code display - however as you'll see this display is also unstable - the test list I am using is LAC278 Talking Pages however this shows up differently in displays depending on how you search and is also sometimes assigned the wrong module code.

![issue 143 - problems with module code searching - nonauthenticated session](https://cloud.githubusercontent.com/assets/20297411/16584950/59e5ccfe-42b6-11e6-992f-0e613e39fc45.JPG)
![issue 143 - problems with module code searching - authenticated session](https://cloud.githubusercontent.com/assets/20297411/16584956/61cd3006-42b6-11e6-96b3-a9053f8e2d08.JPG)
![issue 143 - problems with module code searching - title searching comparison - non-authenticated session](https://cloud.githubusercontent.com/assets/20297411/16584960/67248e46-42b6-11e6-9bf4-02a1c32bc94e.JPG)
![issue 143 - problems with module code searching - title searching comparison - authenticated session](https://cloud.githubusercontent.com/assets/20297411/16584969/6d0918e0-42b6-11e6-91b0-db512480d088.JPG)

**Comment by UniofSunderland** [comment]
The file names don't seem to be displaying so in order of above
1. Non-authenticated module code searching (is not finding LAC278 Talking Pages - correct arabic module code is ARA131 not LAC278)
2. Authenticated module code searching (is not finding LAC278 Talking Pages - correct arabic module is ARA131 not LAC278)
3. Non-authenticated title search for comparison - shows correct list but has wrong module code attached
4. Authenticated title search for comparison - shows correct list but has wrong module code

Note: I was unable to replicate this time (13:30 05/07/16) the triplicate display of lists as in your screenshot - although I have seen this before.  Students should only see the current list and in staff/admin view we will need to have a year next to the list so we can identify which list we should be working on.

Thanks.

**Comment by AndrewIsh** [comment]
Hi

Thanks for the clarification. I'll investigate what's happening and update this issue once I understand.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi

We have this morning pushed out a fix for this to your server. Could you please test that you are now seeing the search results you expect? Please note, as an unauthenticated user you should only see the current year's list, as an authenticated user you should see all years' lists.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi

I'm going to close this issue as I believe this issue is now fixed. Feel free to reopen if you continue to see problems.

Many thanks
Andrew
