### ISSUE TITLE
UniofSunderland - List display - information incomplete

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#144]
When viewing a list the module code, list date and lecturer name attached to list are not displayed.

Current display
![title display example - old mmr](https://cloud.githubusercontent.com/assets/20297411/16580975/ff0de116-429e-11e6-93c5-067d803e0592.JPG)

Display in Rebus 2 with info missing
![when viewing a list no module code date or lecturer attached to list shown](https://cloud.githubusercontent.com/assets/20297411/16580989/1023193a-429f-11e6-861c-8e9b8ce3b407.JPG)

**Comment by AndrewIsh** [comment]
Hi

Thanks for the feedback. I'll create an issue internally and implement this.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1895

**Comment by UniofSunderland** [comment]
Hi Andrew

I just get an error message when following this link – I’m not sure what it is trying to tell me/show me?

Thanks
annika

**Comment by AndrewIsh** [comment]
Sorry, that link is for my purposes, apologies for any confusion.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Annika

An update to fix this was completed yesterday. I'll update this issue once it has been pushed out to your server.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Annika

This is now live. It has highlighted that the "year" field has not been migrated in the current dataset. I have mentioned this to Martin and he has said he will add it to the migration script, so will be added in the next migration. He asked me to thank you for the feedback.

I'll close this issue. Feel free to reopen if you have further problems.

Many thanks
Andrew

**Comment by fionaborthwick1** [comment]
When I was speaking to Sunderland today they were enquiring as to why this issue had been closed when they can't see any change on their system.
I explained that work had been done on our end but they need to have their data reloaded to see the effects of this change.

**Comment by mrenvoize** [comment]
I can see this begin displayed on their system now.
