### ISSUE TITLE
UniofSunderland - Lecturer notes hidden in citation box

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#145]
Important notes that the lecturer has added about the usefulness or directions for the item are hidden in the citation box.  These notes are not part of the citation and need to be displayed automatically without students having to click into boxes.

Old display
![item direction notes visible](https://cloud.githubusercontent.com/assets/20297411/16581167/f7d2007a-429f-11e6-9546-1bcdcd7cd1a3.JPG)

Info hidden in rebus 2
![new mmr item notes hidden in closed citation box](https://cloud.githubusercontent.com/assets/20297411/16581172/023efc20-42a0-11e6-958b-5e8695823696.JPG)

![item direction notes visible](https://cloud.githubusercontent.com/assets/20297411/16581183/0c0ecdac-42a0-11e6-8a64-abf093841c52.JPG)

**Comment by UniofSunderland** [comment]
Sorry last image should have been 
![new mmr item notes displayed in opened citation box](https://cloud.githubusercontent.com/assets/20297411/16581197/25858fd2-42a0-11e6-8048-1f1a0593dc86.JPG)

**Comment by AndrewIsh** [comment]
Hi

Thanks for the feedback.

Apologies, this was an oversight on our part. I have now added the notes field to the templates for all material types. The notes also appear in the citation as the citation format we are using includes the notes field.

In case you're not aware, all your material display templates can be modified in the "Global Settings" > "Material type templates" view.

I'll close this issue, feel free to reopen if you are still seeing the problem.

Many thanks
Andrew
