### ISSUE TITLE
Resize Add items window

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#148]
Hello

Would it be possible to allow users to resize the Add items window - at the moment you can just about see the first reference, when you have a lot of results to scroll through it would really make a difference if you could see more!

![screenshot 2016-07-07 00 51 25](https://cloud.githubusercontent.com/assets/12201255/16638202/5105d67e-43dd-11e6-9a6c-3b6a4df5bea0.png)

best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for this. This is something that has been bothering me of late also, so I'm glad you've mentioned it also. Resizing the window would certainly help, as would reducing the clutter (for example the box containing the progress bar) when the search results are displayed. I'll look at both and get back to you when I have a solution.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
I've been wanting that modal to expand to fill the available screen height for a while.  I seem to remember it being challenging to do,  but it sounds like notes the time to invest in getting that right

**Comment by AndrewIsh** [comment]
Hi Helen

I've just completed a fix for this. The window height should now resize to contain the size of whatever resultset is displaying. We're also now collapsing all resultsets initially, and hiding the scrollbar once the search is complete. This will hopefully making navigating results much easier. This fix has not yet been pushed out to customers. Once it has, I'll update this issue.

Many thanks
Andrew

**Comment by hloliver** [comment]
That's great - thanks for the update
bw
Helen

**Comment by AndrewIsh** [comment]
Hi

I'm going to close this issue as I think we've solved the original problem. Feel free to reopen if you still consider there to be a problem.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew

We’re still seeing the original search window (I think) – the window doesn’t resize and the first set of results is expanded.

But now we’re also finding that the search window sometime disappears if you click on it, or near it – it happened to me by accident when I randomly clicked in the bottom right-hand corner of the search window, and I’ve managed to repeat this several times though it happens at slightly different times and when I’ve clicked on different parts of the screen.

I saw this happen at 12:57, 12:59 and 1:57
Here’s a video – forgive the random mouse movements! http://screencast.com/t/lK0PfyATNAD

Best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Apologies, I was a bit ahead of myself. I was under the impression that this had been pushed out to your server, but it hasn't yet. I'll reopen this issue until it has been pushed out and you are happy.

As far as clicking on the search window and it disappearing is concerned, that's a strange one. Clicking outside the search window should close it, as with any of the other similar windows, but clicking inside it should never close it, yet I can see in the video that it has. I'll invesigate.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew - the other issue may just be that I hadn't noticed it happening before, I could easily have strayed out of the window though I thought that I'd tried that to test it out as well.  I'll have another go next time I'm logged back in.
bw
Helen

Helen Oliver

Systems Librarian
Tavistock & Portman NHS Foundation Trust
Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.uk

**Comment by AndrewIsh** [comment]
Hi Helen

Just to let you know that the modifications to the "Add new items" window are now available on your server. I'll close this issue. Feel free to reopen if you still have problems.

Many thanks
Andrew
