### ISSUE TITLE
Error adding items to a list

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#149]
I've been having some problems adding items to a list, 
https://tavi.rebuslist.co.uk/#/buffer/1590

After selecting a book and clicking on Finish I see an 'Error missing properties' message. The record is loaded into the list, but all of the editing options are greyed out

http://screencast.com/t/Mbd9xPhIuK

I've also tried adding book chapters using the 'Add item as..' feature, but see the same error/options greyed out.  Also the chapter title is missing.

http://screencast.com/t/2pZenLiKf8t

can you take a look?
Thanks 
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for this. Interesting. I'll investigate and get back to you.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

Just looking at this. I can't replicate it on my test list. Would it be ok if I try your list with your login?

Many thanks
Andrew

**Comment by hloliver** [comment]
Please do - I'll leave the login as it is for a while, feel free to use it whenever you need to
thanks
Helen

Helen Oliver

Systems Librarian
Tavistock & Portman NHS Foundation Trust
Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.uk

**Comment by AndrewIsh** [comment]
Hi Helen

I've just added the item from your video to list 1590 (Year 1 Applications Strand - Term 1) while logged in as you, I didn't have any problems. Can you please try adding some more items and let me know how you get on?

Many thanks
Andrew

**Comment by hloliver** [comment]
Hello Andrew
I had another go with this one, I was able to add books/book sections from the EBSCO connector to this list without any problem.  I then went back in and tried to add from existing reading lists and that's where I hit the problem again.

I added 2 books and one book section, clicked on Finish and they were loaded into the list, but all of the editing options were greyed out - see screenshot:

![new_items_can t_edit](https://cloud.githubusercontent.com/assets/12201255/16708336/e86fa6c8-45e7-11e6-8d5b-e63ad00e2d35.png)

I saved the list but saw the 'Oops your list wasn't saved properly' error (which I have been seeing a lot today!).  I clicked on Recover, the items added from EBSCO were there, but the ones from existing reading lists had gone.

Hope this helps to shed some light on it!

Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Sorry to hear you're still having problems with this. I just tried to replicate it by adding an existing rebus:list item to your list (as that's what seemed to cause the problem), but was unable to replicate it. As I mentioned in issue 152, I have turned on logging for your instance in an attempt to catch these tricky problems. If you can continue using the system as normal but, when you see a problem, could you please note down the time. Problems that cause a red popup message in the bottom right corner are of particular interest.

Sorry for the delay in tracking this down, we'll get there in the end!

Many thanks
Andrew

**Comment by hloliver** [comment]
I've tried replicating this issue but can't either - I have been able to add some items successfully, and have also hit some different problems which I have reported separately #155 and #156.
Will let you know if I see it again
bw
Helen

**Comment by hloliver** [comment]
Hi Andrew
I've just seen the problem where the items were loaded but editing options greyed out again
https://tavi.rebuslist.co.uk/#/list/1620, then when I tried to publish the list an 'Error buffer 1620 not found' appeared.  When the list refreshed the new items hadn't been saved.

I added the items at 07:11 and saved at around 07.16
![editing_options_greyed_out_with_error](https://cloud.githubusercontent.com/assets/12201255/16756956/b355b8b8-4800-11e6-8075-47cc10c5d717.png)

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this. I realised this morning when I checked the logs that I'd made a typo in your log configuration and, as a results, logs were not being created. Sincere apologies for this, I'm feeling very foolish! Would it be possible for you to let me know next time you see this and I'll check the logs again!

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

I've had another go at replicating this, but was unable to. I'll close this issue for now, feel free to reopen it if you continue to see the problem.

Many thanks
Andrew
