### ISSUE TITLE
Manage tags problem

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#15]
Similar problem as My Lists.  If tags search returns no matching tags most of the display disappears and the only way to recover it is to refresh the screen:
![rl tags1](https://cloud.githubusercontent.com/assets/10532724/8253229/b07c1676-1685-11e5-97a5-69ee3a51ba70.JPG)

**Comment by AndrewIsh** [comment]
Confirmed. Logged as issue https://github.com/PTFS-Europe/rebus-list/issues/782

**Comment by AndrewIsh** [comment]
This has been fixed upstream and will be available on the preview server when we next push master to it
