### ISSUE TITLE
Edit mode/List Actions tooltip popups obscured as you scroll down

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/rebus-list-2#151]
Originally reported by YSJ - in edit mode (also View mode) the button bar stays visible no matter how far the page you scroll - this is a nice feature. Unfortunately the hover over text from the uib-tooltip is only visible when you are at the very top of the page and you can't see the hover over text when you are lower down as it's obscured by the browser bars.

**Comment by AndrewIsh** [comment]
@janetc Would this work better if the tooltips were under the icons?

**Comment by janetc** [comment]
yes if that's a straightforward way to handle it, that would be great

**Comment by AndrewIsh** [comment]
OK, I'll do that

**Comment by AndrewIsh** [comment]
Hi Janet

This has now been fixed in master. I'll be live the next time we push master out to customers. I'll close this issue, feel free to reopen if it continues to be a problem.

Many thanks
Andrew
