### ISSUE TITLE
Error message : Oops, it looks as if your last session wasn't properly closed...

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#152]
Had this problems several times today.

I created a new list, and added several items from the EBSCO connector (a lot were incomplete records so I wanted to see what they were and where they were coming from)

I added notes to several records, then saved the list.  When I went back in to edit the list a pop-up appeared with "Oops, it looks as if your last session wasn't properly closed..." I tried the Recover option, got the list back but all of the notes were gone. Several red error messages flashed on and off at the bottom of the screen at various points, which should have been captured in the video.

This is the list, https://tavi.rebuslist.co.uk/#/list/1619, and here's a longish video:
http://www.screencast.com/t/NT3EcP4ykYFs

Can you take a look?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks very much for the video, very useful. I've tried replicating this problem this morning on this list while logged in as you, but was unable to. I've turned on logging for your instance in an attempt to catch it next time it happens. If you get a chance, could you please have another go at replicating it.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi (again)

I should have added, if you manage to replicate it, could you please make a note of the exact time it happens, that should enable me to more easily track it down in the logs.

Many thanks
Andrew

**Comment by hloliver** [comment]
I've tried replicating this but with no success.  I'll let you know if I see it again.
bw
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for the update. I'll close this issue for now. Reopen if you see it again.

Many thanks
Andrew
