### ISSUE TITLE
Find item on shelf - open in new window/tab?

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/rebus-list-2#153]
From YSJ - Clicking on an item even in edit mode takes you to the catalogue entry on Prism - which is quite useful but it doesn't open a new tab which means you lose your place on any editing you are doing.  (Also for YSJ apparently when they get back to Rebus 2.0 it's prompting for a new username/password - however I haven't been able to reproduce this.

Could open links in a new tab be a preference perhaps?

**Comment by AndrewIsh** [comment]
Hi

This has now been fixed in master. I'll be pushed out next time the customers' instances are updated. I'll close this.

Thanks
Andrew
