### ISSUE TITLE
Editing user permissions doesnt open window

### ISSUE THREAD

**Issue by ChrisLanghamBCU** [PTFS-Europe/rebus-list-2#154]
I want to edit the user permissions of a particular user James Dean, when I click on Edit User Permissions no window opens. I've setup a replacement login for the user and while I was able to access the User Permissions once - I haven't been able to subsequently get back into window.

Please advise.

Thanks
Chris

**Comment by AndrewIsh** [comment]
Hi Chris

Many thanks for your question. I've had a look and there appears to be a problem getting the user details. I'll create an internal issue and investigate. Also tagging @mrenvoize in this as he may want to contribute.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Fixed with https://github.com/PTFS-Europe/rebus-list/issues/1908
