### ISSUE TITLE
Items selected from connector not added to list

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#155]
I've just tried adding a couple of items to this list https://tavi.rebuslist.co.uk/#/buffer/1620
I selected them from Rebuslist: Existing items section, clicked on Finish but the items were't loaded into the list:
http://screencast.com/t/EOOqEMtOU

11/7 22:22

bw
Helen

**Comment by hloliver** [comment]
Sorry, forgot to say that this happened a couple of times so hopefully will show up in the logs a few minutes earlier than this too.

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this. I realised this morning when I checked the logs that I'd made a typo in your log configuration and, as a results, logs were not being created. Sincere apologies for this, I'm feeling very foolish! Would it be possible for you to let me know next time you see this and I'll check the logs again!

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

Looking at your video, it looks as though you were trying to add an item that already existed on the list. This would explain why the item was not added, however, you should have received a warning alerting you to this. I have replicated the actions you took and each time I received a warning that I was trying to add an item that already existed on the list. I have been working on this warning recently, so it may be that there was a bug that is now fixed.

I'll close this issue, but please reopen it if you continue to see the problem.

Many thanks
Andrew
