### ISSUE TITLE
Problem adding duplicate items

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#156]
Hello
Having problems adding duplicate records to a list 

https://tavi.rebuslist.co.uk/#/buffer/1590
Tried adding "Drama from Ibsen to Brecht" but got a red error saying that the item already existed in the list, I tried to add a chapter from this, but on clicking Finish saw two different errors:
http://www.screencast.com/t/nzCUkc6GXla
(apologies, I think it t was probably between 22:30 and 22:40 - the time on the videos say 21:38 but think they're about an hour out)

I then tried adding a chapter from the same book but without trying to add the book first, and this time just got the error that the item already existed in the list
http://screencast.com/t/dGHhwAQiA9 (11/7 22:50)

bw
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this. I realised this morning when I checked the logs that I'd made a typo in your log configuration and, as a results, logs were not being created. Sincere apologies for this, I'm feeling very foolish! Would it be possible for you to let me know next time you see this and I'll check the logs again!

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

I'm going to close this issue for now as I've not been able to replicate it. Feel free to re-open if you are still seeing the problem.

Many thanks
Andrew
