### ISSUE TITLE
Error when creating new user

### ISSUE THREAD

**Issue by ChrisLanghamBCU** [PTFS-Europe/rebus-list-2#157]
I am unable to any create new users at present. Each time I save the user form, an error box appears at the foot of the screen and no user record is created.

Problem has only started happening this week as I was able to create new users up to the end of last week. Can you take  a look at this.

Thanks
Chris

**Comment by AndrewIsh** [comment]
Hi Chris

Thanks for this. Do you have any details of what the error says when you attempt to create a user? I just created a new user `andrew_admin` on your instance without any problem. If you have any additional information it may help in tracking down the problem.

Many thanks
Andrew

**Comment by ChrisLanghamBCU** [comment]
Hello Andrew,

The error message is blank. I've tried setting up 3 different users all with the same outcome.
![image](https://cloud.githubusercontent.com/assets/20300570/16761980/6f6472c4-481a-11e6-804c-bae93c181407.png)
I've tried both Chrome and IE11.

All the best
Chris

**Comment by AndrewIsh** [comment]
Hi Chris

Thanks for that. I have just successfully created another admin user and a staff user with no problems. I must confess to being mystified as to what is happening. I've turned on logging for your instance. Could you please try again to create a user, note the time that you get the error, and let me know. I'll then track it down in the logs.

Many thanks
Andrew

**Comment by ChrisLanghamBCU** [comment]
Hello Andrew,
I've just tried to create 2 new users again with the same problem - at 15:09 and 15:10.

All the best
Chris

**Comment by AndrewIsh** [comment]
Hi Chris

Sincere apologies. I noticed this morning that I had made a typo in your logging config and, as a result, no logs were created for your attempts yesterday afternoon. Sorry, foolish mistake on my part. Could I ask that you please try one more time!

Many thanks
Andrew

**Comment by ChrisLanghamBCU** [comment]
Hello Andrew,

No worries. I've just tried to create another 2 users at 09:05 and 09:09 - again with the same results.

All the best

Chris

**Comment by AndrewIsh** [comment]
Hi Chris

Thanks for that. I'm not seeing anything in the logs suggesting that there is a problem. I think to attempt to move forward with this, I'm going to need some more information.
- Which user are you logged in as when attempting to create new users?
- Does the red error box appear immediately after you click "Finish" or is there a delay?

Apologies for all the questions!

Many thanks
Andrew

**Comment by ChrisLanghamBCU** [comment]
Hello Andrew,

I am currently at a different campus library and I have tried to recreate the issue. I’ve noticed that the form here does not have a password field – whereas the form I’ve been using to create a new user does have a password field.

[cid:image001.png@01D1DD0D.DF0F72E0]

I’ve been able to save the form and the green box came up at the foot of the screen but the user record has not been created.
Does this allow you to move further forward?

All the best

Chris

**Comment by ChrisLanghamBCU** [comment]
Hello Andrew,
I've replied directly to you. If email hasn't come through please get back.

All the best
Chris

**Comment by AndrewIsh** [comment]
Hi Chris,

I've not seen your email, I'll drop you one that you can reply to.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Chris (again)

To answer your question, the fact that you're seeing a password field is odd, and undoubtedly the cause of the original problem. Can I ask you to clear the browser cache on the machine you are using for creating the user and check if you are still seeing the password field.

As for the new user being accepted but not created, this is extremely odd and prompts a couple of questions:
- How did you determine that they had not been created? Did you search for them?
- Did the new user receive an email asking them to set their password?

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Chris (yet again)

I've since checked and searching for the user's name in the "Manage users / permissions" page does bring up a result. So it would appear they were created. I'd still be interested in the answers to the questions above though.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Chris

I'll reply to your email here, so we have a correspondence trail. I realise you're very busy, so please don't feel obliged to act on this urgently.
1. Your inability to find the new user immediately after creating them was actually a bug. I've just fixed it here, this will hopefully be pushed out to your server shortly. Apologies for that. You were unable to log in as this user because this cannot be done until a password has been set.
2. The inability of the new user to set their password is interesting. I've been trying to replicate it with no success. I created a new user, clicked on the link in the subsequent email and set a password, I then logged in as the new user. Looking in the database, it does look like your new user has successfully set a password, are they still unable to log in? If not, are they getting an error?

Many thanks
Andrew

**Comment by ChrisLanghamBCU** [comment]
Hello Andrew,

I have now been able to successfully setup a new user. 
I had cleared my browser cache and the password field no longer appeared in the form. I created a new user and they appeared in the user search. The password reset email was sent to the user and she was able to successfully login using her login and password.

Many thanks for your help
Chris
