### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by robinmajorBCU** [PTFS-Europe/rebus-list-2#158]
Search doesn't appear to be working for us right now; we are just seeing a revolving "populating search" icon and the red "no go" symbol.  We aren't aware of any current activity within our organisation that would potentially cause performance problems.

**Comment by AndrewIsh** [comment]
Hi Robin

Many thanks for the report. I'll create an internal issue and investigate.

Many thanks
Andrew

**Comment by robinmajorBCU** [comment]
Hi Andrew,
Search has been down for over a week now - it's causing huge problems as we are in the middle of trying to sort out a number of issues around the data migration from v1 to v2 - could we have an update asap please?

**Comment by AndrewIsh** [comment]
Hi

Apologies for the delay in getting this sorted. I've passed it on to @mrenvoize as it would appear to be a problem at the API end. He should be able to give you more detail and an ETA for a fix.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
I'm investigating this at the moment.

**Comment by mrenvoize** [comment]
This should now be working after the data reload... I'm still investigating the original cause and have debugging turned up on your system.
