### ISSUE TITLE
My lists - moderator filter

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#16]
As np_admin / npa_bilbo assigned moderator permissions to np_staff / test for the Example - Science Fiction list.
![moderator](https://cloud.githubusercontent.com/assets/10532724/8302844/7e01acc4-1991-11e5-94c9-68c9f25c6059.JPG)
When signed on as  np_staff / test the My list doesn't recognise user as Moderator for this list
![capture](https://cloud.githubusercontent.com/assets/10532724/8302915/fce99dc6-1991-11e5-99d7-8977cec9ccb6.JPG)

**Comment by AndrewIsh** [comment]
Not clear on this one, in the second screenshot the "Role" column clearly shows the user has a role of "Moderator" on the list. What is suggesting to you that they don't have moderator role?

**Comment by AndrewIsh** [comment]
Ah, if you're looking at the "Moderating" column, that indicates if there is an active moderation request on the list, not whether you're a moderator or not. Good point, that wording needs changing I think.

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/799

**Comment by mrenvoize** [comment]
Closed in above issue on master branch.
