### ISSUE TITLE
Table Filters/Sorts are not intuitive 

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#160]
As reported by York St Johns:

![screenshot from 2016-07-17 20-30-29](https://cloud.githubusercontent.com/assets/557612/16902677/20a9a7ce-4c5e-11e6-9749-9771f74cb299.png)

**Comment by AndrewIsh** [comment]
Agreed about column headings, adding sorting icons like https://design.google.com/icons/#ic_sort_by_alpha has been on my to-do list for a while.

Not clear on the second point:

> it looks like you should be able to click in here to filter your results

That's precisely what you can do in that box

I'll look at this area and see what can be done.

**Comment by AndrewIsh** [comment]
Closed in https://github.com/PTFS-Europe/rebus-list/pull/1930
