### ISSUE TITLE
logins are case sensative

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#161]
Reported by YSJ

By design 'logins' are case sensitive; however this causes problems fro LDAP as it's 'search' is case insensitive, but it's return data is case sensitive..

This yields the situation where 'Joe.bloggs' and 'joe.bloggs' login in LDAP as the same user, but may pass back 'Joe.Blogs' as the username for rebus match on.  

In short, it opens up the door for duplicate users being created.

**Comment by mrenvoize** [comment]
This is now fixed in development and will be deployed at the next push

**Comment by AndrewIsh** [comment]
Closing
