### ISSUE TITLE
Citation Display Enhancements

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#167]
Currently CSL styled Citations can just be added inline into the material templates, and thus appear in the record.

I think the citation view should be it's own thing, under a button with a modal that pops up with the record in csl styled form.

As a further enhancement, said modal could eventually include a drop down menu to select one of a set of citation styles so the user may switch between styles.

**Comment by AndrewIsh** [comment]
:+1:

**Comment by AndrewIsh** [comment]
This is now done and will be available in v17.08.01.146

Closing
