### ISSUE TITLE
Can't Add a Broadcast

### ISSUE THREAD

**Issue by paulwilliamsBCU** [PTFS-Europe/rebus-list-2#168]
We use Box of Broadcasts (a resource which provides access to TV and radio programmes) at BCU and have been promoting heavily this summer. At the moment, I'm having problems manually adding a programme to a list - I'm getting two errors (see attached). The errors show after filling in the forms to add a broadcast.

 Oddly, the second time I try it, the item appears on the list, but I still get the errors and the word 'Series' appears directly after the title (although I think that might be just a template issue I can fix).

Best

Paul

**Comment by mrenvoize** [comment]
First thing that hits me here is.. 'Does "Box of Broadcasts" have an API?'.. we could add a connector for it if so (at some point).

As for a more immediate solution regarding adding them manually..  I can't see your attachments?  If you can't easily add them (no idea where they've gone), then the error message would be helpful if there is one.

Many thanks,

**Comment by paulwilliamsBCU** [comment]
Aha, that's because I completely forgot to attach it! _rolls eyes_ :-)

You should find it here now. I'll find out about an API for Box of Broadcasts - that would be very neat.

Thanks Martin.

Paul

[Broadcast error.docx](https://github.com/PTFS-Europe/rebus-list-2/files/375385/Broadcast.error.docx)

**Comment by mrenvoize** [comment]
Aha, that's really helpfull. It looks like a recent change to those form template mapped a field incorrectly.  

I've just corrected that and push it to the deployed codebase.. it should work now :)

**Comment by paulwilliamsBCU** [comment]
Works perfectly now - thanks Martin!

**Comment by AndrewIsh** [comment]
Fixed - closing
