### ISSUE TITLE
Can't set user permissions

### ISSUE THREAD

**Issue by paulwilliamsBCU** [PTFS-Europe/rebus-list-2#169]
Hi

Since our last data refresh last night, I can no longer set permissions for users. I can get to the screen (see attached), but the various roles buttons won't 'indent'.

[Doc1.docx](https://github.com/PTFS-Europe/rebus-list-2/files/375980/Doc1.docx)

**Comment by fionaborthwick1** [comment]
I can reproduce this. I cannot get any permission to stick at any level in the hierarchy.

**Comment by paulwilliamsBCU** [comment]
This seems to have been mostly resolved, although I can't currently edit my own permissions (the box showing the hierarchy doesn't pop up).

**Comment by mrenvoize** [comment]
@paulwilliamsBCU I think I've just squashed the last bug in this area :)
