### ISSUE TITLE
My List - staff user

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#17]
Staff admin permissions np_staff / test.  
![capture](https://cloud.githubusercontent.com/assets/10532724/8308939/8b48ea2c-19bf-11e5-80ee-83a4adf4f5ef.JPG)
Click on AS400 Cosmology or Example - Science Fiction 'page not available'.  Click on Edt list items icons - 'page not available'
But click on Module AS390 - Astrophysics (or Edt list items) both functions work.  Note: this list is the user is Editor, other two the user is Moderator.  The other Editor role list on the display, Big Bang also works.

**Comment by AndrewIsh** [comment]
I think this is related to https://github.com/PTFS-Europe/rebus-list-2/issues/18, I think there's something wrong with the "Example - Science Fiction" list. This issue suggests that "AS400 Cosmology" may have the same problem. Any clues in the DB @mrenvoize ?

**Comment by mrenvoize** [comment]
Pretty sure this has been cleaned up along the way recently.. lets close this and open afresh if we're still finding issues.
