### ISSUE TITLE
Items in existing lists - title search

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#175]
Hi 

When carrying out a title search, Rebus is returning far too many results from existing lists. The browser freezes for a few minutes and it brings back thousands of results. In the image,1958 results were returned. Very few are relevant to the search and the list scrolls on for ages. Can you have a look to see why this is happening? It seems to have started recently. 

![items in existing lists](https://cloud.githubusercontent.com/assets/17139950/17138370/de81c116-5337-11e6-8ca7-2083bdc42ab3.png)

Many thanks

Richard
UHI

**Comment by janetc** [comment]
Bucks New have also reported this yesterday.  Example - search for 
graphic design 
The problem is in records retrieved in existing results.

**Comment by mrenvoize** [comment]
I can't see that this has changed of late.. however I can see why that particular search gets so many results..

It's looking for ANY material where the author, original-author, collection-title, container-title, container-title-short, original-title, title OR title-short CONTAINS the string 'handbook' OR 'of' OR 'archaeological'.

The 'of' in this case gets picked up a huge amount of times.

So.. we need to implement stop-words.. which is on our list of enhancements.

**Comment by mrenvoize** [comment]
@richughes Have you tried 'phrase' search.. i.e. "handbook of archaeological"

**Comment by richughes** [comment]
@mrenvoize 
Okay, I'll ask staff to try phrase searches instead. I think it was probably just less of an issue when we had fewer items in the system. It's good to hear that stop-words is on your list of enhancements though.

I'll close this ticket.

**Comment by mrenvoize** [comment]
@richughes I've now added a cursory stopwords implementation.  Currently it's a hard coded list of stopwords `and the at to from of if it am me` that will get removed from unquoted phrases.

My intention is to expose this list via a system preference in a near future rollout, but I thought let's get the basics working for now whilst it's fresh in my mind.

This is now live on your system, and the results are promising.

Searching: `"handbook of archaeological"` yields just one result, the one I expect you were looking for
Searching: `handbook of archaeological` now yields 157 results in a much more reasonable time. The result you're looking for is 18th in the list of results.

Note to self, add relevance ranking?
