### ISSUE TITLE
API: Empty response for list 69

### ISSUE THREAD

**Issue by AndrewIsh** [PTFS-Europe/rebus-list-2#18]
As reported by Nick P:

Student access (not logged in) to reading lists not working (using Chrome, Firefox, IE browsers)
 using Search, browse or link (https://preview.rebuslist.com/#/list/69)

Logged in access (np_admin / npa_bilbo)
Search not working but Direct link and Browse OK

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/798

**Comment by mrenvoize** [comment]
Preview has been updated allot since this report and I believe this issue is fixed. 

Closing for now as I'm sure if it's still there someone will spot it and raise a new issue quick enough ;)
