### ISSUE TITLE
SQL - empty lists report (UHI)

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#181]
Hi 

I copied and pasted the "Lists containing no material" query into the reports area. When I run the report it tells me that over 600 of our lists are empty. I checked some and many of the lists in the report actually have content. For example, Ainm-eòlas na h-Alba [UL708477] is listed in the report:

![sql empty lists](https://cloud.githubusercontent.com/assets/17139950/17251207/a01685e6-559f-11e6-9047-c56d56747e49.png)

but it actually has 10 items on it. Can you tell what's going wrong? 

Many thanks

Richard

**Comment by mrenvoize** [comment]
Hmm, looks like there may have at some point been a bug in the calculation of that field.  I'll reset the counts and watch to see if it arises again.

Thanks for reporting.

**Comment by richughes** [comment]
Hi 

I've tried running this report a few times since and still getting a lot of results that shouldn't be on the list. 

I've attached the spreadsheet it produces. "Number of items" field is blank, but many of the lists have items. Can you have a look?

Thanks
[UHI empty lists SQL error.xlsx](https://github.com/PTFS-Europe/rebus-list-2/files/413209/UHI.empty.lists.SQL.error.xlsx)

**Comment by mrenvoize** [comment]
I've added a more refined report to your system now richughes, which only counts empty 'lists' rather than the whole set of difference hierarchy taxons (units, lists and sublists).

That brings your total down to a couple of hundred.  So far, I've not been able to find any false positives though..

**Comment by richughes** [comment]
Thanks @mrenvoize , the results look much more acurate now. Will close this one. 

Richard
