### ISSUE TITLE
Lists not displaying categories/items in Edit mode

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#182]
Hi

I've created a couple of new lists yesterday/today which are fine when I view on the public site, but when I go in to edit them I only get access to the list summary section, the categories and items which were added are missing.

https://tavi.rebuslist.co.uk/#/list/1992 (3/8/16 08.54)
and 
https://tavi.rebuslist.co.uk/#/list/1993 (4/8/16 around 6.45 and 7.45)

![editing_list-no_items](https://cloud.githubusercontent.com/assets/12201255/17392799/c0476160-5a17-11e6-9150-7990d3c7fb21.png)

I wondered if it was only happening for newly created lists, but have had the same problem with a list which was migrated from RL1:

https://tavi.rebuslist.co.uk/#/list/690 

whereas this one is fine: https://tavi.rebuslist.co.uk/#/list/1168

I've been using two different computers, and three different browsers (Safari, Chrome and Firefox) all with the same results

can you take a look?
thanks
Helen

**Comment by mrenvoize** [comment]
I've also been seeing this occasionally since the last update.  Marking as critical bug and making @AndrewIsh aware

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#2018

**Comment by hloliver** [comment]
Hi
I'm still getting this quite often, including the last two lists that I created today:

https://tavi.rebuslist.co.uk/#/list/2006
https://tavi.rebuslist.co.uk/#/list/2007 

Helen

**Comment by mrenvoize** [comment]
I can no longer replicate this.. we've done a few database updates for other issues and I'm thinking this has also inadvertently fixed this issue. Could you please re-raise it if you see it again?
