### ISSUE TITLE
Displaying First Page in Journal Articles

### ISSUE THREAD

**Issue by paulwilliamsBCU** [PTFS-Europe/rebus-list-2#190]
Hi

I'm having trouble setting the First Page metadata field to display in Journal Article types added manually. I have edited the template to include:
First Page: <csl-page-first></csl-page-first>

It's not showing however for the article titled 'Whither North Korea' in:

https://bcu.rebuslist.co.uk/#/list/4342

The article has a first page in the metadata. Am I doing something wrong?

**Comment by jonmcgowan** [comment]
Hi Paul,
The problem will be down to the template modification you've now got this:

<span hide-if-empty> First Page: <csl-page-first></csl-page-first> Page: <csl-page></csl-page></span>

Both 'First Page' and 'Page' are within the hide if empty span - this will mean that if either value is empty the span will be hidden. 

I've edited the template to be:

<span hide-if-empty> First Page: <csl-page-first></csl-page-first></span><span hide-if-empty> Page: <csl-page></csl-page></span>

The page should now display correctly

cheers

Jon McGowan

**Comment by jonmcgowan** [comment]
Sorry - messed up the quotes the examples should have been:

Current:

`<span hide-if-empty> First Page: <csl-page-first></csl-page-first> Page: <csl-page></csl-page></span></h6>`

Fixed:

`<span hide-if-empty> First Page: <csl-page-first></csl-page-first></span><span hide-if-empty> Page: <csl-page></csl-page></span></h6>`

cheers

Jon

**Comment by paulwilliamsBCU** [comment]
Many thanks Jon - that makes sense, and this one is showing. I do also have a number of pages field in there too, but that one also not displaying - could you take a look please? The template says:

<span hide-if-empty> Number of Pages: <csl-number-of-pages></csl-number-of-pages></span>

I'm a little confused anyway with this one, as adding a manual Journal Article type has two fields for number of pages. One under the Article Pages tab and another under the Misc tab. Not sure which we should use - looks like the misc one is showing in the citation.

**Comment by jonmcgowan** [comment]
Hi Paul - The reason for the two different fields is that they are for different things - the labeling is confusing so I will be sorting that out. One field means number of pages as in a number e.g.  10 pages.
The other field actually means Page Numbers - e.g 1,2,3,4,5.  
They are both listed in csl - I will go through and relabel them. Once that is done I'll check the templates for manual display to see that the fields are mapped correctly. 
Thanks for feeding this back!

Jon

**Comment by mrenvoize** [comment]
Just to clarify that even further, in csl these fields are indeed used for different types of data.

@jonmcgowan example isn't great though as it demonstrates the concept using consecutive pages, which of course is likely better expressed as a start page + number of pages pair.

A better example would be '1, 13, 22-24' for example where you've got particular pages spread seemingly randomly across a resource.

The best example I could think for this was a magazine article where a first paragraph may be on one page to attract the readers attention with a 'continued on page...' at the end with the remainder of the article continuing a few pages later.

Hope that helps clarify the use cases.

I can also see lecturers wanting to tell a student to read certain pages.. But I would think this better expressed as a note on the overall item.

**Comment by jons** [comment]
i did what now
