### ISSUE TITLE
Enhancement Request for Pinned 'Finish' Button

### ISSUE THREAD

**Issue by paulwilliamsBCU** [PTFS-Europe/rebus-list-2#194]
When using the Connector to add items to a list, would it be possible to pin the 'Finish' button to the screen in the same way the Edit bar stays on screen? There's been some feedback about needing to scroll to the bottom of the page each time to finish your selection. Sample screenshot attached.
[Finish.docx](https://github.com/PTFS-Europe/rebus-list-2/files/407152/Finish.docx)

**Comment by mrenvoize** [comment]
I've added this to our internal tracker, similar had been on my mind for a while, it's god to hear a customer agree.

**Comment by AndrewIsh** [comment]
Hi Paul

I've just completed a fix for this, it will be pushed out to customers servers with the next update.

I'll close this issue, if you have any further questions regarding this, feel free to re-open.

Many thanks
Andrew
