### ISSUE TITLE
Create user - password field missing 

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#196]
Preview2 and Chrome 

Template doesn't contain password field

![creat user template](https://cloud.githubusercontent.com/assets/10532724/17560101/aeade2a2-5f18-11e6-8732-d13e7c28f4b8.JPG)

**Comment by mrenvoize** [comment]
Indeed.. it doesn't, you get emailed a password form to fill in.

**Comment by NickPhipps** [comment]
I tried that - Preview2 did not email a form

**Comment by NickPhipps** [comment]
It didn’t email a form and it didn’t email anything when I tried reset password.  

Also – latest training guide  12/7/16 needs updating (doesn’t refer to email).

Nick Phipps

PTFS Europe 

+44 7824 883 751

**Comment by NickPhipps** [comment]
As stated on previous message - Preview2 is NOT EMAILING a password form for me to fill in.

**Comment by mrenvoize** [comment]
Emails are queued, and should be sent within 5 minutes of the request.. all my requests in the last 5 minutes have come through.
