### ISSUE TITLE
Reset user password - does not sent reset email

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#198]
![reset password](https://cloud.githubusercontent.com/assets/10532724/17561353/77cab01c-5f1d-11e6-912a-983f8afea84a.JPG)

Edit template displayed.  Click on 'Reset password' - message (bottom right of screen) confirms email sent.  But email not received at address displayed on Edit template.

**Comment by NickPhipps** [comment]
Not mentioned above - 'Finish' icon pressed too.

**Comment by NickPhipps** [comment]
Issue open

**Comment by mrenvoize** [comment]
Emails are queued, and should be sent within 5 minutes of the request.. all my requests in the last 5 minutes have come through.

**Comment by NickPhipps** [comment]
When they eventually came through it was 30 mins+.  Might be worth a ‘may take several mins …’ message on UI.   Thanks.

Nick Phipps

PTFS Europe 

+44 7824 883 751
