### ISSUE TITLE
Hierarchy module - editing list meta data

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#20]
Changed list metadata (Example - science fiction) 'Unable to update list' error message (also on other lists' metadata.  User np_admin / npa_bilbo.

**Comment by AndrewIsh** [comment]
As mentioned in issue #17, there appears to be something wrong with your "Example - science fiction" list. Please do not use this list until it is fixed, most of these errors you're seeing are due to the list rather than the app

**Comment by AndrewIsh** [comment]
Fixed some time ago, closing.
