### ISSUE TITLE
Problems publishing list

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#203]
Just tried to publish changes on the following list https://tavi.rebuslist.co.uk/#/list/1997 but got a red error box (no error details on server, server may be unavailable)
- When I went into it again there was a warning flag on the list's title which said there was an active draft with unsaved changes
- I was then able to publish this list and the new reference (for Seminar 2) appeared
- when I went in to edit the list again it was empty 
- inadvertently refreshed the page while trying to get a screenshot of the empty list(!), this brought back the references, but the one that I'd just added to Seminar 2 only displayed the note and was missing the item data
  ![screen shot 2016-08-15 at 08 57 20](https://cloud.githubusercontent.com/assets/12201255/17658928/e7b0f6e6-62c6-11e6-9811-d1a63a72242f.png)

for info this all occurred between 8.30 and 9.00 in case you've got logging switched on for us

**Comment by EleanorJohnston** [comment]
I believe it is because only librarians can publish. Moderators, editors, owners cannot, so any changed must be passed onto a librarian. We do not have capacity to do this so have asked PTFS to modify permissions.
