### ISSUE TITLE
UHI - judgemental kitten in edit mode

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#204]
Hi 

We have some lists that return the judgemental kitten error when we try to enter edit mode, can you free them up please?

Clinical dentistry 3 (1) [UB709763]
https://uhi.rebuslist.com/#/list/1464 
ERROR
Error: Properties not allowed: frbr_equivilents.
Path: /categories/0/materials/0

Civil engineering technology 2 [UH208425]
https://uhi.rebuslist.com/#/list/1520
ERROR
Error: Expected number - got string.
Path: /categories/0/materials/1/metadata/number-of-volumes

Literature review (Health Studies) [UB709767]
https://uhi.rebuslist.com/#/list/1749
ERROR
Error: Expected number - got string.
Path: /categories/1/materials/11/metadata/number-of-volumes

Thanks

Richard

**Comment by mrenvoize** [comment]
Sorted, my apologies.
