### ISSUE TITLE
Edit materials - no "Finish" button (UHI)

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#206]
Hi 

When we try to edit an existing entry in the Search for Material area, there is no Finish or Submit button to save our changes. We're not getting any red messages to say the record is incomplete, so there doesn't seem to be anything wrong with the records. I've checked a few with the same result. 

![edit materials](https://cloud.githubusercontent.com/assets/17139950/17701917/a87e902a-63c3-11e6-959d-6cf024077c43.PNG)

Can you have a look?

Many thanks

Richard

**Comment by fionaborthwick1** [comment]
Hi Richard,

I may be on the wrong track here but I thought I would send a quick response anyway.  I believe that this is correct behaviour if you are trying to edit the metadata for an item that has been brought in through your connector.  It should not be possible to edit this item as the data from the LMS should be accurate.

You can edit the metadata for any list item entries that have been added manually and you should see the Finish button on these entries.

Does this explain what you are seeing?

Thanks,
Fiona

**Comment by richughes** [comment]
Hi Fiona

Okay, that makes sense then. I think it may have been a COPAC entry that the librarian was trying to update now that the book has been purchased. Our Summon holdings don't update immediately from Millennium so this was a way round it until the new book became available via the Summon connector. I'll let them know deleting the placeholder/COPAC entry and adding it again is the best way to solve it. 

Will close the ticket.

Thanks

Richard
