### ISSUE TITLE
Forms: Tabs containing missing mandatory fields should be highlighted

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#209]
When adding a material via the manual add option, the form is split across a number of tabs. Currently if an incomplete mandatory field is not on the tab you have currently in view, there is no hint that the field is missing until you attempt to submit the material.

We should highlight the tab changer in red to hint at the missing fields.

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#1997

**Comment by AndrewIsh** [comment]
This has now been implemented and will be pushed out with the next update. I'll close this issue for now, feel free to re-open if it continues to be a problem.
