### ISSUE TITLE
User permissions - moderator

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#21]
Login : np_admin / npa_bilbo
Hierarchy module, select 'Example - Science Fiction', user roles: remove any other users, add np_lib as moderator
Logout
Login: np_lib / npl_bilbo
My lists : filter 'moderating' does not display 'Example - Science...' (displays AS390 Astrophysics)
Hierarchy : check 'Example user role - only np_lib displayed, check AS390 Astro - only Martin R displayed.

![capture](https://cloud.githubusercontent.com/assets/10532724/8328355/06c08d7e-1a68-11e5-9d5e-ae2644b486f7.JPG)
![capture1](https://cloud.githubusercontent.com/assets/10532724/8328363/16b4b778-1a68-11e5-8e43-7be2eb9a5190.JPG)
![capture2](https://cloud.githubusercontent.com/assets/10532724/8328367/1a2a1cb8-1a68-11e5-92d2-7d452a80e973.JPG)

**Comment by AndrewIsh** [comment]
As mentioned in issue #17, there appears to be something wrong with your "Example - science fiction" list. Please do not use this list until it is fixed, most of these errors you're seeing are due to the list rather than the app

**Comment by AndrewIsh** [comment]
This was fixed some time ago, closing.
