### ISSUE TITLE
No connector's are working - UHI

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#211]
Hi

Our connectors aren't working at all. Searching an ISBN that we know is in the system produces no local results and nothing from Summon or Copac. If searches for a split second and says "there were no results for your search". Is it related to the changes made last night?

Can you fix this as soon as possible please?

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Apologies for that, this has now been resolved. Feel free to re-open if you continue to see problems.

Many thanks
Andrew
