### ISSUE TITLE
Can't add or delete list entries - UHI

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#216]
Hi 

When I try to add or delete entries I'm getting a red error message. It's happening on a few different lists, most recently:

Aviation business and management 1 [UN208472]
https://uhi.rebuslist.com/#/list/2491 

ERROR
Error: Expected integer - got null.
Path: /X-Version

Can you have a look as soon as possible?

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for this. I've not been able to replicate this, I just added an item "Test" to the top of this list https://uhi.rebuslist.com/#/list/2491. Can you refresh and try again for me please and let me know how it goes?

Many thanks
Andrew

**Comment by richughes** [comment]
Hi Andrew

I was able to delete your test item and there was no error. I'm still having difficulties adding though. 

When I search an ISBN, the connector results are now bringing back multiple "&" signs underneath the each title. It happens in Summon results and COPAC. 

![summon error](https://cloud.githubusercontent.com/assets/17139950/17856546/f996c08e-6875-11e6-989d-0ef49b6a8fd5.PNG)

When I try to add the item, I now get the following error:

ERROR
Error: The patch attempted to update the model in an unauthorized way
Path: /

Error: anyOf failed: anyOf failed: anyOf failed: Expected array - got string.
Path: / 

I tried various books and got the same result. Can you have another look?

I'm using Firefox 48.0

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard,

Thanks for reporting this. There appears to be something amiss in the Connect response, I'm in the process of reporting it to Alex so he can investigate, I'll update shortly.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Richard

This is now fixed. Many apologies for the inconvenience.

I'll close this issue, feel free to re-open if you continue to see problems.

Many thanks
Andrew
