### ISSUE TITLE
csl-page-last sudo element

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#224]
Can we add a csl-page-last sudo element for the templates, which uses page-first and number-of-pages to calculate a page-last for display?

**Comment by AndrewIsh** [comment]
We have now added a new material template element `<csl-page-last>` which will display the last page of a page range if the material has both "start page" and "number of pages" populated.

It will be live on customer instances on 06/06/17

**Comment by AndrewIsh** [comment]
Closing
