### ISSUE TITLE
No hyperlinks appearing - UHI

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#230]
Hi

None of our records are linking through to the library catalogue, the titles are no longer hyperlinked and there is no icon either:

![no hyperlink or icon](https://cloud.githubusercontent.com/assets/17139950/18087663/406e862a-6eae-11e6-81bf-b7727d01d82f.PNG)

I've tried adding ="lms_link" to the book template with linkify, but any changes I make to the templates won't save. I don't get a green confirmation or red error. 

Can you have a look as soon as possible? We have inductions this week and next and can't currently demo the system to anyone. 

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Many apologies for that. This should now be fixed. I'll contact you by email regarding your data as I have a couple of questions.

I'll close this issue, if you're still seeing problems, feel free to re-open.

Many thanks
Andrew
