### ISSUE TITLE
Browsing and searching lists 

### ISSUE THREAD

**Issue by VickiMcGarvey** [PTFS-Europe/rebus-list-2#231]
# With RL1 we did not need to login to browse or search lists but appears with RL2 we need to login. Has this changed.

Vicki McGarvey Staffordshire University

**Comment by AndrewIsh** [comment]
Hi Vicki

Thanks for your question. You should not need to login to browse or search lists. However, visibility of lists to unauthenticated users is dependent on a couple of things.

Firstly, when creating your list, ensure you finalise it by clicking the "Publish" button in the list edit screen's button bar. This will indicate that you have finished working on this list.

Secondly, only lists that have been made visible in the Manage Hierarchy page will be available for unauthenticated users to view. The little " and > buttons on each hierarchy item control this.

If both of these things have been done and you are still not able to view lists without logging in, let me know and I'll take a look.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Vicki

Further to this. I've dug a bit deeper and have noticed that all your lists are not due to be visible until tomorrow. All lists have a validity period associated with them and all yours' start tomorrow, I assume this is at your request.

I'll check again in the morning, I suspect they'll all magically appear.

Many thanks
Andrew

**Comment by VickiMcGarvey** [comment]
Ok thanks Andrew I was wondering if this was the case we will check tomorrow.

Vicki

---

Vicki McGarvey, BA (Hons) PGDipILS MEd MCLIP CMALT SFHEA
Teaching Excellence Fellow
Learning & Information Services Manager (Collection Management, Eresources, Digital Capabilities)
Information Services, Library, Staffordshire University
F300, Thompson Library, College Road, Stoke-on-Trent
t. 01782 294560 e. vicki.mcgarvey@staffs.ac.ukmailto:vicki.mcgarvey@staffs.ac.uk
[cid:image006.png@01D18B58.9FCEFB20]http://www.staffs.ac.uk/digitalu

**Comment by AndrewIsh** [comment]
Hi Vicki

I've just checked and all your lists seem to be visible today and looking great.

I'll close this issue. If you've got any further questions regarding this, feel free to re-open.

Many thanks
Andrew

**Comment by VickiMcGarvey** [comment]
Hello,

Yes I have checked this morning and all lists are browsable and searchable, without a login.

Many thanks

Eleanor

From: MCGARVEY Vicki
Sent: 31 August 2016 17:41
To: 'PTFS-Europe/rebus-list-2' reply@reply.github.com; PTFS-Europe/rebus-list-2 rebus-list-2@noreply.github.com
Cc: Author author@noreply.github.com; JOHNSTON Eleanor E.Johnston@staffs.ac.uk
Subject: RE: [PTFS-Europe/rebus-list-2] Browsing and searching lists (#231)

Ok thanks Andrew I was wondering if this was the case we will check tomorrow.

Vicki

---

Vicki McGarvey, BA (Hons) PGDipILS MEd MCLIP CMALT SFHEA
Teaching Excellence Fellow
Learning & Information Services Manager (Collection Management, Eresources, Digital Capabilities)
Information Services, Library, Staffordshire University
F300, Thompson Library, College Road, Stoke-on-Trent
t. 01782 294560 e. vicki.mcgarvey@staffs.ac.ukmailto:vicki.mcgarvey@staffs.ac.uk
[cid:image006.png@01D18B58.9FCEFB20]http://www.staffs.ac.uk/digitalu
