### ISSUE TITLE
List search doesn't disappear

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#236]
Hi 

After searching for a list and clicking on the title to open it, the dropdown list of modules doesn't disappear once the chosen list is open. The only way of making it disappear is to press backspace until the search query is deleted. If we click Rebus:list to go back to the homepage the dropdown list still appears. 

This seems to have started recently, can you have a look?

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

This is a bug that crept in last week. I've fixed it in the last 5 minutes, it will be pushed out to customers servers shortly. I'll update this issue when that is complete.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Richard

This has now been pushed out. I'll close this issue, but if you continue to see problems, please re-open.

Many thanks
Andrew
