### ISSUE TITLE
Amazon book jackets being sent via http not https

### ISSUE THREAD

**Issue by wl0ifr** [PTFS-Europe/rebus-list-2#240]
Completing testing I noticed that both Firefox and Chrome highlighted that my list was insecure.

I've looked and it appears that this is caused when a book jacket is retrieved from Amazon as it's using http rather than https.

Jackets from Google are using https.

I'm attached 3 screen shots.

"Chrome secure no amazon jackets loaded" shows site is secure when in Global Settings
"Chrome not secure" shows site is insecure when displaying a list
"Firefox not secure" as above

![chrome secure - no amazon jackets loaded](https://cloud.githubusercontent.com/assets/22322736/18672574/8fcd56fe-7f40-11e6-80ae-76c47c071aa1.png)
![chrome not secure](https://cloud.githubusercontent.com/assets/22322736/18672576/8fd143d6-7f40-11e6-974c-bc647bbfaeb0.png)
![firefox not secure](https://cloud.githubusercontent.com/assets/22322736/18672575/8fce3a06-7f40-11e6-8f00-26ce7ac21a05.png)

**Comment by AndrewIsh** [comment]
Hi

Many thanks for bringing this to our attention. As you've noted, mixed content warnings such as these are undesirable. We'll investigate and update this issue once a solution has been implemented.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
It looks like there was a regression for this in the service we use to cache image urls.

I've now corrected the regression and pushed out the service fix so all customers should be running without any secure content warnings again.

Many thanks for bringing it to our attention.

Martin
