### ISSUE TITLE
UniofSunderland - copied permissions

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#242]
Permissions copied from RebusList 1 when the data was migrated has granted staff (lecturers) “Librarian” level  access when it should be “Editor” as our lecturers only have permissions to edit lists and "publish to library”

Further to this Owner/Leader cannot be deselected if selected as part of the migration, selecting owner/leader to a new or existing list is ok and can be removed, it is the lists that have migrated with this value that are affected.

Have example of member of staff 'Susan Mandala' but cannot paste image into this report.

**Comment by fionaborthwick1** [comment]
There have been a lot of changes to the user roles and permissions area in the last few weeks. It may be worth exploring this one again to see if the problems remain.  As you will see the terminology has changed so we now no longer have Librarian - this has been replaced with Author.

The Author role allows direct publishing whilst the Editor role allows the member of staff to edit lists but those changes then require moderation.

**Comment by fionaborthwick1** [comment]
I explained (and showed) some of the changes / developments with the user permissions at meeting yesterday. We really need to do a reload of user data to see if the situation has improved before investigating further.

**Comment by fionaborthwick1** [comment]
Hi,

I believe that this should now be resolved resulting from a mixture of development work in the user permissions / roles area and several reloads.

Please log any discrepancies, problems or questions you have about this on the helpdesk.

Thanks,
Fiona
