### ISSUE TITLE
UniofSunderland - duplicated notes fields

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#243]
Notes, these have been copied/migrated across twice from Rebus:List 1.

Example on LAC278 item 'storytelling as interaction' - this example also shows some information (author in this case) is not being migrated.

**Comment by fionaborthwick1** [comment]
This example is using the Entry template which does contain the line for csl-author.
<h5><csl-author></csl-author>

This is the link for RL1 - https://sunderland.rebuslist.com/list.php?list_id=11290

Bowles, Hugo, Storytelling as interaction in The Homecoming
in Language and Literature
Volume 18 Issue 1 (2009) Los Angeles: Sage Publications 
Pages 45 - 60 
Note: Log in with your University user ID and password to access this resource

**Comment by fionaborthwick1** [comment]
After talking with Ian and Leigh yesterday, I think that the issue with the duplicated notes has now been resolved as they have been doing some work with the material type templates.

However the missing authors are still an issue.

**Comment by fionaborthwick1** [comment]
Hi,
I am pretty confident that these issues have been resolved with one of your data reloads before your live migration.

If you find any missing authors etc then please log a ticket with the helpdesk quoting an example.

Many thanks,
Fiona
