### ISSUE TITLE
UniofSunderland - citation style

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#244]
Can the standard citation style be changed to Harvard in UniofSunderland instance - we were under the impression that there was to be only one style for the time being but that it would be harvard-ish and that developments on further styles were being considered.

**Comment by AndrewIsh** [comment]
Hi

You are free to choose any of the large number provided by CSL. Any easy way to locate styles is to use the [Zotero Style Repository](https://www.zotero.org/styles). Once you have located a style, you will need it's file name, this can be found by hovering over the style and looking at the URL it points to, for example:

`https://www.zotero.org/styles/harvard-the-university-of-melbourne`

in this example, the style name is `harvard-the-university-of-melbourne`

Once you have the name, this should be entered into the Global Preferences > "CSL Settings" tab > CSL citation style

I hope this helps. I'll close this issue. Feel free to re-open if you have further questions regarding this.

Many thanks
Andrew
