### ISSUE TITLE
Filtering items based on connector

### ISSUE THREAD

**Issue by fionaborthwick1** [PTFS-Europe/rebus-list-2#246]
Currently when a new item is added to a list a box appears giving the option to choose a source (box 1). Whichever source is chosen determines where the ‘Find item on the shelf’ button (box2) takes the user to, this means we could potentially end up with this button linking to either EDS or Prism for books and ebooks when in fact we want users to be directed to Prism for these items. To try and get round this is it possible for the local database (cat00941a) within EDS to be bypassed when searching which would mean the EDS option would not show if the item was a book or ebook as it wouldn’t be found in EDS.
Hope this makes sense?

**Comment by fionaborthwick1** [comment]
The box 1 and box 2 refers to screenshots sent on original email to myself. Box 1 basically shows the connector results screen with the results grouped by connector and box 2 is the reading list with the find items on shelf icon appearing at right hand side.

**Comment by fionaborthwick1** [comment]
So it would appear that all items are found on EDS but ideally Sunderland would like only Prism connector to be used for Books so that students are always referred back to the LMS.  Therefore they would like the EDS connector to exclude books and e-books.

**Comment by wl0lri** [comment]
Hi 
Until this work is completed would it possible to please change the wording on the buttons, so  Rebus:Connect – Library Catalogue would become Library Catalogue (use for books and e books) and Rebus:Connect -  Discover would become Discover (use for e journals).  
Thanks Leigh

**Comment by AndrewIsh** [comment]
Hi Leigh

I've changed your config now as requested. Unfortunately, we're not able to remove the `Rebus:Connect` prefix.

So the updated names will be:
`Rebus:Connect - Library Catalogue (use for books and e books)`
`Rebus:Connect - Discover (use for e journals)`

The change is not yet live, I will restart your instance later today which will enable the change.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
@a-sassmannshausen: Is it possible to filter out ILS sourced materials from the EDS connector as requested above? (I'm thinking the same has been asked of Summon too recently and would also be interested in an answer for that connector too)

**Comment by a-sassmannshausen** [comment]
Hello,
It might well be possible to do this.  It would require some development work, but could leverage existing work around advanced search: essentially what we need to do here, from the sound of it, is to set an "advanced search" criterion of "not books or ebooks".

Hope this helps,

Alex

**Comment by fionaborthwick1** [comment]
Hi,

It is my understanding that communication on this issue happened in email dialogue between yourselves and Alex and that you are now happy with how the connectors operate.

Thanks,
Fiona
