### ISSUE TITLE
Unable to manually add article

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#248]
Hi

I'm trying to manually add an article to a list but can't click into any of the fields in the Materials tab to edit them.  The Material Link URLs and Tags tabs are both fine.  I've tried a couple of other record types (book, book section) and they're ok.

can you take a look?
thanks
Helen

**Comment by janetc** [comment]
Hi Helen,
I'm not able to reproduce this I'm afraid. In the Material details tab in the Title detail section did you ensure you entered the title and publisher as these are mandatory? 
-Janet

**Comment by mrenvoize** [comment]
I saw this the other day but it miraculously disappeared when i tried to recreate it.. I think it was a caching problem somewhere.
