### ISSUE TITLE
Entering page range

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#250]
Hi

Is it possible to enter article/book chapter pagination as a range of pages rather than the start page, and total number of pages? 

Our EBSCO databases and Discovery service almost all use page ranges so at the moment only the start page is imported if we select records using the EBSCO connector.  This means that students don’t have any idea how long the article is, and as they have to include the page range when they cite papers in their essays and dissertations they would have to go off and check this every time rather than being able to rely on finding the correct information in their reading list.

Is this something that could be configurable for different sites if necessary? I did have a look at the material templates but didn't manage to get what I was after!

Thanks
Helen

**Comment by mrenvoize** [comment]
This is all to do with the CSL standard. We are standards compliant and are not intending to break from it in this area.

However, your connectors should be handling this transparently, importing no. of pages.

As for the templates being able to display as start and end, there no reason this shouldn't be possible and I believe it's one of the issues in the queue.

Citation wise, you have many thousands of styles to choose from to use in your system changeable via the system preferences.

**Comment by hloliver** [comment]
Thanks Martin - at the moment our EBSCO connector doesn't seem to be importing the number of pages - see screenshot below, this article is pp. 96-108 so we're not getting the page rage or the number of pages. Could someone take a look at this sometime?

![ebsco connector importing page numbers](https://cloud.githubusercontent.com/assets/12201255/19128039/76f7e964-8b39-11e6-8fc9-c46ccda1cf54.png)

If we can configure the templates to display the page range on the list that should keep the students happy!

Thanks
Helen

**Comment by janetc** [comment]
I attempted adding 
<span hide-if-empty> Number of Pages: <csl-number-of-pages></csl-number-of-pages></span> to the Article material template but this did not show pages. Will continue to investigate.

**Comment by mrenvoize** [comment]
@a-sassmannshausen could you investigate the EBSCO connector and it's mapping of pages ranges to csl fields 'first-page' and 'number of pages' please?

**Comment by janetc** [comment]
Polly has also raised this - "Page number ranges are not displaying. See List 25 “Wayland’s Smithy”. The start page only is displaying."

**Comment by AndrewIsh** [comment]
We have now added a new material template element `<csl-page-last>` which will display the last page of a page range if the material has both "start page" and "number of pages" populated.

It will be live on customer instances on 06/06/17

**Comment by hloliver** [comment]
HI Andrew

This doesn't seem to be working at our end - I've tried adding articles from different databases through our EBSCO connector, manually and from our Rebus:list local items but all I'm getting is either First page (EBSCO) or Number of Pages (Manually or Rebus:list local items.

The only time I've managed to get the page range displayed is when I entered an item manually and put the page range in the Misc tab under Page Number(s)

This list shows the various sources that I've tested, with notes for each item 

https://tavi.rebuslist.co.uk/#/list/2189

The manually entered items and rebus local holdings both have start page and number of pages populated, and I had understood from a conversation way back that this approach would pick up the last page from most of our EBSCO databases (one or two are a bit sketchy but we're expecting problems with those!)

Could you take a look?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Looking at the materials, it's clear that the EBSCO records only contain the `page-first` field, there is no `number-of-pages` field, it's therefore impossible for us to calculate and display the last page. Perhaps @a-sassmannshausen could look at what's being returned and see if the number of pages is made available by EBSCO?

For the item in the "Seminar 2" category, "From intersubjectivity to subjectivity: the transformative roles of emotional intimacy and imitation", you've noted "not displaying first page/last page, only number of pages". This is because you have not added the `<csl-page-first>` or `<csl-page-last>` elements to the material template for the Artcle material type. I just added those elements to the template and the page range is now displaying correctly.

The same applies to the item "Early interactions between infants and their postpartum depressed mothers" in your "Seminar 3" category. 

I hope this helps.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew

EBSCO does include the number of pages in most of its records, but doesn't always display in the public interface in the same way, and I guess different providers might hold the info in different fields - hopefully there will be a way to extract it!

![ebsco_no_of_pages-1](https://user-images.githubusercontent.com/12201255/26837859-5e5148e4-4ad6-11e7-9c10-2a1bfc86db82.png)
![ebsco_no_of_pages-2](https://user-images.githubusercontent.com/12201255/26837860-5e5b6838-4ad6-11e7-8099-63131f04bdfb.png)

Thanks for sorting out the templates for the manual entries - sorry, hadn't occurred to me to do that but will keep an eye out for future updates to templates as I can see that we would need to do this ourselves if we wanted to include the fields in our site.

Best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

OK, I'll speak to @a-sassmannshausen and see if the EBSCO API response is exposing these values, if so we should be able to pass them through to rebus:list

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

I've had a chat with Alex and he's now mapped the number of pages field into the EBSCO response that rebus:list receives. I've just tested it and it seems to be working well. So any newly added material that includes that field in the API response will now include it in rebus:list, and should display the page range if the material type template contains the `<csl-page-first>` and `<csl-page-last>` elements.

Give it a go and let me know what you think.

Many thanks
Andrew

**Comment by hloliver** [comment]
That's great - thanks both! 

I've tested on a few records from different databases in Discovery and it's working well.  

The only one that it isn't working is the PEP Archive, I'm hoping that the number of pages can be retrieved as it's the only one of our databases that doesn't display a page range to the end user, but gives first page and number of pages:

![ebsco-pep_no_of_pages](https://user-images.githubusercontent.com/12201255/26880246-b8485878-4b8b-11e7-9c63-f017f3f08c64.png)

Is there a way of including this in the page number mapping or is it a problem if it doesn't follow the same format as the other databases?

It would be great if there is a way to extract the page numbers though as it's heavily used in our reading lists. 

Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Alex has checked the response we're getting from EDS for that material and, unfortunately, we're not receiving the number of pages, just the first page number, so the `<csl-page-last>` element is unable to display. We can't account for why the number of pages is contained in the native interface display but not in the API response. If it's a problem for you, it might be worth you contacting EBSCO and seeing if they can shed any light on it.

Hope this helps.
Andrew

**Comment by hloliver** [comment]
Thanks Andrew, I'll take it up with EBSCO and get back to you if they're able to help
best wishes
Helen

**Comment by AndrewIsh** [comment]
OK, I'll close this for now. Feel free to re-open when you get a response from EBSCO.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew

I've had a reply from EBSCO about the API response from PEP Archive, the database doesn't flag the last page/number of pages - the only place this is included in the record is here, which is what's displayed in the public interface.

              <Data>&lt;searchLink fieldCode="JN" term="%22Journal+of+Child+Psychotherapy%22"&gt;Journal of Child Psychotherapy&lt;/searchLink&gt;, 2006; v. 32 (2), p122, 26p</Data>

Presumably this isn't any help to you? EBSCO are escalating this to their content team to make sure that they don't get this data from the database provider, and to see if it would be possible to get it in future, but to be honest I'm not holding out a lot of hope so think we'll have to write it off for now.

best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for the update on this. That's disappointing, fingers crossed EBSCO will have success in getting this data. I'll keep this issue closed for now, feel free to re-open if/when you get more info.

Many thanks
Andrew
