### ISSUE TITLE
Browse on homepage missing in Chrome

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#252]
Hi
No Browse option when Tavi homepage https://tavi.rebuslist.co.uk/#/ viewed in Chrome (see screenshot below), Firefox and Safari both ok

![browse missing in chrome](https://cloud.githubusercontent.com/assets/12201255/19385827/cb30b670-9208-11e6-8855-28a622bb098b.png)

can you take a look sometime
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

I can't replicate this, I've attached a screenshot of how things look in Chrome for me.

![image](https://cloud.githubusercontent.com/assets/9194223/19435251/8c2f0b06-9461-11e6-9cf0-10704fbee54b.png)

Can you please try clearing your browser cache and trying again, that should sort it out.

I'll close this issue, feel free to re-open if it continues to be a problem.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew, that worked, sorry should have tried that first!
bw
Helen

Helen Oliver

Systems Librarian
Tavistock & Portman NHS Foundation Trust
Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.uk
