### ISSUE TITLE
'Find items on shelf' missing from items selected from Koha connector

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#254]
Hi

I've just created this list https://tavi.rebuslist.co.uk/#/list/2032 selecting most of the items from the Koha connector results, but these aren't displaying the 'Find items on shelf' icon

So far the only record which is showing the icon is a journal article selected from the EBSCO connector results (Anderson, The reflecting team...)

can you take a look at this?
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for this. Looking at the list, it looks as though some of your material may need refreshing. We introduced some improvements to material linking fairly recently, some material will not contain these changes. I'll ask Martin to resync your data, which will add these changes to your data. I'll let you know once this is done.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew
bw
Helen

Helen Oliver

Systems Librarian
Tavistock & Portman NHS Foundation Trust
Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.uk
