### ISSUE TITLE
Chapter titles repeated for records in 'local items' connector

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#256]
Hello

When importing a chapter record from the local items connector the chapter title is repeated:

![chapter titles repeated from local collection](https://cloud.githubusercontent.com/assets/12201255/19571060/80bb33b8-96f4-11e6-99bf-59db1a60e750.png)
![chapter titles repeated from local items](https://cloud.githubusercontent.com/assets/12201255/19571059/80bb5c6c-96f4-11e6-8c29-551695957826.png)

can you look into this?
thanks
Helen

**Comment by janetc** [comment]
Hi Helen,
I've fixed this - the layout of the Book Section template in the Material Type Templates had lines adding the title as a link, and also the title as plain text.
I just removed the part for title as plain text in the Book Section template. 
<span hide-if-empty><csl-title></csl-title></span>

Best wishes,
Janet
