### ISSUE TITLE
Hide if empty not working

### ISSUE THREAD

**Issue by wl0ifr** [PTFS-Europe/rebus-list-2#260]
We are looking at the Book template which contains this line

`<h5 hide-if-empty><csl-author></csl-author></h5>`

This fails to return the author of my book, however editing the line to

`<h5><csl-author></csl-author></h5>`
the author displays

**Comment by mrenvoize** [comment]
Sorry, I'm not sure if there was a mistake in a copy/paste there.. the two lines quoted look the same to me. Could you clarify please?

**Comment by mrenvoize** [comment]
I'll get @AndrewIsh to look into this, we've not come across it anywhere else so far but will look into it.

Thankyou for your report.

**Comment by AndrewIsh** [comment]
Hi @wl0ifr 

Thanks for the report, I'll investigate. Can you please let me know what customer you belong to?

Many thanks
Andrew

**Comment by wl0ifr** [comment]
Hi Andrew, sorry University of Sunderland, this is was the list I was working on
https://sunderland.rebuslist.co.uk/#/buffer/12745

**Comment by AndrewIsh** [comment]
Hi Ian

I've just looked at your book template and notice that you're not closing your `<h4>` tag on the title line, that may be causing hide-if-empty to get confused, can you please try closing the tag and see if you continue to have problems.

Many thanks
Andrew

**Comment by wl0ifr** [comment]
Hi Andrew,

I've closed the tag, however when I add "hide-if-empty" to the <h5> no author is displayed.

Ian

**Comment by AndrewIsh** [comment]
Hi Ian

Thanks for that. I've taken a look and it appears to be a bug. I'll create an internal issue and try and get it addressed shortly.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Ian

I've just completed a fix for this issue. It should be pushed out to customer instances with our next bug fix release. I'll leave this issue open until that has happened and you have confirmed it fixes the issue you're seeing.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Closing
