### ISSUE TITLE
List with sublists only works in public view if it has items as well

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#261]
A list with sublists can only be opened in public view (not logged in) if an item (ie book/article) is added to the main list as well as the sublists 

ie see Block 1 October https://tavi.rebuslist.co.uk/#/list/2050
if not logged in as admin, I can navigate to the list but can’t open it.  If I'm logged in as admin I can navigate to it in the public view and open it.

Can you take a look?

Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Can you please elaborate? I just viewed the list as an unauthenticated user, and was able to view the sublists the list contains. See screenshot below.

Many thanks
Andrew

![image](https://cloud.githubusercontent.com/assets/9194223/20051199/b06a53a8-a4c5-11e6-843a-38ad34d83077.png)

**Comment by hloliver** [comment]
That's odd - it's working now! I noticed it with this list, and with a couple of others that I created a couple of weeks ago - I tested it out on different computers at work and home, and different browsers but the only way I could open the main list when unauthenticated was to add an item to it as well as sublists.
Will let you know if I see this behaviour again
Thanks
Helen

**Comment by AndrewIsh** [comment]
OK, that is indeed very odd! I'll close this issue for now but by all means re-open it if you see the problem again.

Many thanks
Andrew
