### ISSUE TITLE
Renameing sublists

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#262]
Hi
I can’t find a way to rename sublists – you can’t seem to do it within the sublist itself, and sublists aren’t visible when you go to Manage Hierarchy.  

Also as sublists don’t appear in the hierarchy you can’t move/clone them (haven’t come across the need to do either of these yet, but haven’t worked through all of the instances where we might use them).

Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this, I'll create an issue and investigate.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Sublist renaming is clearly a bug and will be fixed imminently and released in one of the next two bugfix releases (14th or 21st February 2017).

Regarding Cloning/Moving sublists to other container lists that would be an enhancement request.  We need to understand a clear use case for this before moving further with it.  I'll create another issue to track progress on that front.

**Comment by AndrewIsh** [comment]
Hi Helen

Just to note that sublist renaming is now possible via the same mechanism we have added for renaming regular lists, the "Edit list metadata" button in the list view will allow this. See here for more details: http://rebuslist.readthedocs.io/en/latest/editing_reading_lists.html#editing-list-metadata

The cloning/moving sublists has been created as a separate issue and is marked as an enhancement request.

I'll close this issue. Feel free to re-open if you still have questions.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew



Re moving/cloning sublists - we haven't spent too much time on sublists yet, it will be a major change for the way that our lists are organised.  Is anyone else using them? We don't want to generate a lot of work for this if we're the only ones who would potentially want it and haven't committed to it ourselves yet!

Helen
