### ISSUE TITLE
Inaccuracy in Book Section template

### ISSUE THREAD

**Issue by fionaborthwick1** [PTFS-Europe/rebus-list-2#264]
From University of Sunderland:

In the template adding the line  as below displays the message as ‘Read 19 pages starting at page 10’ . Ideally we would like the programme to calculate the number of pages as it seems to do on RL1 and read ‘Pages 10-29’. Is this a change that can be made? 
<h4><csl-container-title rebus-linkify></csl-container-title></h4>
    <h5><csl-author></csl-author></h5>
    <h6><span hide-if-empty><csl-issued></csl-issued></span> <span hide-if-empty><csl-edition></csl-edition></span></h6>
    <h4><span hide-if-empty>Chapter: <csl-chapter-number></csl-chapter-number>.</span> Read <csl-number-of-pages></csl-number-of-pages> pages starting at page <csl-page-first></csl-page-first></h4>
    <p><csl-type></csl-type></p>
    <rebus-collapse expand-text='+Citation' collapse-text="-Citation" element-class="panel panel-default" heading-class="expand-collapse panel-heading" body-class="panel-body">
        <p hide-if-empty><rebus-citeproc></rebus-citeproc></p>
    </rebus-collapse>
</div>

![image](https://cloud.githubusercontent.com/assets/1167777/20060847/090148da-a4f5-11e6-97d5-ac25c5e117c3.png)

**Comment by fionaborthwick1** [comment]
Discussed at meeting yesterday - this is really quite an important issue for Sunderland.

**Comment by mrenvoize** [comment]
Another bit of polish that's been on the list for months but we've not had the time to get to.

**Comment by AndrewIsh** [comment]
We have now added a new material template element `<csl-page-last>` which will display the last page of a page range if the material has both "start page" and "number of pages" populated.

The desired display could be achieved by using the following template:

```
<div hide-if-empty>
    Pages <csl-page-first></csl-page-first>-<csl-page-last></csl-page-last>
</div>
```

It will be live on customer instances on 06/06/17

**Comment by AndrewIsh** [comment]
Closing
