### ISSUE TITLE
Search for material - alternative versions

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#267]
Hi 

When an item is added as an alternative version, the second item doesn't appear in the "Search for materials" area. 

In the list display there is a book and eBook:

![search for material](https://cloud.githubusercontent.com/assets/17139950/20174566/5968ae2e-a736-11e6-9ef3-8363ed16cab7.JPG)

but when searching for the book "Descriptive physical oceanography: an introduction" only one is returned. Can you have a look?

Thanks

Richard

**Comment by mrenvoize** [comment]
I wondered whether someone might spot this. I'm aware of this one and need to find some time to dig into how to accomplish it.

Thanks for the report,

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#2132

**Comment by mrenvoize** [comment]
Fixed upstream, this will roll out on Monday night assuming it passes our internal quality assurance tests over the weekend.

Thanks @richughes
