### ISSUE TITLE
Problem with "view lists that use this material"

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#268]
Hi

In the Search for Materials area, when I click "view lists that use this material" I get a blank screen, it doesn't list any modules. I've tried various items and the screen is always empty. A book to try is:

"Descriptive physical oceanography: an introduction "

I'm not sure when this stopped working. I'm on the latest version of Firefox. 

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for drawing our attention to this. We have now produced a fix for this. It will be rolled out to customers during our next scheduled upgrade next Monday night (14th).

I'll close this issue, if you encounter further problems with this, don't hesitate to re-open this issue.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
I've now done some additional fixes API side to account for equivalent and alternative materials that appear on lists. The api calls before these fixes were not properly taking account of these.
