### ISSUE TITLE
APi not returning course ID

### ISSUE THREAD

**Issue by wl0ifr** [PTFS-Europe/rebus-list-2#270]
Hi,

I (well Capita Libraries) are using a couple of APi calls to return list information for an item.

The item is
https://capitadiscovery.co.uk/sunderland-ac-sandbox/items/66353

This calls
https://sunderland.rebuslist.co.uk/api/materials/?search=0749730242
to get information about the material, in-particular the material ID

Which calls
https://sunderland.rebuslist.co.uk/api/lists/?has-materials=29856
to get list information from the material ID.

The problem is that the second API has a null value for course_identifier despite it being in the list.

This is what is returned by the API
`[{"after":11286,"course_end":null,"course_identifier":null,"course_start":null,"id":12394,"material_count":44,"name":"Test List 2016-17","parent":13124,"public_note":null,"source":"SUNDERLAND","summary":null,"type":"list","year":null}]`

As you can see course_identifier is null.  however that field is populated see picture

![screen shot 2016-11-14 at 10 02 25](https://cloud.githubusercontent.com/assets/22322736/20260557/20436192-aa52-11e6-9137-a405ec6f54ff.png)

Can you help with this, thanks

**Comment by mrenvoize** [comment]
I'm investigating this one for you now.. It looks like a bug has crept in during the last update, I'll write a test to ensure it doesn't creep in again.

Martin

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#2142

**Comment by mrenvoize** [comment]
I've not corrected this in master, providing it passes our Quality Assurance this afternoon, it will get pushed out to customers this afternoon during our next scheduled release window.

Thanks for pointing this out, 

Martin
