### ISSUE TITLE
Manage Materials - Templates for display

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#272]
The 'Manage Materials' search results display is currently a rather flat table with an abstract set of fields in display.  We should use the public list display templates to display the search results instead to give a much better reflection of what users see.

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#2147

**Comment by AndrewIsh** [comment]
Definitely agreed. We use the user defined templates everywhere else, it should be used here too. Should be relatively easy to implement.

**Comment by AndrewIsh** [comment]
This is now available. Closing.
