### ISSUE TITLE
API returns labels with hyphens rather than underscores

### ISSUE THREAD

**Issue by wl0ifr** [PTFS-Europe/rebus-list-2#277]
Hi,

We are using some of the APis to display RL2 in our VLE, however the labels use a mixture of underscores and hyphens.

For example, in_stock & owner_uuid use underscore and container-title & number-of-pages use hyphens.

When our web developer tries to use the values returned by the fields labelled with a hyphen it's being treat as a mathematical equation, i.e. minus.

Would it be possible to have consistency and only use underscores?

Thanks
Ian

**Comment by AndrewIsh** [comment]
Hi Ian

The properties you mention, `container-title` & `number-of-pages` are properties of the `metadata` object and are defined by the [CSL schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json).

I'm not sure how your developer is making use of the properties, but I'm perplexed as to why the values would be treated as a mathematical equation. Is it possible to get more details?

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Indeed,  I'm not currently aware of any json parser that would make that kind of mistake.

I'm afraid as csl is an external standard that we've adopted, we're not likely going to be able to persuade them to change that. 

As Andrew says, could you give us any more context so we could offer some advice?

**Comment by wl0ifr** [comment]
Hi Both,

Ive asked our web developer to respond, or send me his response to post.  Will update ASAP.

Ian

**Comment by wl0ifr** [comment]
Update from our web team

Hi,

Thank you for your comments.

We weren’t originally aware that you were using the CSL schema, hence the original question Ian kindly posted for us.  However, as you are using the CSL standard then obviously this isn’t really changeable, which we do appreciate.

I am pleased to say that after a fair amount of trail and error I have now been able to solve the problem.  To put the original issue into context and in case it helps others, here is an overview of how we are trying to use the data.

We are using PHP to interact with the Rebus:List v2 APIs and render the information to the end-user.  Once the data has been retrieved from the API it is ran through PHP’s “json_decode()” method to convert the JSON string into an associative array.  Whilst we could access the JSON data directly and render the output accordingly, we needed to perform the conversion because we are using the Smarty tempting engine for easier maintenance in the longer term.  The template engine appears to only have support for numerical and associative arrays rather than JSON.  The hyphen problem is isolated to Smarty as we have had similar problems in the past with other hyphenated keys in JSON data using PHP, as I will now explain.


In ordinary PHP you can access the object key as:-

$object->myKey

or even:-

$object->my_key

However, when the key contains a hyphen, e.g. “my-key”, PHP seems to have a problem parsing the accessor and gets:-

$object->my

missing the “-key” part or interpreting “-“ as another instruction such as subtraction.  Therefore you have to use a workaround for it to be parsed correctly:-

$object->{'my-key’}

or

$object->{“my-key”}

This then works perfectly and you can then use the accessor.



For Smarty you access the key/values in similar fashion but with decimal separators:-

$object.key

or

$object.with.further.dimensions.key


You can use camel-case and underscores in the accessor such as:-

$object.myArray.my_key


The accessors need to be used within “Smarty tags” which are curly braces.  The Smarty tags can either be functions such as “if”, “foreach” etc., or property accessors to display the values.

I tried various combinations of the above workaround with the Smarty tags but all to no avail.  My attempts have included:-

$object.my-key
$object.'my-key’
$object.{‘my_key’}
{‘$object.my-key’}

The problem with the above is the curly braces were treated as additional Smarty tags.

It seems that you get:-

$object.my

but not the “-key” part, or it tries to subtract “key” from “$object.my” in a mathematical equation, which is what has been noticed with the above PHP problem.  However, the solution was to wrap the hyphenated key with curly braces and double quotes:-

$object.{“my-key”}

This also works for multidimensional arrays/keys, such as:-

$object.{“with-a-hypenated”}.{“multidimensional-array”}.key

Interestingly this is the only working solution as single quotes don’t work correctly, as previously described, though they do for ordinary PHP!


I originally conducted some internet searches and people have been encountering similar problems at both PHP and Smarty, thus have recommended the avoidance of hyphens in key names especially in PHP as they can be misinterpreted as subtraction statements.  This is why the original question was raised but as you are using a standard then this isn’t something easily changeable.

Whilst the problem is now resolved, this has been a learning curve and I hope our experiences will help others if they encounter the same problem.

Best regards,
Web Team

**Comment by AndrewIsh** [comment]
Thanks very much for the background on this, very interesting. It seems that the issue has now been resolved, so I'll close this, feel free to re-open if you encounter further problems with this.
