### ISSUE TITLE
ISBN is not validated

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#279]
We should validate ISBN'S as they enter rebus:list. 

Many come through with a type appended,  we should strip this before final validation and perhaps add the field to the 'fixed' array in those cases

**Comment by mrenvoize** [comment]
We should validate ISBN'S as they enter rebus:list. 

Many come through with a type appended,  we should strip this before final validation and perhaps add the field to the 'fixed' array in those cases

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#2158

**Comment by AndrewIsh** [comment]
A fix for this has been released - closing

**Comment by mrenvoize** [comment]
I don't remember if this was also applied at the serverside validation level
