### ISSUE TITLE
Error 3 - publishing list updates

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#28]
List https://preview.rebuslist.com/#/list/13
Stopped using preview when error message displayed.  Was adding tags to list.  Before this list edit had signed on as np_admin made one edit to the same list, published list, accssed manage tags module, added tags, then to list edit then publish - error message.

**Comment by NickPhipps** [comment]
np_admin / npa_bilbo

**Comment by mrenvoize** [comment]
Think I've finally nailed this one.. or at least I can reproduce it consistently on the _master_ development branch now.

Just discussing with @AndrewIsh how to fix.

All tied to PTFS-Europe/rebus-list#819 on the tracker

**Comment by AndrewIsh** [comment]
Fixed some time ago, closing.
