### ISSUE TITLE
Published units/lists not displayed in public view

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#281]
Hi 
I've been playing around with the hierarchy and have set up a new top=level unit with sub-units and  lists, however although these are all displayed in the admin view, some are missing in the public view.
I have checked that:

1. All units/lists are published (see screenshot 1)
2. They don't have start dates in the future (I only added the unit/list title and module code, no other settings were changed)
I've also cleared my browser cache in case that was the problem

It screenshots below you'll see that the admin view shows Units for Year 1 and Year 2, each with 3 lists, but the public view only shows Year 1

Can you take a look?
thanks
Helen

Admin
![hierarchy_-_admin_fpp_y1_and_y2_published](https://cloud.githubusercontent.com/assets/12201255/20931680/c245f9d6-bbc9-11e6-95a3-003549575de2.png)

Public
![hierarchy_public_view_-_fpp_only_y2_displayed](https://cloud.githubusercontent.com/assets/12201255/20931691/d12147f8-bbc9-11e6-925c-10e9b7cec591.png)

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this. I've done some investigation and it appears that those lists believe they are suppressed when they are not. I've created an internal issue and will discuss with @mrenvoize to try and figure out what's going on. I'll get back to you when we've looked into it.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew - these lists are showing now! Did you manage to find out the cause of the problem or is it still a mystery? I've been playing about the hierarchy today - love being able to clone whole branches, that's going to make life a lot easier!
Helen

**Comment by mrenvoize** [comment]
I believe we've gotten to the bottom of the problem now and I've written a patch to fix it. 

I have not, however, rolled this onto any customer servers as yet and won't be doing so until our next update window (Monday Evening before the Tuesday morning JISC at risk period as per our current release scheduling promises)

It was a slightly obscure bug in that the problem could easily seem to go away of its own accord when working on the hierarchy publishing and unpublished lists; So this may be why you're finding lists are all appearing as expected again.

I will be running a check on databases as part of the fix to ensure they are in a consistent state.

Thanks for the report, 

Martin

**Comment by hloliver** [comment]
Thanks Martin - that explains a few other occasions where we thought we'd seen this happening, but the lists would reappear before we had a chance to log it!

**Comment by hloliver** [comment]
Hi - coming back to this after a bit of a break, but still seeing the same problem ie only Year 2 lists are displayed for the Forensic psychodynamic psychotherapy course unless you're logged in, in which case you can see Year 1 as well.

We now have the added bonus of having a duplicate top-level unit in the hierarchy (Tavistock and Portman Library - new hierarchy) which I don't _think_ I created! I'm wary of deleting one of them in case they both go.

best wishes
Helen

**Comment by hloliver** [comment]
Sorry, have just done something really stupid! 

Trying out moving items around in the hierarchy and used Forensic psychodynamic psychotherapy course by mistake, so if you're trying to replicate the issue above can you look at the second top-level hierarchy called "Tavistock and Portman Library - new hierarchy" which hasn't been affected by the changes that I made.

Thanks
Helen

**Comment by mrenvoize** [comment]
As far as I can see all lists are displaying as expected by the system now.. Suppressed lists are suppressed and inheritance is being carried down the hierarchy.  Validity dates are being respected and inheritance of this is also working.

I'm going to close this one, but feel free to open a new issue if you are finding your still having problems.
