### ISSUE TITLE
Search for material - no results when searching for author/book title for book chapter records

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#284]
Hi - the Search for Material feature isn't finding chapters when you search for the book's author or title.  In the example below I omitted to enter the author of the chapter, so searched for the record to edit it, no results for Wilson, or 'child-focused' so had to search on isbn to find it
Helen

![searching for book section - no results for author or book title only isbn](https://cloud.githubusercontent.com/assets/12201255/21007914/2e93a73c-bd37-11e6-9067-d5076fa84260.png)

**Comment by AndrewIsh** [comment]
Hi Helen

This is a known issue, we've a fix worked out, it should be implemented before very long. I'll update this issue once it is implemented.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
The fix for this will be going out tonight.
