### ISSUE TITLE
Can't change unit title

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#285]
Hi

I can't change the title for one of the units - when I edit the title field and save it the red error box appears, it then looks as if the update has been accepted and the new title is displayed in the hierarchy, but reverts back to the old title after the page has been refreshed.  

http://screencast.com/t/KwoE1eu5r5 - short video here shows what happens when I try to change a unit called 'Event Planning' to 'Observation in an Organization'

Is this because the unit was cloned? If that is the reason is it intentional, or something that will be enabled in the future?

Thanks 
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this. It appears to be a bug, you certainly should be able to edit them. I've created an internal issue and will investigate.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

This should now be fixed.

I'll close this issue, if it continues to be a problem, feel free to re-open.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew, all looks good now.

Thanks also for the feedback on the other issues

best wishes

Helen


Helen Oliver

Systems Librarian
Tavistock & Portman NHS Foundation Trust
Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.uk
________________________________
