### ISSUE TITLE
Manage User Roles from Hierarchy/List Pages

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#286]
With the user privileges re-write we lost the ability to view and alter users roles from the manage hierarchy page.  We hope to bring this back shortly along with adding the ability to make such changes directly from the list draft pages for users with the given permissions.

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#2224

**Comment by AndrewIsh** [comment]
A fix for this has been released - closing
