### ISSUE TITLE
Adding entry - local catalogue result list displays 'blanks'

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#29]
List : https://preview.rebuslist.com/#/list/38
search 'chemistry acid' 
local catalogue result set 
![capture](https://cloud.githubusercontent.com/assets/10532724/8431063/a820bff2-1f2e-11e5-996b-0868e4b0d6e3.JPG)
Tries this search 3 times - same result. 
Selecting one of these  blank items doesn't add an entry.
Copac result set OK
Tried other searches, they worked OK (including add and publish).  

Nick

**Comment by NickPhipps** [comment]
It doesn't seem to be 2 word searches - tried 'black holes' that worked OK.

**Comment by mrenvoize** [comment]
Created issue in the main tracker as I can replicate this: PTFS-Europe/rebus-list#871

**Comment by AndrewIsh** [comment]
Fixed some time ago, closing
