### ISSUE TITLE
Can't add items to list from local holdings

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#294]
Hi
I can't add items to a list from the Local Holdings - once I have selected an item and hit Finish the search box closes but no items are added to the list. After a few seconds the 'No error details received from the server' message appears at the bottom of the page.
If I try to add the item again I get an error telling me that this item already exists in the list.
Here's a video:
https://www.screencast.com/t/i3m8vgGSw

can you take a look
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for the video. I'll try and replicate your actions on the list you're working on. Let me know when you're finished editing it and I'll investigate.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew - this is the list https://tavi.rebuslist.co.uk/#/list/2334

After I opened the call I managed to add several local items to seminar 5 (I was curious to see whether all items were affected or just particular record types - I was able to add articles and chapters this time)

Helen

**Comment by AndrewIsh** [comment]
OK, so are you seeing this problem on any items now?

**Comment by hloliver** [comment]
No - I've just tried on a new list and all worked fine, it happened several times when I originally tried though.  I'll let you know if it happens again.
Helen

**Comment by AndrewIsh** [comment]
OK, great, thanks for letting me know. I'll close this, re-open if it happens again.
