### ISSUE TITLE
Export references

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#296]
Is there going to be an option for students to export the list's references like there is in RL1?

I couldn't see anything about this in any of the documentation but it's a really popular feature with our students and is always the highlight of their Endnote training sessions!

Helen

**Comment by mrenvoize** [comment]
Yes, it's in the development plan.. I believe the target date is before May 2017, but it may well come long before this.

**Comment by hloliver** [comment]
Excellent, that should keep them all happy!
Helen

**Comment by AndrewIsh** [comment]
Closing

**Comment by AndrewIsh** [comment]
Just to update, this is due for release next Tuesday 04/07

**Comment by hloliver** [comment]
Hi Andrew
Just seen that it's now possible to export individual items which is great - are there plans to add this feature for the whole list? Our students are encouraged to export their entire set of reading lists into Endnote/Mendeley and found the option to do this in RL1 incredibly useful and a great timesaver.
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for the feedback. We are planning to add the ability to export more than single items, I'll update this issue once this has been implemented.

Many thanks
Andrew

**Comment by hloliver** [comment]
That's great, do you have a rough idea when this is likely to be available??

**Comment by AndrewIsh** [comment]
Hi Helen

Unfortunately not at the moment. We need to discuss how this fits in with other development priorities and schedule it accordingly. I'll let you know once we have a date on it. Sorry I can't be more specific at the moment.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew, good to know that it's in the plan. 

What would be nice would be the option to select all items, _and_ select multiple items.  Quite often you might want to export several reference but not the whole list; with RL1 you would either end up with the whole list and you would need to remove unwanted items after importing them into a reference manager, or you would have multiple files files to upload.  Not the end of the world, but it would be nice to make your selection in RL2 and just have one file to import  - I don't know if that would be possible here?

**Comment by AndrewIsh** [comment]
That certainly sounds like a sensible approach. I'll add that functionality to the spec.

**Comment by hloliver** [comment]
Thanks!
