### ISSUE TITLE
Problem adding book section

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#298]
Hi
I've been having problems adding book chapters from our Discovery results (this feature isn't working for us on Koha at the moment)

When I was working on this list https://tavi.rebuslist.co.uk/#/list/2334 and searched to add a new item, nothing at all happened when I selected 'Add to list as...Book section' 

I tried on another list (https://tavi.rebuslist.co.uk/#/list/2337) and this time the book section window opened but the 'Material details' fields were missing and the only area that could be edited was the 'Material links URLS'

Here's a video https://www.screencast.com/t/3jvsrv55ViH

I tried on Chrome and Safari, and cleared my browser history but the problem still occurred.
can you take a look?
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for reporting this. I've been able to replicate the problem and will investigate and get back to you.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

A fix for this has just been pushed out to your instance. I'll close this issue, feel free to re-open if it continues to be a problem.

Many thanks
Andrew

**Comment by hloliver** [comment]
All good now – thanks Andrew
