### ISSUE TITLE
Tags - hard to read & no uppercase

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#30]
The font size and style makes tags hard to read.  Also it is not possible to use uppercase, which might be necessary on occasions.

**Comment by AndrewIsh** [comment]
Hi Sharon

Happy to modify the appearance of the tags. We made a conscious decision to force lowercase on all tags though. Can you please elaborate on when this would be problematic?

Thanks
Andrew

**Comment by SharonCocker** [comment]
Hi Andrew,

For us lowercase only tags would be a problem as lecturers often request 
items to be tagged with subjects containing proper nouns, such as author 
names or place names.    We really need to be able to use uppercase 
otherwise, as a library, we would be setting a poor example to our 
students - plus I'm sure our academics would pull us up on it!

Many thanks,
Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by SharonCocker** [comment]
Hi Andrew,

Just wondered if there was any updates about using uppercase for tagging?  Sheffield mentioned it to Nick Phipps when he last visited as it would cause us a real problem if we could only use lowercase. 

Many thanks,
Heather

**Comment by AndrewIsh** [comment]
Hi Heather

Myself and @mrenvoize have been discussing it. We can definitely see your point. Our main concern is trying to eliminate duplication of tags as much as possible. Converting to lowercase is a technique used widely as a method of eliminating one source of duplicates. However, case is clearly important to how you (and I suspect others) intend using tags, we're therefore going to remove the lowercase restriction. This change will be made soon and I'll update this issue when it has been done.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
In progress: https://github.com/PTFS-Europe/rebus-list/issues/1402

**Comment by AndrewIsh** [comment]
Hi Sharon

This is now done. Both uppercase and lowercase tags are allowed. In an attempt to reduce duplication, it is not possible to enter a tag which contains the same letters but in a different case. For example, if the tag "Drama" existed, it would not be possible to create a tag "drama".

Preview will be updated with the patch shortly.

Thanks
Andrew

Closed in https://github.com/PTFS-Europe/rebus-list/pull/1404
