### ISSUE TITLE
Manual entries - error message

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#302]
Hi 

When adding manaul entries, even after the mandatory fields have been added, the red error box remains visible.

![manual entry error](https://cloud.githubusercontent.com/assets/17139950/22329135/bdedd0c8-e3b7-11e6-906e-1507fac7e1c3.JPG)

It is possible to save the entry and add it to a list, but it's confusing for users as they still think there is a problem with their form data and don't bother trying to save it. 

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for reporting this. It's clearly a bug, I'll create an issue and get a fix done ASAP.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Pretty confident this is now resolved, but please re-open if I'm incorrect.
