### ISSUE TITLE
Adding book chapter – invalid data error doesn’t disappear

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#303]
Adding a book chapter – invalid data error doesn’t disappear even when the required fields are in the record, though I can save the record despite this:

https://www.screencast.com/t/E8KAHEHjExcO 

On a related note, it would be nice if the results list indicated that the book had been selected after you complete the chapter record - at the moment it’s still green so it looks as if you haven’t selected any records.

Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for reporting this. It's a bug and has also been reported in #302. I'll create a fix ASAP.

As for your second point, that's a very interesting suggestion and makes a lot of sense. I'll create an enhancement issue and look at how this could be implemented.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Bug fix rolled out 31st January 2017, Enhancement moved into own issue: #310

**Comment by hloliver** [comment]
Hi - we're still seeing this error!
