### ISSUE TITLE
Backwards navigation lost

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#304]
I’ve been looking at how we want to arrange our lists using the hierarchy and it’s occurred to me that from the students’ viewpoint it will be fairly straightforward to navigate to the lists that they want, but if they change their mind, or want to go back to look at a different module there isn’t a way for them to navigate back to it.

As our courses are becoming more modular the example in the video is probably fairly typical – and once the students have got to their Theory lists there isn’t an obvious way back to look at the rest of their Year 1 lists unless they decide to open the list and use the breadcrumb trail:

https://www.screencast.com/t/BdCd05GF 

For the most part we will try to link the students directly to their year group’s lists, so it won’t be quite as bad as it is in the video, and I realise that expanding the hierarchy would make it easier than clicking on it the unit title, but I would be very surprised if most of our students approached it that way! 

Is there a way of adding a way of navigating back up a level?

Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

The browser's "Back" button should allow users to navigate back up the hierarchy in the way you describe, are you not finding this is the case?

Many thanks
Andrew

**Comment by hloliver** [comment]
Hello Andrew

It's fine if the user is consistent in the way that they navigate to the list ie 

- always clicking on the unit title - the browser's back button works
- or always using expanding the units - they can see where they are anyway

However if they do a mixture of both then the back browser jumps back to the last time that they clicked on a unit title so they may miss out a couple of units that fall in between
https://www.screencast.com/t/6xC8obLo

Our users are predictably inconsistent so are very likely to click on the title/expand in a fairly random way!

I noticed a similar issue watching a student who was viewing a list, and then clicked on a unit a couple of levels higher up in the hierarchy which left them a bit stuck as they couldn't get back to the rest of their Year 1 lists
https://www.screencast.com/t/catgIiZ2Cyf

So an option to navigate back up to the previous level in the hierarchy, similar to that in RL1 would save a lot of confusion:
![rl1_back_navigation](https://cloud.githubusercontent.com/assets/12201255/22372562/6643f74c-e495-11e6-9f58-ccce69ecf8c2.png)

Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for that. Yes, that's a very good point. I'll create an issue to provide a persistent link on the Browse page that always goes to the next level up in the hierarchy.

Many thanks
Andrew

**Comment by hloliver** [comment]
Great that will definitely help our users out, thanks Andrew

**Comment by mrenvoize** [comment]
Expected: February 28th Release

**Comment by AndrewIsh** [comment]
A fix has just been completed for this, it will be rolled out in this coming Monday's (22nd) update. I'll close this issue, if it continues to be a problem, feel free to re-open.

Many thanks
Andrew
