### ISSUE TITLE
Rollover problems - 'Hierarchy is locked whilst inheritance is recalculated'

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#309]
Hi

This is related to #290 

I've just had another look at the rollover but now getting this message and can't make any changes to the hierarchy at all! I've waited for about 20 mins to see if it really was recalculating but assume now that it's got stuck - can you unlock it for me?

![rollover_-_hierarchy_locked](https://cloud.githubusercontent.com/assets/12201255/22733011/381290ca-ede8-11e6-8d2d-e771a60d12d1.png)

Thanks
Helen

**Comment by janetc** [comment]
Hi Helen,
Martin has unlocked the hierarchy for you now. Some rollover fixes have also been applied which may address some of the other rollover issues reported. I'll be testing that in due course.
-Janet

**Comment by hloliver** [comment]
Hi - just trying the rollover again on a single list (no sublists/child lists) but getting the same message 'Hierarchy is locked whilst inheritance is recalculated'. It's been about 10 minutes so assuming that it's stuck again.  

Can you unlock it asap as I'm working at home on RL2 today so this is causing problems!
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Martin has now unlocked the hierarchy, apologies for the inconvenience.

Many thanks
Andrew
