### ISSUE TITLE
Suggestion - scroll button

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#31]
The current icon used for the 'scroll button' was no obvious to users - perhaps it could be altered to a different icon? (please see attached screenshot) 

![button problem - scroll icon](https://cloud.githubusercontent.com/assets/12249067/8694711/af55b524-2ad8-11e5-8fcf-3eed1dd4a61a.png)

**Comment by AndrewIsh** [comment]
Hi Sharon

Thanks for that. Very good point, will do.

Cheers
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/908

**Comment by mrenvoize** [comment]
Actually I think that alternate button is more misleading personally, makes one think you can move items side to side (which of course you can't ;) ).

Perhaps a better hover text hint might be more appropriate?

**Comment by AndrewIsh** [comment]
Sharon's icon suggestion was adopted some time ago. I'll close this issue.
