### ISSUE TITLE
Changes to list/unit metadata needs refresh to take effect

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#317]
Making changes to list/unit titles needs the page to be refreshed before the changes take effect - screencast below shows that I added 'Portfolio' to the end of the titles of 2 units, but this wasn't displayed until I refreshed the page.

https://www.screencast.com/t/4ecTC6maLPy

I've only noticed this today so it's a fairly recent issue.  I've tried clearing my browser cache in case that was causing problems but it hasn't made any difference

can you take a look?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for that. You're right, it appears to be a bug that was introduced with the last update. I've just fixed it. It will be pushed out to your server with the next update.

Many apologies and thanks for reporting it.

Andrew

**Comment by hloliver** [comment]
Thanks Andrew!

**Comment by AndrewIsh** [comment]
A fix for this has been released - closing
