### ISSUE TITLE
Suggestion - Find Item On Shelf button

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#32]
The 'lightening' icon currently for the 'Find Item on Shelf' button is not clear to users - could a different image be used instead?  (please see attached screenshot)

![button problem - find item on shelf icon](https://cloud.githubusercontent.com/assets/12249067/8694869/bc2e3b76-2ad9-11e5-89f5-eb6c75a9532e.png)

**Comment by AndrewIsh** [comment]
Hi Sharon

Thanks for this suggestion. Following similar feedback from others, we actually intend replacing it with the icon that is currently used in RL1.2, we've just not done it yet :)

Cheers
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/723

**Comment by AndrewIsh** [comment]
This is now done
