### ISSUE TITLE
List keeps refreshing

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#320]
Hi - bit of an odd one today

A list that I created a while ago continually refreshes, 

https://tavi.rebuslist.co.uk/#/list/3980

https://www.screencast.com/t/xjfyakOs6Kj 

The other lists in that unit are fine - can you take a look
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Could you please empty your browser cache then reload the list?

Many thanks
Andrew

**Comment by hloliver** [comment]
All good now
Sorry - should have thought of that!
Helen

**Comment by AndrewIsh** [comment]
Glad it's working!

Thanks
Andrew
