### ISSUE TITLE
Can't add multiple items to a list

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#322]
I'm unable to add multiple items to a list using the Koha/EBSCO connectors.

When I select multiple items from the results it looks as if they've been added to the list, but it isn't possible to add notes/tags, and once the list has been published the items haven't been saved.

Here's a screencast https://www.screencast.com/t/FcsPSUp0

The error messages at the end vary

Koha connector: 'No error details read from server. Server may be unavailable'
EBSCO connector: 'Error: List 4091 not found. Path:/

If another single item has been added separately beforehand but in the same session that will be saved when you publish the list, but if you add another single item separately after adding multiple items none of them are saved when you publish.

can you take a look sometime?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for that. Looking at your screencast, it looks like the API call might be failing for some reason. I'll try and replicate the problem and create an issue.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew




________________________________

**Comment by AndrewIsh** [comment]
Hi Helen

Just to let you now, this has been fixed. It will be made live on your system on next Tuesday's (9th) update.

I'll close this issue, if you continue to see problems, feel free to re-open it.

Many thanks
Andrew

**Comment by hloliver** [comment]
Great, thanks Andrew
