### ISSUE TITLE
'Add to list as' not working

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#324]
The 'Add to list as' feature isn't working, nothing happens when you select 'Book section' - I've tried this with EBSCO and Koha connectors, and using Chrome and IE
Can you take a look?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks very much for that. I just tried it on your instance and am seeing the behaviour you're describing. However, I am unable to replicate it on a local instance. I'll investigate further and report back once I've got to the bottom of it.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

This has now been fixed and the fix is live on your instance. I'll close this issue, if you continue to see problems, please feel free to re-open.

Many thanks
Andrew
