### ISSUE TITLE
Problems logging in with IE

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#327]
We're having problems logging in to RL2 with IE, but only on some pcs - it appears that you've logged in, and see the green 'user logged in successfully' box a the bottom of the screen, but when you go to the menu the only options offered are 'Login' and 'About'

One of the pcs is running Window 8 and IE 11, the other is running Windows 7 and IE 10 - we have the same set ups on two other pcs and RL2 is running fine on those!

I've tried clearing browser history, forcing reload and restarting the pc, but no difference.  Any idea what might be causing it? 

Thanks
Helen

**Comment by paulwilliamsBCU** [comment]
Hi. I've seen this too at BCU. I can provide a screencast if helpful...

**Comment by AndrewIsh** [comment]
Hi both

I've been having some trouble replicating this. Would it be possible for one or both of you to let me know what version of IE you're using?

Many thanks
Andrew

**Comment by paulwilliamsBCU** [comment]
Hi Andrew

For me, it's IE 11, specifically version 11.839.10586.0. I log in to Rebus:list (and get the green verification message), then click on the menu bar on the left. All of the options flash up for a second, then disappear, to be replaced by just the Login and About options. No problem on Chrome.

**Comment by AndrewIsh** [comment]
Hi both

Just to update. I've managed to replicate this once or twice on both your instances, but it happens maybe one time in twenty and doesn't leave any clue as to what's going on when it does! I'm working towards trying to reliably replicate it on my instance here as I need to be able to do that to be able to get an idea of what's happening.

Sorry to not have any more news, just wanted to let you know that I've not forgotten about this!

Many thanks
Andrew

**Comment by mrenvoize** [comment]
This one should be resolved after tonight's rollout.

**Comment by AndrewIsh** [comment]
Closing as fixed. If you still continue to have problems after tomorrrow, please re-open.

**Comment by hloliver** [comment]
Sorry I was away without any access to IE, but all good now!
Thanks
