### ISSUE TITLE
Display list year

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#329]
We've had feedback from our tutors that they would prefer the academic year displayed in full ie 2017/2018 rather than 17/18 - is this something that could be configured for different sites?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for this. I'll create an internal enhancement issue for this and update this issue once it has been implemented.

Many thanks
Andrew

**Comment by janetc** [comment]
Bradford would also like this enhancement.

**Comment by mrenvoize** [comment]
So we currently have `2016` and `16/17` as available formats..

Tavi and Bradford would like: `2016/2017`
Ulster would prefer: `2016/17`

Any more for any more formats :confused:

**Comment by AndrewIsh** [comment]
This has now been done and will be released on 11/07/2017. @janetc Could you please update Bradford? @mrenvoize Could you let Ulster know please?

I'll close this, feel free to re-open if there are further questions.
