### ISSUE TITLE
Diacritics not displaying correctly

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#33]
Please see the attached screenshot which shows the name Brontë not displaying correctly. 

![diacritics not displaying correctly](https://cloud.githubusercontent.com/assets/12249067/8695287/1916386e-2adc-11e5-9435-5cc3b7dae99f.jpg)

**Comment by AndrewIsh** [comment]
Thanks for that Sharon.

@mrenvoize Can you check the db for these materials and see if it's the DB that's breaking the diacritics. If not, I'll check the frontend.

**Comment by mrenvoize** [comment]
I'll look into it, we should be utf8 end to end, but perhaps the preview system got setup with the wrong coallations in the database.

**Comment by AndrewIsh** [comment]
This issue was fixed some time ago. I'll close this issue.
