### ISSUE TITLE
Judgmental Kitten

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#330]
I can't edit this list: https://tavi.rebuslist.co.uk/#/list/2179, I'm getting the judgmental kitten and the following error:

![cant_edit_list_error](https://cloud.githubusercontent.com/assets/12201255/26446612/b6a0a27c-413c-11e7-9bb1-1a5db8d91d71.png)

can you take a look
thanks
Helen

**Comment by hloliver** [comment]
Seeing the same error with  https://tavi.rebuslist.co.uk/#/list/2182 - think they were the two lists that I tried to rollover on 23/5 which locked the hierarchy
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

I can't replicate this, I just managed to open the drafts of both of these lists without any problem. Can you please confirm that you're still having the problem?

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew - both lists fine again now!
Thanks
Helen

**Comment by AndrewIsh** [comment]
Great, thanks the the update. 

Closing.
