### ISSUE TITLE
Tags created in list are not showing up in Manage Tags area

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#331]
Tags created on the fly aren't coming up as auto-suggestions anymore, and also aren't showing up in the Manage Tags area. 
can you take a look?
thanks 
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

I've manage to replicate this. I'll investigate and update this issue when I've got to the bottom of it.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

A fix has been created for this. It will be included in next Monday night's update.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Closing as fixed. If you continue to have problems after tomorrow, please re-open.

**Comment by hloliver** [comment]
Hi Andrew - can you re-open this?

I've tried creating tags in a list but they're not coming up if I start typing them in again on a different record - in fact it looks as if all of our tags from our migrated lists have disappeared as well as the only tag I can get to auto-suggest is one that I created in the Manage Tags admin area.

On a related note, the Manage Tags area only gives you an option to add a tag on the first screen - could you add an option to search for existing tags there as well?

Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Apologies for this.

>I've tried creating tags in a list but they're not coming up if I start typing them in again on a different record 

The fix for this that should have gone out last night didn't, it's now scheduled for next Monday night, many apologies for the inconvenience.

>in fact it looks as if all of our tags from our migrated lists have disappeared as well as the only tag I can get to auto-suggest is one that I created in the Manage Tags admin area.

>On a related note, the Manage Tags area only gives you an option to add a tag on the first screen - could you add an option to search for existing tags there as well?

However, both these problems should now be fixed.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks, will look out for that next week. Other two working perfectly now, thanks for sorting them out
best wishes
Helen

**Comment by AndrewIsh** [comment]
This was made available last Tuesday. I'll close this issue, feel free to re-open if you continue to see problems.
