### ISSUE TITLE
Hide individual entries on a list

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#333]
We really like the option to view changes made in the draft, and the Additional list info.

The first one reminded me of an enhancement that a couple of other sites, as well as us, had asked for in Rebus:list 1 a couple of years ago - being able to hide individual entries on a list.

We'd find this really useful when we update live lists which we end up doing quite a lot during the course of the year.  It's not too bad if there are only a couple of edits, but when there are a lot it would be good to hide the changes until they were complete and ready to publish so that it wasn't confusing for the students.

There are also occasions where the tutors don't want to release all of the readings in one go, it would be great if we could add all of the readings then suppress the ones that the tutors didn't want released yet

best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

I think this is addressed by the ability to create an ongoing draft of a list with the changes not visible until the list is published. The tutor could create the basic list, publish it, then add to a new draft of it until they want the additional items visible, then publish that draft.

I may, of course, be misunderstanding, in which case feel free to elaborate.

Many thanks
Andrew

**Comment by hloliver** [comment]
Sorry, I think you've probably got it covered! 

I think that this will be fine in most cases for the first example I gave, and we can work around the odd time where it isn't.

In the 2nd example we'd like to be able to create the whole list but hide the items that weren't needed straight away then release them as required by the tutor - usually a week at a time.  That wouldn't work so well as all of the changes would be published at the same time, but to be honest not that many tutors want to do that, so unless there's a demand from it from other customers please ignore!

Best wishes
Helen

**Comment by AndrewIsh** [comment]
OK. Well I'll leave this issue open for comment by other customers. If there's sufficient interest, I'll create an enhancement request.

**Comment by mrenvoize** [comment]
The weekly release of materials was the exact case that sublists and visibility periods were designed for at the request of some existing customers and tenders.

The idea was that a list is split into weekly sublists and those sublists each had their own visibility periods assigned so only became live during those periods.

**Comment by hloliver** [comment]
Ah, I knew I was missing something! Thanks Martin

**Comment by AndrewIsh** [comment]
Closing - feel free to re-open if you have any more questions
