### ISSUE TITLE
Missing icons in IE

### ISSUE THREAD

**Issue by paulwilliamsBCU** [PTFS-Europe/rebus-list-2#336]
Hi

There were some similar problems to this resolved a month or two back, and I think maybe this is related to it? When using Internet Explorer on a variety of machines here at BCU, I can't add a user to a list as an additional contributor etc. When I try this, I don't get the blue and orange icons showing the various levels (eg LEADER, OWNER, AUTHOR etc). Because these don't show, we can add a user to a list at all. In Chrome, this works fine.

I've attached a short video to show what I mean.

**Comment by AndrewIsh** [comment]
Hi Paul

Thanks for this, I'm not seeing the video, did you perhaps forget to attach it?

Many thanks
Andrew

**Comment by paulwilliamsBCU** [comment]
Thanks Andrew. Apologies - having a bit of trouble finding somewhere to host the video! Can't attach mp4 here and for some reason, my screencast-o-matic account suddenly won't allow uploads! Hopefully have it with you shortly...

**Comment by paulwilliamsBCU** [comment]
Does this work on Dropbox?

https://db.tt/1oNEmhFqrF

**Comment by AndrewIsh** [comment]
Yep, worked perfectly, thanks. I see the problem, will investigate.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Paul

This is now fixed and the fix will be released in the weekly update tonight.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
I'll close this, feel free to re-open if you still see the problem after the update tomorrow.
