### ISSUE TITLE
List:it issues

### ISSUE THREAD

**Issue by paulwilliamsBCU** [PTFS-Europe/rebus-list-2#337]
Hi

We're currently having a few problems getting results in List:it. In Amazon for example, I get results if the item is something also found via the Connector in our local catalogues, but no option to add if it isn't. Is there a setting which dictates whether items from outside of our holdings can be added?
![list it](https://user-images.githubusercontent.com/20226714/27627919-4f5b4c7a-5be5-11e7-8d3c-d85b7410a5ee.jpg)

**Comment by AndrewIsh** [comment]
Hi Paul

List:It works in the way you described, if the item is not available via any of your connectors, we are unable to harvest the metadata and cannot add the item to the list. In this case, it would be necessary for you to add a manual item. 

I hope this helps. 

Many thanks
Andrew

**Comment by paulwilliamsBCU** [comment]
Thanks Andrew. That's a shame - it does reduce the usefulness of the tool unfortunately. Never mind, thanks for the quick response.

**Comment by AndrewIsh** [comment]
It's certainly something we could consider for an possible future enhancement. It obviously would need custom metadata harvesters for whatever websites users were using List:It with, but it's certainly a good idea.

**Comment by paulwilliamsBCU** [comment]
Thanks Andrew - would be very happy to support that enhancement.

**Comment by mrenvoize** [comment]
Hmm, I'm not so sure about metadata harvesters... they're notoriously difficult to maintain and you need one per website you want to support.

However, for sites that have a reasonable api (amazon included) we could probably build connectors so we could add those as fallbacks (and perhaps have them as list:it only fallbacks) which would solve the same problem from a slightly different angle.

**Comment by AndrewIsh** [comment]
Indeed, I was using "harvesters" in the broader term, we certainly wouldn't want to get into scraping but, as you say, utilising APIs via Connect where available should enable acquisition of relevant metadata.
