### ISSUE TITLE
Table of Contents icons not working

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#338]
Hi - just been trying out the TOC icons but nothing happens when you click on them, we've tried on IE, Chrome and Firefox but it's the same for all of them..
Can you take a look?
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Many apologies, this was a bug in the TOC outlink. It is now fixed and will be pushed out on 04/07.

Many thanks
Andrew
