### ISSUE TITLE
Test Issue Submission

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#339]
**Raised by:** ashimema@gmail.com<br>
Testing github issue IFTTT link&nbsp;<br><br>
#### Attachments<br>
![](http://ift.tt/19fNRe4 )<br>
http://ift.tt/19fNRe4

**Comment by AndrewIsh** [comment]
It works! ;-)

**Comment by mrenvoize** [comment]
Blimey that was quick!

_Sent from my Sony D5803 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mrenvoize** [comment]
Seems the Gmail sync part of the IFTTT service was borked,  working now so closing this :-) 

_Sent from my Sony D5803 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
