### ISSUE TITLE
LDAP account creation

### ISSUE THREAD

**Issue by jomnz** [PTFS-Europe/rebus-list-2#342]
Hello,

We are seeing only users' first name being populated in the Name field when account are created via LDAP.

May I ask whether when searching for associated users, the 'Name' field is used? If so, would we be able to have LDAP populate the 'Name' field on account creation with both the users' first and last names?

![image](https://user-images.githubusercontent.com/26322588/27821824-855d7a68-609b-11e7-8fd4-015f56bb7551.png)

Thanks,
Joe
York St John University

**Comment by mrenvoize** [comment]
I've now added surname mapping to your ldap configuration (assuming the attribute for surname is 'sn' as is default on most LDAP systems I have come across).

You should see this take effect next time each person logs in.

To answer the direct question, yes all fields are searched.
