### ISSUE TITLE
collapsed breadcrumb

### ISSUE THREAD

**Issue by jomnz** [PTFS-Europe/rebus-list-2#346]
Hello,

We have found an unnecessary click in the breadcrumb trail. Parent lists default to collapsed state. Could this be changed to default to expanded? 

http://i.imgur.com/FjAzwbT.gifv

Thanks,
Joe
York St John University

**Comment by AndrewIsh** [comment]
Hi Joe

Many thanks for this. This has also been [raised by another customer](https://github.com/PTFS-Europe/rebus-list-2/issues/321) and is recorded as an enhancement request. I'll close this issue you, if you could refer to the existing one for updates, that would be great. 

Many thanks
Andrew
