### ISSUE TITLE
exception handling

### ISSUE THREAD

**Issue by jomnz** [PTFS-Europe/rebus-list-2#347]
hello,

We've identified a few areas where there is poor exception handling. 

One such example can be found in a user attempting to create a sub-list without the required permissions: 

http://i.imgur.com/E0UOsTK.gifv

We see an unexpected server error message in the bottom-right corner of the page.

Joe
York St John University

**Comment by AndrewIsh** [comment]
Hi Joe

Many thanks for this. In the situation you illustrated, if the user does not have the required permissions to create the sub-list, they should not see the buttons that allow them to do this. So what you're describing is a bug. I have created an internal issue to address this and will update this issue once it is fixed.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Joe

A fix for this bug will be included in next Monday night's update. I'll close this issue, if you continue to see the problem after the update has been released, feel free to re-open.

Many thanks
Andrew
