### ISSUE TITLE
Table Of Contents - Display

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#348]
The 'table of contents' option on journals is poorly formatted as raw xml.. This matches RL1, but we should do better in RL2.

**Comment by AndrewIsh** [comment]
Looking at the journaltoc API documentation, there's no way to get the data back in anything other than RDF.

On the upside, [feedparser](https://www.npmjs.com/package/feedparser) will parse RDF feeds. On the downside, it's a node app. On the upside, we could probably Browerify it, on the downside, that might not work. 

We could create a small node powered web service that runs feedparser, that would be cleaner, but would be another service to maintain.

Need to ponder...

**Comment by AndrewIsh** [comment]
Aha! It's not just RDF, it's RSS! Things suddenly got much simpler. There's a number of ways we can do this, just need to choose one.

**Comment by AndrewIsh** [comment]
Right, more findings. [angular-feeds](http://siddii.github.io/angular-feeds/app/) seems like a possible way forward. However it, and seemingly every other RSS feed reading library is dependent on [Google Feeds](https://developers.google.com/feed/) which was deprecated and was supposed to stop working at the end of 2016 (though to date still seems to be working). We _actually_ only need something that can parse RSS into a something like JSON. Digging required...

**Comment by AndrewIsh** [comment]
https://www.raymondcamden.com/2015/12/08/parsing-rss-feeds-in-javascript-options

**Comment by AndrewIsh** [comment]
Closed in https://github.com/PTFS-Europe/rebus-list/pull/2466
