### ISSUE TITLE
Enhancement request - recycle bin for deleted lists

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#349]
Hi

On a few occassions our staff have accidentally deleted a module list completely from the system. Would it be possible to create a recycle bin/archive area where lists can be retrieved for a certain period of time after they have been deleted? Possibly 30 days? 

An alternative might be that the delete list function is removed from list level permissions and the subject librarian can only suppress a record and mark it for deletion. The system admin then confirms deletion in an area of the sytem that only they can access. 

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Many thanks for the suggestions. Being able to modify list level permissions is definitely on our to-do list, although I currently don't have an expected date. I've created an internal issue. I'll close this issue but will update it once I have more information as to when this is likely to appear.

Many thanks
Andrew
