### ISSUE TITLE
Updated notifications appearing when lists not updated

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#35]
After clicking on the 'scroll button' notifications appeared to say the list had been successfully updated, however no updates had taken place.  Please see attached screenshot. 

![notification after clicking on the list - no edits](https://cloud.githubusercontent.com/assets/12249067/8696560/335dfd34-2ae5-11e5-94d8-65f4727efb57.png)

**Comment by AndrewIsh** [comment]
Hi Sharon,

Thanks for that, you're right, I'll look at that.

Cheers
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/912

**Comment by AndrewIsh** [comment]
This is now fixed. Closing.
