### ISSUE TITLE
Problems adding records from EBSCO connector

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#350]
Adding items to a list from our EBSCO connector is generating errors

ie https://tavi.rebuslist.co.uk/#/list/2223 displayed an 'internal server error' 
https://www.screencast.com/t/rscVj5mPKr 

This occurred when I was trying to replicate an error that a colleague had reported when using the EBSCO connector in this list https://tavi.rebuslist.co.uk/#/list/2221

In his case he got the following error:

![ebsco connector error](https://user-images.githubusercontent.com/12201255/27844249-b6a4a094-6116-11e7-837e-bafc49189ba1.jpg)

He tried both recover and discard options but neither made any difference

Can you take a look?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for this. I just tried and was able to replicate the problem. I'll investigate and get back to you.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

This should now be fixed. I'll close this issue, feel free to re-open if you continue to see problems.

Many thanks
Andrew

**Comment by hloliver** [comment]
Great, thanks for sorting this out so quickly
Best wishes
Helen
