### ISSUE TITLE
Judgmental Kitten

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#351]
Hi - we're seeing the Judgmental Kitten for this list:
https://tavi.rebuslist.co.uk/#/list/1523
can you take a look?
thanks
Helen

**Comment by hloliver** [comment]
And this one: https://tavi.rebuslist.co.uk/#/list/1763

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this. I was able to reliably replicate the problem. I'll investigate and get back to you once I've got to the bottom of it.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

These lists should now both be working. I'll close this issue, feel free to re-open if you're continuing to have problems.

Thanks
Andrew

**Comment by mrenvoize** [comment]
Leaving a comment

**Comment by hloliver** [comment]
Still getting the judgmental kitten today for both lists - can you take another look?
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

i just looked and I'm not getting the kitten on either of those lists, are you still experiencing the problem?

![image](https://user-images.githubusercontent.com/9194223/28924885-1a9f8824-785b-11e7-9275-73d48de37382.png)

![image](https://user-images.githubusercontent.com/9194223/28924901-25e886a4-785b-11e7-9979-5562afd390f7.png)

**Comment by hloliver** [comment]
?Odd, I checked it when I was logged in and logged out and couldn't get in to either list, but both fine now.

Sorry about that, will keep an eye on it though.

Helen

**Comment by AndrewIsh** [comment]
I noticed they're both suppressed, so only visible to users with sufficient privileges (and definitely not visible to unauthenticated users), could it be that you were logged in as a user without sufficient privileges?

**Comment by hloliver** [comment]
I always use the same admin account so shouldn't have been that - and I'm sure that I tried both logged in and not logged in, but there's definitely room for doubt!

Apologies, Helen

**Comment by AndrewIsh** [comment]
No worries. I'll close this. Feel free to re-open if it comes back.

Regards
Andrew
