### ISSUE TITLE
List locked

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#353]
HI
We're seeing the judgmental kitten for this page:

https://tavi.rebuslist.co.uk/#/list/1541

I've checked the dates (which are all empty in the lists so it's inheriting the unit's dates), but the Modify this Hierarchy Element button is greyed out.

Can you take a look?
thanks
Helen

**Comment by hloliver** [comment]
Sorry, just realised that the Modify button is greyed out because I was already modifying the record!
Still seeing the judgemental kitten though
bw
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Apologies for that, there was an error in the data for one of the materials in that list, it is now fixed and the list should open fine.

I'll close this issue, if it continues to be a problem, feel free to re-open.

Many thanks
Andrew

**Comment by hloliver** [comment]
all good now, thanks!
