### ISSUE TITLE
Book chapters displaying journal toc icon

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#355]
We're coming across quite a few book chapter records which have been migrated across from RL1 which are displaying journal TOC icons.  

ie https://tavi.rebuslist.co.uk/#/list/3615

![journal toc icon for book chapter](https://user-images.githubusercontent.com/12201255/28766097-cc81a6be-75c5-11e7-82d2-f30bdf631068.png)

Several book chapter records in this list display the toc icon ie

Seminar 1 - Klein, Personification in the play of children

Seminar 2 - Klein, The importance of symbol formation in the development of the ego

Seminar 3 - Klein, A contribution to the psychogenesis of manic depressive states

Seminar 6 - Meltzer, Part II: Richard week-by-week

(the Klein chapters are all from the same book, but colleagues have reported the same issue in different lists with different books)

I've had a look at the records and can't see the issn that the toc service is searching for anywhere in the record

Could you take a look?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Here is the metadata we're storing for "Love, guilt and reparation and other works 1921-1945.". As you can see, it does indeed contain an ISSN, hence the TOC button.
```
{
	"ISBN": ["0-7012-0408-7"],
	"ISSN": ["0099-7528"],
	"URL": ["http:\/\/search.ebscohost.com\/login.aspx?direct=true&db=psyh&AN=1930-02320-001&authtype=shib&site=ehost-live&custid=ns014732", "https:\/\/tavi.koha-ptfs.eu\/cgi-bin\/koha\/opac-detail.pl?biblionumber=1081", "http:\/\/search.ebscohost.com\/login.aspx?direct=true&db=psyh&AN=1930-02320-001&authtype=shib&site=ehost-live&custid=ns014732"],
	"author": [{
		"literal": "Klein, M"
	}],
	"container-author": [{
		"literal": "Klein, Melanie"
	}],
	"container-title": "Love, guilt and reparation and other works 1921-1945.",
	"container-title-short": "Love, guilt and reparation and other works 1921-1945.",
	"id": ["1-3193"],
	"issued": {
		"raw": "1975-01-01T00:00:01Z"
	},
	"medium": ["REFERENCE", "BOOK", "BOOK", "BOOK", "BOOK", "BOOK", "BOOK", "BOOK", "BOOK", "BOOK", "BOOK"],
	"note": ["Numerous reprints incl.: Hogarth Press, 1985; Delacorte Press\/Seymour Lawrence, 1975; Virago (1988); Vintage, 1998"],
	"number-of-pages": 13,
	"page-first": "219",
	"publisher": "Hogarth Press and Institute of Psychoanalysis,",
	"publisher-place": "London,",
	"shortTitle": "Love, guilt and reparation and other works 1921-1945.",
	"submitted": {
		"raw": "1975-01-01T00:00:01Z"
	},
	"title": "The importance of symbol formation in the development of the ego",
	"type": "chapter"
}
```
I've checked the other records you mention and they too contain ISSNs. If this is incorrect, it might be worth contacting Martin to query why this is. 

In the meantime, I'll close this issue. If you have further questions, feel free to re-open.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew, that's odd - no idea how they got there! Will check with Martin.
Helen?
