### ISSUE TITLE
Koha connector not working

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#356]
Trying to add new items to a list but the Koha connector doesn't seem to be working.

In this video the search lists Koha as one of the resources it's searching but doesn't return any results:

https://www.screencast.com/t/0dh4gtZQZDn7

However, searching Koha for 'Lanyado' returns 17 results https://tavi.koha-ptfs.eu/cgi-bin/koha/opac-search.pl?idx=&q=lanyado

and 'Handbook of child and adolescent psychotherapy' returns 5 results https://tavi.koha-ptfs.eu/cgi-bin/koha/opac-search.pl?idx=&q=Handbook+of+child+and+adolescent+psychotherapy

Could you look at this asap?
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

I see what you mean, I've contacted Alex to see if he can get to the bottom of it. I'll update here when I have more info.

Thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

Apologies for that, this is now fixed.

Many thanks
Andrew

**Comment by hloliver** [comment]
?Great, thanks Andrew
