### ISSUE TITLE
Koha connector lost again - urgent!

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#357]
Hi - we've lost the Koha connector again, can you have a look asap!
thanks 
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Apologies for the delay in responding. As you've probably noticed, the connector is now back. Just to note, you'll get a more speedy reply if you log urgent problems such as this on OTRS.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew, will do

best wishes

Helen
