### ISSUE TITLE
Sort by rank button - query

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#36]
We are unsure what the 'Sort by rank' button does.   We thought it would sort by the number of 'likes' but it doesn't.    Is this a bug?  Or could you clarify what ranking it uses?  A screenshot is attached to show a list with various 'likes' but sorted in what appears to be a random order. 
![sort by rank button query](https://cloud.githubusercontent.com/assets/12249067/8697057/ce6276e4-2ae9-11e5-98a5-acd03761b048.png)

**Comment by AndrewIsh** [comment]
Hi Sharon

'rank' is the order that the list creator has specified when they created the list. Perhaps 'rank' is misleading, it originated from the assumption that the list creator would place the most important items at the top of the category, hence 'ranking' them.

So, sorting by rank is a way of viewing the original 'ranking' of items by the list creator, or reversing that order, or restoring the original order after sorting alphabetically.

I hope that makes sense?

Cheers
Andrew

**Comment by mrenvoize** [comment]
Added internal issue https://github.com/PTFS-Europe/rebus-list/issues/1006, closing this public one.

**Comment by mrenvoize** [comment]
needs PTFS-Europe/rebus-list#1006

**Comment by mrenvoize** [comment]
I've opened an internal issue for this now.. any thoughts regarding a more appropriate description on that hover text would be greatly appreciated @SharonCocker ?

**Comment by CFWilliams** [comment]
Hi,

If I've understood this correctly, PTFS are interpreting the list creator's input order as having some form of prioritised value. At Leeds Beckett, we are scanning through paper course handbooks for references, these are not necessarily in a structured order! Other institutions may be more organised...

**Comment by AndrewIsh** [comment]
Hi

Thanks for the feedback. Would you have a preferred default order for material to be displayed within a list category?

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
We sort by original creation order by default, when sorting the option to return to the original order is labelled "Original sorting" which seems to address this issue. Closing.
