### ISSUE TITLE
Exporting lists broken

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#360]
Problems exporting lists - we're seeing a new error when we try to export lists, I'm going with unicorn-t rex?
ie
https://tavi.rebuslist.co.uk/#/list/2696
https://tavi.rebuslist.co.uk/#/list/2714

It doesn't happen on all lists, this one is ok 
https://tavi.rebuslist.co.uk/#/list/2841, but it's only got two references

can you take a look?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for that. I see what you mean. I'm not sure what's happening here, but I'm tagging @mrenvoize as it looks like it's coming from the API. Hopefully he will be able to shed some light on it. I'll create an internal issue and we'll investigate.

![image](https://user-images.githubusercontent.com/9194223/29355708-fb27dc30-8269-11e7-91eb-3ea207e1210d.png)

Thanks
Andrew

**Comment by hloliver** [comment]
?Thanks Andrew - thought it might be one of yours!

**Comment by AndrewIsh** [comment]
Hi Helen

Just a quick update on this. We've determined that the problem arises with lists containing Journal material types. We've created a fix and it will be pushed out with the next release.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew

This seems to be fixed for some lists
ie https://tavi.rebuslist.com/#/list/2758 and https://tavi.rebuslist.com/#/list/2766

but we're still seeing the t-rex error for others 
ie https://tavi.rebuslist.com/#/list/2744 and https://tavi.rebuslist.com/#/list/2745

could you take another look?

thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

The fix for this has yet to be pushed out, which will be why you're still seeing the problem. We're anticipating getting the fix out in the near future. I'm going to close this issue and open a corresponding one on OTRS, where our correspondence can continue, as all support issues should be going via there.

Many thanks
Andrew
