### ISSUE TITLE
Navigation with rebus:list 2.0  via email

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#37]
From: HOliver@tavi-port.ac.uk
Subject: Navigation with rebus:list 2.0 
Date: July 18, 2015 at 08:24AM 

Hi Nick,

I'm afraid that I haven't been able to spend anywhere as much time looking at the rebus:list 2.0 that I would like to have done, sorry for not giving any feedback on it.

One of the issues that I keep getting hung up on though is the navigation and the fact that the hierarchy seems to have changed completely to include the actual lists rather than the framework that manages the lists.

The way that our students currently access their reading lists is usually from a link to the parent group of lists i.e. we put this link on their VLE http://ift.tt/1VdqASM, and from that the students can see the different modules available and find their way to the list that they want.

From what I can see on the preview site the students will need to navigate to their lists using the breadcrumb trail and dropdown menus - will there also be an option to display them in a group in a similar way that we do now so that they can see at a glance?

Sorry, this has been giving me a huge headache as it will be an enormous behaviour change for our students, and a big risk that they won't see the new navigation - most of them are not very confident online so unless they see a big green button saying 'Click here' they go away empty-handed! 

If I have completely misunderstood please let me know, I've only had time to dip in and out of the preview site so there will have been a lot that i have missed! 

Best wishes Helen Helen Oliver 
Systems Librarian 
Tavistock & Portman NHS Foundation Trust 
Tavistock Centre 
120 Belsize Lane 
London 
NW3 5BA

**Comment by AndrewIsh** [comment]
As far as I can see this is a non-issue. They appear to want to be able to link to a particular point in the browse hierarchy, which RL2 offers.

**Comment by AndrewIsh** [comment]
E.g https://preview.rebuslist.com/#/browse/2

**Comment by mrenvoize** [comment]
Closing here, will discus with Helen when we come to migrate them into RL2.. I agree I don't think this is an issue, more of a misunderstanding of usage.
