### ISSUE TITLE
rebus:list 2.0 query - Global Settings: book cover options  via email

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#38]
From: h.quinn@sheffield.ac.uk Subject: rebus:list 2.0 query - Global Settings: book cover options Date: July 22, 2015 at 10:31AM Hello, I am in the middle of testing out the rebus:list 2.0 preview. During looking at the Global Settings book cover options page I'm unsure whether I've accidentally changed the options? - bit trigger-happy with my mouse! I thought I ought to let you know in case I've altered something which might cause problems. With apologies, Heather

**Comment by AndrewIsh** [comment]
Seems fine. Closing.
