### ISSUE TITLE
Add ‘cancel’ button to Edit List function (draft/publish/cancel)

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#40]
Suggested function discards any changes made in list edit mode and exits the function.  At moment, if a user decides they don't want to publish or save to draft the changes made in edit list mode they have to manually unpick them.

**Comment by mrenvoize** [comment]
I wouldn't call hitting 'undo' a manual unpicking..

The way in which the storage happens would make a 'cancel' operation rather difficult to achieve.  Needs some thought as to the validity of this request.

**Comment by NickPhipps** [comment]
Fair point.  I'll close the issue.
