### ISSUE TITLE
List metadata – academic year (2015/16)

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#41]
Present list metadata field 'year' in academic year format

**Comment by mrenvoize** [comment]
Technical Specification

Two new system preferences:
1) Display Format (Academic [14/15], Calendar [2014])
2) Display in List Title

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#1994

**Comment by AndrewIsh** [comment]
This has now been implemented and will be pushed out with the next update. There are two new global preferences, "Display list year with list title" & "Year display format", the list display looks these up and acts accordingly. Will update the docs now.

Closing.
