### ISSUE TITLE
Sequence of sub-lists in student's pull down list same as hierarchy's sequence.  

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#42]
The sequence displayed in the read-only pull down list seems to be arbitrary.  Matching the hierarchy  sequence would be ideal but an alternative (eg, alphabetic sequence) would be an improvement.

**Comment by CFWilliams** [comment]
Yes it would

**Comment by AndrewIsh** [comment]
This was fixed some time ago. Closing
