### ISSUE TITLE
Item type icons

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#43]
Stick with the v1.2 item type icons for now.  Consolidate related item types (eg, article, journal article, newspaper article, magazine article, etc.) to a single v1.2 item type (eg, article).   Suggest we review this for some of the more exotic item types (eg, maps) closer to the full release date.

**Comment by AndrewIsh** [comment]
The selection of 1.2 item type icons is no where near broad enough for all the CSL item types. This is the reason for the shift to the new ones (plus, they're in keeping with icons we're using elsewhere in 2.0). The new icon selection is still admittedly not broad enough for all the CSL types but is much broader than the 1.2 icons.

**Comment by NickPhipps** [comment]
I have already acknowledged that the number of item types has increased significantly and this should be addressed by consolidating related ones  to a single icon (see above).  Do we have any evidence that students will find it useful to filter by different types of articles?

**Comment by AndrewIsh** [comment]
The main problem is that consolidation will only get you so far. CSL has a number of material types for which there isn't anything even approaching a suitable icon (there are many, but examples would include maps, thesis, legal case). Our new icon set does have icons for these types.

**Comment by AndrewIsh** [comment]
As far as filtering is concerned. Although CSL provides types for journal articles, newspaper articles, magazine articles and generic articles, I doubt any Connect source will make the distinction, so it'll end up coming into RL2 as whatever CSL type we map it to.

**Comment by NickPhipps** [comment]
Ok for the more obscure item types.  Leave it for now, but don't be surprised if customers ask for commonly used item types to be consolidated.

**Comment by AndrewIsh** [comment]
Customers seem happy with the choice of icons, we can always revisit if it becomes an issue. Closing.
