### ISSUE TITLE
Book chapter - adding additional text

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#44]
How do you create a book chapter?   I added the book required, but could not find how to add the chapter details afterwards.  The entry displayed in the list shows the book title as if it was the chapter title.  I couldn't see where I am going wrong. 

![rebus 2 0 screenshot how create data for a book chapter](https://cloud.githubusercontent.com/assets/12249067/9881202/c16a9116-5bc6-11e5-9a02-df185e8855d0.png)

**Comment by mrenvoize** [comment]
Good question, this area of functionality is still an area of work in progress.

The data layout in rebus:list 2.0 is much more frbrized at the core, I have implemented 99% of the server-side code now, but need to discus with @AndrewIsh as to the best approach for the Clientside user interface.

I'm going to bat some ideas around with him later this week and then getting some feedback on an envisaged workflow from yourselves would be great :)

**Comment by SharonCocker** [comment]
I've just tried to add a journal article and find a similar problem to that of trying to add a book chapter - is this part of the same area of work in progress?  (ie only the journal title will add to the list and there are no fields to add article details)

**Comment by AndrewIsh** [comment]
Hi Sharon

This is actually being worked on at the moment. Material type specific input forms will be on preview shortly, I'll let you know when.

**Comment by mrenvoize** [comment]
@AndrewIsh Is this the work I merged into preview early this week?

**Comment by mrenvoize** [comment]
@SharonCocker I believe stage one of this is now complete, in that you can now manually add chapter/article records.  We are still working on the FRBR side of things enabling better integration into the add by catalogue search functionality and DOI searching.

Many thanks

**Comment by AndrewIsh** [comment]
@mrenvoize Indeed it is.

**Comment by AndrewIsh** [comment]
Actually, book chapter is one of the forms that hasn't been done yet, I'll do it first thing Monday (on leave today)

**Comment by AndrewIsh** [comment]
Hi Sharon.

This is now live on preview. The new material editing form (under the admin menu "Search for material") should allow you to add chapter and journal article details, as should the manual material add form.

I'll close this for now, if anything isn't clear, feel free to re-open.

Thanks, Andrew

**Comment by SharonCocker** [comment]
Hi Andrew,

Can we re-open this one please?  I've tried adding a book chapter and not had any success.  I firstly tried via "Search for material" and perhaps I was doing something incorrectly, but I couldn't get it to work for any title, ie it didn't seem to even be searching for anything.  

I also tried adding a chapter via manual entry of material - I went through each of the sets of fields and entered data, but once finished only the author's details appeared in the entry.   Also, I couldn't figure out how to go back into the item and amend it - there doesn't seem to be any obvious way of editing individual items.   (If I'm doing this wrong, please could you let me know, thanks.) 

Also I noticed a couple of things about manual entry which I wanted to raise - the date published option and the 'finish' button.  I'll raise these as separate issues.   

Just as a last comment regarding adding chapters or article entries - in the current version of rebus:list it is possible to add chapter/article details either at the point of entry, ie the user searches for the book/journal from the library catalogue and completes all the relevant chapter/article details all in one action.   Here at Sheffield we use articles and book chapters very frequently in our list work and so if it had be to done via a manual entry each time it would be quite time consuming.   

Many thanks,
Heather
