### ISSUE TITLE
Unable to delete list

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#46]
Added 'Test' list to Manage Hierarchy on Preview (first level down from top).  Tried to delete it: error message 'can't delete list'.

**Comment by janetc** [comment]
Hi, Can I reopen this please - Bucks and YSJ have both reported this. I just tested on Preview2 and even as Admin can't delete a list. See https://preview2.rebuslist.com/#/list/223
After clicking Confirm get msg "Unable to delete"

Or is there a workflow that I'm missing?

Thanks

**Comment by AndrewIsh** [comment]
No, you're doing it right. It's a known issue, not sure why it was closed.

**Comment by mrenvoize** [comment]
I'm pretty sure this is no longer the case, I can't replicate it.
