### ISSUE TITLE
Hierarchy management - drag & drop to new tree

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#47]
Created a new tree (test 2) tried to drag and drop the  Faculty of Medicine hierarchy branch from the Rebus:list tree.   Drag worked but 'drop' didn't.  The branch didn't link to the test 2 tree and returned to the Rebus:list tree.

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1136

**Comment by AndrewIsh** [comment]
Fixed in https://github.com/PTFS-Europe/rebus-list/pull/1354

Closing
