### ISSUE TITLE
Material manual entry - date published option/calendar - suggestion

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#48]
Hi,

When creating a manual entry to material, the option to add a publishing date brings up a calendar (please see screenshot) - I couldn't seem to be able to enter any free text and could only use the calendar to select a date.   Dates for material published are most usually by year only, rather than a specific full date.    Also, if you need to choose a date in the past, eg 1971, there is no easy way to move the calendar backwards in time.    Would it be possible to make that field free text only?

Thanks,
Heather 

![rebus 2 0 screenshot manual entry date option](https://cloud.githubusercontent.com/assets/12249067/10510389/9b678944-732a-11e5-9dab-a6db0f59352a.png)

**Comment by AndrewIsh** [comment]
Hi Sharon

Thanks for this, I'll discuss internally about what we can do about this.

Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1134

**Comment by mrenvoize** [comment]
Thank you for the comments Sharon.

I think freetext is likely not going to be a viable option unfortunately, as it opens the field to accepting forms of dates that the backgrounds systems won't understand.. for example we intent to eventually allow for searching/filtering on lots of the fields available in the metadata, at which point things like 'January 2012' and '2011/2012' are not understandable by a computer without a large amount of human intervention.

However, I can certainly see the downfall of this particular calendar widget, it's not exactly easy to use for this case.  I'm proposing a 'flat' widget to replace it with a dropdown/textbox for year, month, day with none of these being required fields. If you only select a year for example, in the background we'd map this to 01/01/Year to denote publication covering that entire year.  Selecting a more specific date would be entirely optional at that point.

Does this sound like a viable solution?

**Comment by SharonCocker** [comment]
Hello Martin,

I think so long as we are able to show just the year published (rather 
than a full DD/MM/YY) so it references the item correctly, then this 
would work better.

For example:
Sinnott-Armstrong, Walter; Howarth, Richard B; Perspectives on climate 
change [electronic resource] : science, economics, politics, ethics,
Bingley : Emerald, 2005

Best wishes,
Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by JoannaBek** [comment]
Hi,

Just wondered if there had been any update re the date picker widget to enable any year to be selected quickly rather than paging through individual months?

Thanks,
Heather

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks very much for your message. This has not yet been addressed, but it is definitely on the list. I've just checked where it is on the list, and it's pretty near the top so hopefully I'll get to it soon. I'll let you know as soon as it's done.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Duplicated by #62

**Comment by AndrewIsh** [comment]
We have removed the date picker in favour of manual date entry. Publishing dates can now be manually entered as `YYYY` or `YYYY-MM` or `YYYY-MM-DD` Hopefully this addresses the issue. Feel free to reopen if not.
