### ISSUE TITLE
Material manual entry - finish/cancel buttons obscured - suggestion

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#49]
Hi,

When adding material by manual entry, I noticed that the 'Finish & Cancel' buttons at the bottom of the page are obscured by the 'Save/Publish' footer - please see screenshot.   The page can be scrolled upwards, but I couldn't see any way of moving the manual entry page away from the footer.  

Is it possible to change this?

Thanks,
Heather

![rebus 2 0 screenshot manual entry finish button](https://cloud.githubusercontent.com/assets/12249067/10510562/b13ed9b0-732b-11e5-80ee-9ba43a113aa3.png)

**Comment by AndrewIsh** [comment]
Hi Sharon,

Yes, thanks for that, it's something we'd spotted but not got round to fixing yet.

Thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1022

**Comment by AndrewIsh** [comment]
This has now been resolved. Closing.
