### ISSUE TITLE
More metadata option sometimes displays incorrectly

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#50]
Hi,

I've noticed that sometimes the 'more metadata' option for material does not display correctly - please see screenshot.   

Many thanks,
Heather

![rebus 2 0 screenshot more metadata](https://cloud.githubusercontent.com/assets/12249067/10510735/9ba03a08-732c-11e5-982b-e5d0e5fdb0db.png)

**Comment by AndrewIsh** [comment]
Hi Sharon

Thanks for this, another one that's on the list, we've just not got round to fixing yet.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1135

**Comment by AndrewIsh** [comment]
Closed in https://github.com/PTFS-Europe/rebus-list/commit/809f873b49570893a424d0345aec0e031b39e697
