### ISSUE TITLE
Problems with moving items around the list / adding item at the top of the list

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#53]
Hello,

I seem to be having problems with moving items around the list. Firstly, due to the entries being quite big visually, it takes very long time to bring them from top of the list to the bottom (and the other way around). 

Also when moving the item and trying to add it as shown at the picture, the item goes back to its original place. I have to be very precise in placing it within the gray boundaries for it to stay. The problem appears only when trying to add item to the category that is empty - works fine if there are other items already there.
![trying to move file](https://cloud.githubusercontent.com/assets/16195154/12751562/c4926456-c9b5-11e5-9919-86d1c5c3ad43.png)

Additionally, if there are any items in a category, it is impossible to just add item at the top of the list - I need to create a new entry below the first one, and then move it. Would it be possible to keep the plus sign for adding the items at the top, that is there for the empty categories?

Thanks a lot,
Joanna

**Comment by mrenvoize** [comment]
Very useful feed back @JoannaBek, I'll pass it onto our UI Developer, many thanks for getting in touch.

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#1544

**Comment by JoannaBek** [comment]
Hello,

I've been moving items around and I'm getting this error message:
![error message](https://cloud.githubusercontent.com/assets/16195154/12845921/3b824980-cc01-11e5-904d-42acbe86e358.png)

Yesterday after receiving this message, I was logged out of the preview and then couldn't get back into the edit mode. Today it doesn't seem to be interfering with my work - it just pops up every now and again.

**Comment by AndrewIsh** [comment]
A fix was pushed out for this some time ago. I'll close this issue. If you are still seeing problems, feel free to reopen.

Many thanks
Andrew
