### ISSUE TITLE
Problem manually adding items to list - Safari

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#55]
Hello
If I try to add items manually to a list when I'm using Safari (Version 9.0.2 (10601.3.9)) I see the following error - I've tried a couple of different item types (book, article) with the same result. I can add items successfully using Chrome though
bw
Helen

![adding_items_manually-safari](https://cloud.githubusercontent.com/assets/12201255/12884502/a134bcd4-ce56-11e5-93ef-9be5cf2a7d83.png)

![adding_items_manually-safari-error](https://cloud.githubusercontent.com/assets/12201255/12884685/d7883936-ce57-11e5-9828-647d6b66be9d.png)

**Comment by AndrewIsh** [comment]
Hi Helen

It sounds like Safari has got itself into a bit of a mess. Could you please do the following for me, do this using Safari:
- Log into rebus:list 2 as an admin user
- In the Main menu, go to "About rebus:list"
- Right at the bottom of the page is a big red button, click it
- You should then be able to add items in Safari, if not, let me know.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew, that seems to have sorted it
Helen

**Comment by AndrewIsh** [comment]
OK, thanks for the update Helen. Let me know if you have more problems. I'm currently working on a fix that will hopefully prevent this from happening again. I'll close this issue for now.

Thanks
Andrew
