### ISSUE TITLE
Admin menu display (Firefox browser)

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#58]
In Firefox, there have been various times when the administration menu hasn't displayed correctly: 

![firefox admin menu error](https://cloud.githubusercontent.com/assets/17139950/12913878/2563200a-cf19-11e5-8e70-e2844901f657.PNG)

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for this. Have you only seen this problem in Firefox? Also, roughly how often does it occur, for example, while using the application, does it occur every 5 minutes etc.?

Many thanks
Andrew

**Comment by richughes** [comment]
Hi
i've just noticed a similar problem with the display, this time at the login screen. Still using firefox. It happended the first time I tried to login this afternoon. It appeared okay for a split second, then changed when I scrolled down slighlty.

![login screen error](https://cloud.githubusercontent.com/assets/17139950/12980407/3b09186c-d0d4-11e5-9e03-3f0f2c2e24e1.png)

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Very interesting, this certainly is a weird one. I use Chrome and have nevert seen this issue, I'm going to do some testing with Firefox today and see if I can replicate it. Many thanks for the update.

Thanks
Andrew

**Comment by AndrewIsh** [comment]
We have now been able to replicate this. https://github.com/PTFS-Europe/rebus-list/issues/1612

**Comment by AndrewIsh** [comment]
Also raised here https://github.com/PTFS-Europe/rebus-list-2/issues/69

**Comment by mrenvoize** [comment]
We have hopefully finally gotten to the bottom of this one with the 24/01/2017 release.. Please re-open if you continue to have this problem.
