### ISSUE TITLE
Unresponsive script message (Firefox)

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#59]
In Firefox, when navigating the site the following message often appears:
![firefox script debug](https://cloud.githubusercontent.com/assets/17139950/12913967/a9b58334-cf19-11e5-94f2-8922173c7753.PNG)

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for this. Have you noticed that this message appears on any particular parts of the site?

Many thanks
Andrew

**Comment by richughes** [comment]
Hi Andrew

I've only seen this message once, but Kasia who is currently building our lists has had it happen quite a few times.  She was using version 34 of Firefox so I've asked her to update it and see it improves. It seems to be mostly in edit mode, especially when she's using the Summon connector quite a lot. 

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for the additional information. If possible, could you ask Kasia to make a note of what she's been doing recently if she sees this message again, ideally what she has been doing in the previous 10 minutes or so, i.e. adding items to lists, moving items around etc.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Richard

The fix for these problems I previously mentioned in issue #57 was pushed to your server about a week ago. Is Kasia still seeing these problems? If not, I'll close this issue.

Many thanks
Andrew
