### ISSUE TITLE
Material Display: Item type field

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#6]
We should allow the display of Item/Material type in the public list view.

**Comment by mrenvoize** [comment]
This sort of refinement will be configurable by the customer once the template system has been implemented.

**Comment by SharonCocker** [comment]
Just to clarify - is this the same as "material type"?   (please see screenshot) There are a number of types not listed which we would need for our lists.   Thanks, Heather

![rebus 2 0 screenshot ability to create own item types](https://cloud.githubusercontent.com/assets/12249067/9880832/4c940ad0-5bc5-11e5-8c18-79490512b7bf.png)

**Comment by mrenvoize** [comment]
NOTE: See reply in newly created issue #45

**Comment by mrenvoize** [comment]
Material Type hinting is now available in the master branch, I will update preview shortly

**Comment by SharonCocker** [comment]
Hi Martin,

The main one I spotted is ebook (which we often use), so I think adding 
e-\* alternatives would certainly be useful for us as we do have 
e-journals in the library as well as print journals (though currently 
use journal for both).  We also have some in-house item types such as 
"private note", "other".   Would we be able to create custom item types?

Thanks,
Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by mrenvoize** [comment]
Inactivity, believe fixed
