### ISSUE TITLE
No <title> tag on the site.

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#60]
There doesn't seem to be a <title> tag in the HTML. Will this be added once the logo area is created?

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for the question. The intention is to make the contents <title> tag user configurable, with the default being "rebus:list - <customer_name>". This is on the list of things to do, I'll let you know here as soon as it is implemented, it should be soon.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1574

**Comment by AndrewIsh** [comment]
Hi Richard

Just to let you know, this has now been added. There is now "Site title tag" and "Customer name" settings in Global Preferences > Custom content & CSS. These control the appearance of the <title> tag.

I'll close this issue, if you have further questions regarding this, feel free to re-open.

Many thanks
Andrew
