### ISSUE TITLE
CSL display article or chapter records - page numbers

### ISSUE THREAD

**Issue by NickPhipps** [PTFS-Europe/rebus-list-2#63]
Some reference standards (eg, Harvard) use first page, last page (rather than number of pages) for article and chapter item types.  The RL record needs to have all 3 fields to handle CSL variations.  For example, if the source only returns first page and the number of pages add a routine to generate the last page number as part of the record create process.

**Comment by AndrewIsh** [comment]
Unfortunately, CSL has no provision for last page number. So, even if we calculated it, there would be no way of representing it in the CSL metadata, and tools, such as Citeproc (which we use to generate our citations) would have no knowledge of how to use it.

That said, as you say, some ref standards do display last page, so there must therefore be a way of generating it. I am guessing that Citeproc does the calculation itself if the standard in use calls for it. However, this is only a guess, I'll check the Citeproc source code and verify.

**Comment by mrenvoize** [comment]
As Andrew has highlighted, we are following the official csl specification. Anywhere we deviate from that entails breaking all/any tools that work with that standard and thus destroying interoperability.

As such I am closing this issue. How the data is input and stored is unrelated to how it is output and displayed.

As for our own internal templating system, which stretches beyond citation styles. We may need a processor to allow for displaying in such forms.. But let's leave that until a customer actually asks for it.
