### ISSUE TITLE
Edit list error message in Chrome

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#64]
Hi 

When trying trying edit a list Chrome, we've noticed the following error message. It appears when selecting the edit list option before any edits are made.

![chrome error patch](https://cloud.githubusercontent.com/assets/17139950/13105396/de1862b2-d55a-11e5-8487-501a41766025.PNG)

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for this. There is a completed fix that should address this. The fix is not yet on your instance of rebus:list, once it has been applied (which should be shortly), I'll let you know.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Richard

Your instance of rebus:list has now been updated to include this fix. So, I'll close this issue. Feel free to re-open if the issue continues.

Many thanks
Andrew
