### ISSUE TITLE
Search box not responsive to changing shape of browser

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#67]
I have noticed that the search box is not responsive when changing the shape of the browser (I'm using a PC and have tried in IE, Firefox & Chrome).    It appears responsive up to a certain point and then disappears from view.   

(Just to mention, in case it has impact, that I have also raised a separate suggestion to make the search box larger and in a more prominent place as with v.1.)

Thanks,
Heather

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for the comment. The search box will only appear in the navigation bar at the top of the page until the screen is shrunk to a certain point, at which point it moves into the slideout menu at the side. That is the designed behaviour anyway, if you are seeing something different, please let me know! :-)

Many thanks
Andrew

**Comment by SharonCocker** [comment]
Hi Andrew,

Thanks I can see this now.  I tried it on my phone and did find it rather tricky.  When I did a search for an existing list, unless you slide back the menu you are unable to see any results.  This makes searching on a phone very tricky I thought.    Please see attached screenshot showing my search for a list named "LRS".   

Thanks,
Heather

![search_phone_view_18feb16](https://cloud.githubusercontent.com/assets/12249067/13147562/3da85290-d651-11e5-804a-d5d2b40b9c03.PNG)

**Comment by AndrewIsh** [comment]
Hi Heather

Good point, the slideout menu should slide back in when the search results are populated. I'll create an issue to fix this.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1608

**Comment by AndrewIsh** [comment]
Hi Heather

I've now addressed this. When performing a search on a narrow display, as per your example, when there are search results to be viewed, a button labelled "View X results" (where X is the number of results) is displayed. Clicking this button slides the menu out of the way so the results can be viewed.

If you have any problems, feel free to reopen this issue.

Many thanks
Andrew
