### ISSUE TITLE
Login box

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#68]
Hi

When Rebus is closed down, on entering the homepage again it automatically prompts for a username and password, even if it's a few days later. If someone returns a while later they might only want to browse the lists, rather than go directly to login. Can the login screen be prevented from appearing in those circumstances, it seems to remember the previous session for a long-time. 

This might be due to the broswer being closed before logging out of Rebus, but I expect that will happen quite often. 

Hope this makes sense. 

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for the feedback. The behaviour you're seeing is by design. When returning to rebus:list after a period of time, if the user had not logged out, or the previous session timed out, the server detects this and requests authentication. The user is not obliged to log in, they can close the login box and proceed unauthenticated.

Currently it is not possible to customise this behaviour on a per customer basis. It's certainly an interesting idea, I'll create an issue on our internal Github site so we can discuss the possibility of making it a customer specific system preference.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1607

**Comment by richughes** [comment]
Hi Andrew

That's fine, I think there is still a related issue though.

When the login screen appears over the homepage as described above, clicking the cross removes it as you'd expect, but the links in the footer don't appear afterwards (see pic). They only appear if you refresh the screen and login again. Can you have a look at some point please as they should be visible when someone isn't logged in. The problem seems intermittent.

![footer disappearing](https://cloud.githubusercontent.com/assets/17139950/13175116/1bed2036-d700-11e5-88ce-05f1d9ec26e0.png)

Thanks again

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

I just had a quick test and couldn't replicate that. It's an interesting phenomenon though, once the footer is loaded it shouldn't need re-loading even if the user logs out. Could I ask you to keep an eye on it and see if there's any pattern? I'll have a double check at this end and make sure there's nothing amiss that might be causing it.

Many thanks
Andrew

**Comment by fionaborthwick1** [comment]
Hi there,

Just to add to this that I have seen what Richard reports.  I had their RL
system open (probably for a couple of days) and went to close the tab
today.  Obviously I had been logged out and returned to the home page but
there were no footers - only the PTFS Europe copyright statement.  I then
browsed the hierarchy, opened a reading list and when I scrolled to the
bottom the footers were there.

Fiona

On 19 February 2016 at 12:15, Andrew Isherwood notifications@github.com
wrote:

> Hi Richard
> 
> I just had a quick test and couldn't replicate that. It's an interesting
> phenomenon though, once the footer is loaded it shouldn't need re-loading
> even if the user logs out. Could I ask you to keep an eye on it and see if
> there's any pattern? I'll have a double check at this end and make sure
> there's nothing amiss that might be causing it.
> 
> Many thanks
> Andrew
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PTFS-Europe/rebus-list-2/issues/68#issuecomment-186192954
> .

## 

Fiona Borthwick
Customer Services Consultant, PTFS Europe Limited
Content Management and Library Solutions

+44 (0) 800 756 6803 (phone)
+44 (0) 7540 768230  (mobile)
+44 (0) 131 2088578  (direct dial)
+44 (0) 800 756 6384 (fax)fiona.borthwick@ptfs-europe.com
skype: fionaborthwick1
http://www.ptfs-europe.com

**Comment by AndrewIsh** [comment]
Hi Fiona

Thanks for the update. OK, I clearly need to work harder at trying replicate this! In the meantime, if anyone spots a behavioural pattern (i.e. a sequence of actions that always causes it to happen), can they let me know, that would be a great help!

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
I've created a separate issue for the footer related portion of this issue:
https://github.com/PTFS-Europe/rebus-list/issues/1656

**Comment by AndrewIsh** [comment]
Hi Richard

Are you still seeing this problem? I've not seen it for some time.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Inactivity, unable to replicate.
