### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#69]
Hello,

I just tried to log in to rebus to do some testing, but my log in box came up with those weird characters:
![logging in](https://cloud.githubusercontent.com/assets/16195154/13221810/147faf40-d975-11e5-8c66-2113900ac187.png)

When I tried to edit the reading list, the edit button wasn't there. It reappeared only after logging out and back in. The weird characters stayed at the top of the log in box though.

**Comment by JoannaBek** [comment]
PS Just noticed this is the same issue as in #58 - I am using Chrome, and the characters appear every time I'm trying to log in.

**Comment by AndrewIsh** [comment]
Hi Joanna

As you spotted, we're aware of this issue and are looking into a fix. I'll close this issue in favour of the already existing one.

Many thanks
Andrew
