### ISSUE TITLE
Selecting items

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#70]
Hello,

I have just tried to select an item on my list.
![selecting items](https://cloud.githubusercontent.com/assets/16195154/13222068/27e7bcf2-d976-11e5-9aaa-10a87022e296.PNG)

Instead of selecting just this one, Rebus selected all the items that I have added "in one go" (searching catalog and then pressing 'plus' button on various items from this particular search).
![selecting items 2](https://cloud.githubusercontent.com/assets/16195154/13222104/4d264308-d976-11e5-92d1-60ba4755de2d.PNG)

It does that with all the items from this group, doesn't matter which one I press.

**Comment by JoannaBek** [comment]
I have checked the issue today - it is gone for the items from the previous session, but it reappears when I try to add a few new items from the same search.

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for this, apologies for the delay in getting back to you. I think I know what this is. I'll create a issue at our end to get this fixed. In the meantime, after adding an item, saving a draft then re-opening should fix it.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1621

**Comment by AndrewIsh** [comment]
Hi Joanna

This issue has now been fixed internally. I'll push an update to preview2 later. I'll now close this issue. If you have further problems, feel free to re-open it.

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hello,

I just got another multi-selection appearing on my list when trying to add new items:
![image](https://cloud.githubusercontent.com/assets/16195154/13456806/d4dd4b74-e05c-11e5-8e63-c8d8dacf0041.png)
