### ISSUE TITLE
Search box not working

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#71]
Hi

Our search box isn't working at present, no response from searches at all in Firefox or Chrome. 

Many thanks

Richard

**Comment by richughes** [comment]
Hi 

Search seems to be working fine this morning. 

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for the update. Martin pushed a fix for this at the end of Wednesday, glad it is now sorted.

I'll close this issue.

Many thanks
Andrew
