### ISSUE TITLE
Manual list entries not working

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#72]
Hi

Kasia and I have lost the rights to add manual entries. The screen opens, but the dropdown menu for material type doesn't work, a red circle with a line through it appears whenever we try to access it. 

![manual entries not working](https://cloud.githubusercontent.com/assets/17139950/13287464/251629ca-daff-11e5-83a8-b052fde2171f.png)

Please can you fix this as soon as possible, as it is slowing Kasia's work.

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Apologies for that, should be fixed now. Feel free to re-open if not.

Regards
Andrew
