### ISSUE TITLE
Site appearance changing drastically - CSS not registering?

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#74]
Hi

Almost everytime I press F5 today the appearance of the site changes in someway. Sometimes it seems to be recognising part of our CSS, but at other times it recognises none of it (see pics). I've not made any changes to the CSS area in the last few days. It's happening in Chrome and Firefox. 

![css not working](https://cloud.githubusercontent.com/assets/17139950/13319409/5c6bf476-dbb9-11e5-8553-36dec9ac0569.png)

![css not working 2](https://cloud.githubusercontent.com/assets/17139950/13319355/0477fe22-dbb9-11e5-839f-61bfab60903e.png)

Can you have a look?

Thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for this. I had a few attempts to replicate during the day and wasn't able to, are you still seeing this?

Many thanks
Andrew

**Comment by richughes** [comment]
Hi Andrew

It was fine again after the break in service yesterday afternoon and there doesn't seem to be any problems this morning. 

I'll let you know if it happens again. 

Many thanks

Richard

**Comment by AndrewIsh** [comment]
OK, great, thanks. I'm suspecting it was something to do with CSS caching. Anyway, let me know if it happens again, I'll close this issue for now.

Many thanks
Andrew
