### ISSUE TITLE
Browse view not appearing correctly

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#75]
Hi, 

The page view after clicking the Browse option is currently displaying incorrectly - please see screenshot.   I'm using Chrome, but the same also happens in Firefox.  

Thanks
Heather
![image](https://cloud.githubusercontent.com/assets/12249067/13351215/f7c69fb6-dc7c-11e5-9c2d-50734bab817a.png)

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for that. It appears to be a bug, I'll create an issue at our end and get it fixed ASAP.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1634

**Comment by AndrewIsh** [comment]
Hi Heather

I've just fixed this, so I'll close this issue. Feel free to re-open if it continues to be a problem.

Many thanks
Andrew
