### ISSUE TITLE
[Manage hierarchy] Edit user roles option

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#76]
Hi,

Within the Manage Hierarchy, I am not able to get the "Edit User Roles" option to work - I wasn't sure if this was actually working yet or not.  I've included a screenshot, although it doesn't pickup the red no-entry symbol I see when I try to type in the "Search for Users" field.  

Thanks,
Heather

![image](https://cloud.githubusercontent.com/assets/12249067/13352874/464c12c8-dc88-11e5-9173-263e98176492.png)

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for that. I'll create an issue at our end and investigate.

Regards
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1636

**Comment by AndrewIsh** [comment]
Hi Sharon

I've just fixed this internally. I'll push an update to preview2 a bit later. I'll close this issue, if you continue to see problems, feel free to re-open it.

Many thanks
Andrew
