### ISSUE TITLE
Problem with Edit Mode within a list

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#77]
Hi,

I've just been trying to edit a list and it keeps throwing me out - I've tried a few times.  I could click on the edit button initially and the orange band did appear, however when I tried to go further I was thrown out and the log in box appeared and also (strangely) it download box also appeared - please see screenshot.  

Many thanks,
Heather

![image](https://cloud.githubusercontent.com/assets/12249067/13353605/69c5ef6c-dc8d-11e5-9505-07fc9d1cfa85.png)

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for that, a really odd one! OK, I'll create an issue at our end and investigate. Do you know roughly what time it happened?

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1637

**Comment by SharonCocker** [comment]
Hi Andrew,

Apologies not to get back to you sooner, I was out of the office on Friday afternoon.  The issue happened about 1pm Friday.   

Heather

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for that. I've not been able to replicate it. Can you let me know if it happens again, with an exact time that it occurs and I'll take a look.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
I'm going to close this as I'm assuming it's now fixed. Feel free to re-open if you're still having the problem.

Many thanks
Andrew
