### ISSUE TITLE
Problem with logging in 26/2/16 14:23

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#78]
Hello,

After my unsuccessful tagging issues, I can't now login at all. Here's the video from my struggle:
https://www.youtube.com/watch?v=6txqClxHbSc

**Comment by AndrewIsh** [comment]
Hi Joanna

Extremely odd. I just managed to log in and enter edit mode on your list as an admin user. Can you try going to the "About rebus:list" page, scroll down to the bottom of the page, click the big red "Purge all rebus:list local storage" button, then logout, login and try getting into your list again.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Thanks for the timestamp by the way, very useful!

**Comment by JoannaBek** [comment]
Hello Andrew,

Just tried that, and after clicking edit list it brought me back to the login screen, but this time without the funny characters:
![image](https://cloud.githubusercontent.com/assets/16195154/13355234/4145cbac-dc97-11e5-95e9-604ee419b08c.png)

**Comment by AndrewIsh** [comment]
Hi Joanna

I've increased the verbosity of the logging on the server, could you please log out, log back in again, delete your cache and refresh, then try again. Could you please make a note of exactly what time you try it so I can look in the logs.

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hi Andrew,

08:29 start of the try.

First, I couldn't log out - the button wasn't active at all, and clicking on it didn't do anything. So I refreshed the page - it worked then.

Logged back in, cleared the cache, tried tagging book through the select item - it worked! And I could publish the list, the tag was there (added tag Week 10 to second position).

However when I came back to the edit mode, the tag I just added disappeared from edit view. Just tried adding it again (08:37) - it doesn't do anything. It is there though in the published view. 

So tried again and now I am getting this box when clicking edit:
![image](https://cloud.githubusercontent.com/assets/16195154/13389450/fdf052c0-debf-11e5-89c1-0c773cdc8e02.png)

I clicked "recover" and nothing happened, except seeing an error:
![image](https://cloud.githubusercontent.com/assets/16195154/13389468/1a9d45d6-dec0-11e5-823d-8fb746048ec2.png)

The tag disappeared as well.

Now I can't add the tag at all. 

On the bright side - I am not being asked to be logged back in! Not yet at least...

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for the update, sounds like you've been having fun! I'm going to take a look at this and try and figure out what's going on.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1640

**Comment by AndrewIsh** [comment]
Hi Joanna

As per issue #73 I'd be interested to know if you're still experiencing these problems. Again, I've not been able to replicate them while testing your list.

Many thanks
Andrew

**Comment by CFWilliams** [comment]
Leeds Beckett are seeing these same issues; makes exploring the system difficult.

**Comment by AndrewIsh** [comment]
Hi both

Are you still seeing these problems?

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hello, 

I haven't had this issue for a while.

Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

I'll close this issue. Feel free to reopen if it comes back.

Many thanks
Andrew
