### ISSUE TITLE
Test lists disappeared 09:10 29/2/16

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#80]
Hello,

I tried to add a few items to my test list, but they did not appear in the published list. I then tried to log out, clear cache, log back in (Chrome). Now my list (JB test) completely disappeared:

![image](https://cloud.githubusercontent.com/assets/16195154/13390170/99559b9a-dec4-11e5-9f00-e788d198ab0f.png)

I tried to log in in Mozilla as well, but the result is the same.

Thanks,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for this. I've asked @mrenvoize to take a look at this, as it likely falls into his side of development.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
HI Joanna

Are you still seeing this problem? I can see your test list in the browse page this morning.

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hello Andrew,

I can't get in to Rebus at all this morning.

![image](https://cloud.githubusercontent.com/assets/16195154/13455748/31714404-e057-11e5-90a5-bac3f8af3dbd.png)

**Comment by AndrewIsh** [comment]
Hi Joanna

It looks like you've got the URL wrong, it should be: https://preview2.rebuslist.com

Hope this helps.

Andrew

**Comment by JoannaBek** [comment]
Oh yes, I blame morning. My test list appeared as well, thanks!

**Comment by AndrewIsh** [comment]
Glad it appeared. Sounds like you need a coffee, I'm on my second already, that can't be good...

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Closing
