### ISSUE TITLE
Selecting new items (re: #70)

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#82]
Hello,

I just had another multi-selection of new items when trying to select just one:
![image](https://cloud.githubusercontent.com/assets/16195154/13456844/ff8b78f0-e05c-11e5-88de-83823d289be1.png)

All the best,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

I just tested and this is working as expected for me.

I think you must have a cached version of the old code. Can you clear your browser cache (Ctrl + F5 should do this) and try again.

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hello Andrew,

Yup, that seems to be working fine now. I tried on three different batches of items and the problem didn't reoccur. 

Thanks a lot,
Joanna

**Comment by AndrewIsh** [comment]
Excellent. I'll close this issue. If you see it again, feel free to re-open.

Many thanks
Andrew
