### ISSUE TITLE
Error when adding new items

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#83]
Hello,

I just had this error message suddenly jump out on me when trying to add extra items:
![image](https://cloud.githubusercontent.com/assets/16195154/13456897/2cefd520-e05d-11e5-8eea-130a118af5ee.png)

All the best,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Interesting, can you let me know which item(s) you were trying to add?

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hello Andrew,

I captured similar problem on the video. It was just a random search for a keyword 'industry'. The items I was trying to add when the error appeared did not record on my list anyway:
https://youtu.be/jE10Gmo2K_Q

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for the video, extremely useful. OK, leave it with me, I'll see what I can do.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1677

**Comment by AndrewIsh** [comment]
Hi Joanna

This problem has now been fixed. I'll close this issue but feel free to re-open it if you see a repetition of the problem.

Many thanks
Andrew
