### ISSUE TITLE
Newly added items visible in published mode, but not in edit mode

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#85]
Hi,

I just added a few new items and tagged them simultaneously, then published my list - everything worked fine and my list looked like:

![image](https://cloud.githubusercontent.com/assets/16195154/13462254/803e2d96-e07e-11e5-956c-0b83eeb7eeee.png)

But when I came back to my edit mode, the items I have added disappeared:

![image](https://cloud.githubusercontent.com/assets/16195154/13462276/9848b280-e07e-11e5-9e75-9844f774ac05.png)

They are there when I publish the list, but no sign of them in the edit mode.

https://youtu.be/6pqxVSvrH3U

**Comment by AndrewIsh** [comment]
Hi Joanna

Many thanks for this. I'm going to pull @mrenvoize in on this one as it looks like it might involve his side of rebus:list.

As an aside, can I ask what browser you're using?

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hi Andrew,

I use Google Chrome (Version 48.0.2564.116 m).

Thanks,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

We've recently pushed out updates that should address this problem. I'll close this issue. Feel free to re-open if you are still seeing the problem.

Many thanks
Andrew
