### ISSUE TITLE
Multiple notification after action (re #13)

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#87]
Hi,

I have just deleted my sublist and got multiple notification appear:

![image](https://cloud.githubusercontent.com/assets/16195154/13464123/82f5fc40-e087-11e5-93e5-42a3417b4534.png)

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for this. Interesting, we had this problem a long time ago and I thought I'd fixed it, perhaps not! I'll create an issue at our end and investigate.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1663

**Comment by AndrewIsh** [comment]
Hi Joanna

I've just pushed a fix to preview2 that should address this. I'll close this issue. Feel free to re-open if you feel it hasn't been resolved.

Many thanks
Andrew
