### ISSUE TITLE
Functionality issue: no way of changing the name of the list in the 'manage hierarchy' level

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#91]
Hello,

Would it be possible to add the function (which was there in the previous version) of changing the name of the list on the 'manage hierarchy' level? At the moment one has to go into the list to change it, which is very impractical and will take a lot of time if one has to change names of all of the sub-lists.

Thanks a lot,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for this. I'll add this as a possible enhancement.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1666

**Comment by AndrewIsh** [comment]
This has now been completed. Closing.
