### ISSUE TITLE
Unable to swap places between my two sub-lists on 'manage hierarchy' level

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#92]
Hello,

I have created two sub-lists for my test list, but I am unable to swap them around - the 'Week 2' one constantly springs back to the original position.

![image](https://cloud.githubusercontent.com/assets/16195154/13498984/3f7b0834-e154-11e5-933b-c0f6348ce1db.png)

Thanks,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

This has previously been raised here: https://github.com/PTFS-Europe/rebus-list-2/issues/54

I'll close this issue and reference it in the other issue.

Many thanks
Andrew
