### ISSUE TITLE
When list is published, user is not taken to the top of the list

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#94]
Hello,

When a list is published, the user is taken to probably the middle of the list (not even the bit where one was working before). Would it be possible to change it, so that one comes to the top after publishing?

Thanks,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for this. There is currently an enhancement in progress that should address this. I'll update here once it's done.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Joanna

Apologies for the delay in updating this. An update was pushed out some time ago that should have addressed this. I'll close this issue, feel free to re-open if the problem persists.

Many thanks
Andrew
