### ISSUE TITLE
Query regarding working on a list

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#95]
Hello,

In the previous version of the Rebus, I was usually working with two tabs open for a list - one in an admin mode, second in a user one. That was to ensure that all links were working correctly and taking students to the right resources. The admin mode was 'live', so refreshing the student mode was bringing just added resource up.

Is that the case in the new version as well, or one would need to press 'publish' every time they wanted to see the results in the student mode?

Thanks a lot,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

As you know, the workflow with rebus:list 2 is quite different, and will not allow the scenario you describe. The reason being that when you are editing a list, you are editing a draft, this draft is not available in the student mode until it is published. However, the draft edit mode and student mode are virtually identical in appearance, so I'd hope that would remove the need to "preview" the list in student mode.

Can you describe what you would are not seeing in the draft mode that would require you to "preview" the list in student mode, maybe the appearance of draft mode can be improved accordingly.

Many thanks
Andrew

**Comment by JoannaBek** [comment]
Hello Andrew,

We check our journal articles in the student mode after we add them - that is because of the capricious nature of the various platforms that are providing the access to the journals. They are not always linking correctly despite all the correct information, and DOI are also not always sending students to the right article. So we would check them as we go, just to make sure everything is working as it should.

All the best,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for the additional information. So, ideally, you'd want the linking buttons for Fulltext etc. to be displayed while in draft mode. OK, I'll create an issue and look at that.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
https://github.com/PTFS-Europe/rebus-list/issues/1669

**Comment by AndrewIsh** [comment]
Hi Joanna

A fix for this has recently been implemented. It will be pushed out to your server very shortly. I'll update this issue once it is available.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Joanna

This is now live on preview. I'll close this issue. If you have any further problems, feel free to reopen.

Many thanks
Andrew
