### ISSUE TITLE
[Edit Mode] New items not appearing until list published

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#97]
Hi,

I've noticed that when editing a list, new items do not always appear until the list is published.  I've tested by adding various types of items and haven't really seen a pattern.  Please see the screenshots of two separate occasions when this has happened this morning (I had published the list in between time).   The two items which are missing from the first screenshot are: "Hawaiian Journal of History" and "New Zealand Journal of History" - on the screenshot showing in edit mode, neither journal entry appears whereas once the list is published (second screenshot) they both suddenly appear.  The same thing happens again in the third screenshot, ie my entry for the book "The transformed library" has not appeared, but once the list is published the book entry suddenly appears.   I am using Chrome btw. 

Many thanks,
Heather

![image](https://cloud.githubusercontent.com/assets/12249067/13635866/6979f1f8-e5f6-11e5-808c-4aae5627827f.png)

![image](https://cloud.githubusercontent.com/assets/12249067/13635922/bd8cf86c-e5f6-11e5-959a-bb3b557e3f34.png)

![image](https://cloud.githubusercontent.com/assets/12249067/13635940/d47e4ed6-e5f6-11e5-9d76-918c37611fe5.png)

![image](https://cloud.githubusercontent.com/assets/12249067/13635946/e20501d0-e5f6-11e5-9866-261b46f71c85.png)

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for that. Are these items you're adding via a search or manually?

Many thanks
Andrew

**Comment by SharonCocker** [comment]
Hi Andrew,

They are all via a search.  
(However I am in the middle of trying to add some items manually and not having much success, but I'll raise that as a separate issue once I've double-checked what the problems are.)    

Thanks,
Heather

**Comment by AndrewIsh** [comment]
Hi Heather

I've this morning pushed out an update which should address this. Could you please let me know if you continue to see problems?

Many thanks
Andrew

**Comment by SharonCocker** [comment]
Hi Andrew,

Just did some quick testing and so far so good!  I added a number of items in two separate actions and all worked okay on both occasions.   I'll pass on the information to others in our team as I know they'd originally experience similar.   

Many thanks,
Heather

**Comment by AndrewIsh** [comment]
Hi Heather

That's good to hear. I'll close this issue for now, feel free to re-open it if you're still seeing problems.

Many thanks
Andrew
