### ISSUE TITLE
Can't edit a particular list

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#99]
Hi 

When I try to edit the following list, the edit mode appears for a split second but the screen then refreshes itself back to the public view. Clicking edit again gives the same result. 

https://uhi.rebuslist.com/#/list/1541 

The list was previosuly stuck in the "oops, do you want to recover" loop. Clicking recover didn't work, so I pressed discard earlier today. 

Many thanks

Richard

**Comment by AndrewIsh** [comment]
Hi Richard

I just checked and I was able to enter edit mode and exit on that list, this leads me to think that maybe something has got left behind from a previous editing session. Can you go to the "About rebus:list" page, then scroll to the bottom and click the big red "Purge all rebus:list local storage" button. You'll need to login again afterwards, but can you see if that fixes the problem?

Many thanks
Andrew

**Comment by richughes** [comment]
Hi Andrew

Thanks, I pressed the red button and was able to get back in afterwards. Will close this one. 

Cheers

Richard
